import {
  Assignment,
  AssignmentState,
  Submission,
  SubmissionState,
  Category,
  Session,
  AssignmentAssigneeMode,
  Person,
  Class as EdLinkClass,
  SubmissionFlag,
} from '@edlink/typescript';
import { RewardableEvent } from '../entities/RewardableEvent.entity';
import { Class } from '../entities';
import { v4 as uuidv4 } from 'uuid';

// Note: could mock all data and use it to provide a usable demo of the app
// maybe good for testing too, but how would I implement it across the app? specific data responses for every single request?
// May want to turn these into functions that return data instead of hard coded values too, depends, probably a combo

const sampleCategories: Category[] = [];
const sampleSessions: Session[] = [];

export const DEMO_STUDENT: Partial<Person> = {
  id: '261f71b1-fd80-41f1-b0d5-af40ebd91be4',
  first_name: 'John',
  last_name: 'Doe',
};
export const DEMO_TEACHER: Partial<Person> = {
  id: '8286451d-0ab3-43ae-b4d7-0536a1ca85b3',
  first_name: 'Dakota',
  last_name: 'Gordon',
};
export const DEMO_CLASSES: Partial<EdLinkClass>[] = [
  {
    id: '19698799-1433-4118-b4f1-561345dfa877',
    name: 'Math 101',
  },
  {
    id: '2963b5de-a871-4aad-8e89-6e263311e99e',
    name: 'Math 101 (Section 1)',
  },
  {
    id: 'a9066cb7-09f4-43ed-8023-75f9d0b84032',
    name: 'Math 101 (Section 2)',
  },
];

export const MOCK_COURSE = [];

export const CREATE_DEMO_ASSIGNMENTS = [
  {
    title: 'Math Assignment 3',
    description: 'This is the description of the assignment',
    due_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    grading_type: 'points',
    points_possible: 10,
    category_id: '00000000-0000-0000-0000-000000000000', // homework category
    state: AssignmentState.Open,
  },
  {
    title: 'Math Assignment 2',
    description: 'This is the description of the assignment',
    due_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    grading_type: 'percent',
    // points_possible: 10,
    category_id: '00000000-0000-0000-0000-000000000000', // homework category
  },
  {
    title: 'Math Assignment 1',
    description: 'This is the description of the assignment',
    due_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    grading_type: 'percent',
    // points_possible: 10,
    category_id: '00000000-0000-0000-0000-000000000000', // homework category
  },
  {
    title: 'Math Assignment 4',
    description: 'This is the description of the assignment',
    due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    grading_type: 'letter_grade',
    points_possible: 20,
    category_id: '00000000-0000-0000-0000-000000000000', // homework category
  },
  {
    title: 'Math Assignment 5',
    description: 'This is the description of the assignment',
    due_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    grading_type: 'pass_fail',
    points_possible: 15,
    category_id: '00000000-0000-0000-0000-000000000000', // homework category
  },
  {
    title: 'Math Assignment 6',
    description: 'This is the description of the assignment',
    due_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    grading_type: 'percent',
    points_possible: 25,
    category_id: '00000000-0000-0000-0000-000000000000', // homework category
  },
  {
    title: 'Math Assignment 7',
    description: 'This is the description of the assignment',
    due_date: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    grading_type: 'points',
    points_possible: 30,
    category_id: '00000000-0000-0000-0000-000000000000', // homework category
  },
  {
    title: 'Math Assignment 8',
    description: 'This is the description of the assignment',
    due_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    grading_type: 'points',
    points_possible: 40,
    category_id: '00000000-0000-0000-0000-000000000000', // homework category
  },
  {
    title: 'Math Assignment 9',
    description: 'This is the description of the assignment',
    due_date: new Date(Date.now() + 16 * 24 * 60 * 60 * 1000).toISOString(),
    grading_type: 'points',
    points_possible: 50,
    category_id: '00000000-0000-0000-0000-000000000000', // homework category
  },
];
export const MOCK_DEMO_ASSIGNMENTS: Assignment[] = [
  {
    id: 'assignment-demo1',
    title: 'Math Homework 1',
    description: 'Complete the exercises on page 42',
    description_plaintext: 'Complete the exercises on page 42',
    state: AssignmentState.Open,
    created_date: '2025-01-01T12:00:00Z',
    updated_date: '2025-01-01T12:00:00Z',
    properties: {},
    attachments: [],
    assignee_mode: AssignmentAssigneeMode.All, // or Individuals
    assignee_ids: ['person-1'],
    due_date: '2025-01-08T12:00:00Z',
    display_date: '2025-01-01T12:00:00Z',
    start_date: '2025-01-01T12:00:00Z',
    end_date: '2025-01-08T12:00:00Z',
    points_possible: 100,
    grading_type: 'points', // or 'letter_grade', 'pass_fail', 'percent'
    submission_types: ['online_text_entry', 'online_url', 'online_upload'],
    max_attempts: 3,
    session_id: 'session-1',
    category_id: 'category-1',
  },
  {
    id: 'assignment-demo2',
    title: 'Math Homework 2',
    description: 'Complete the exercises on page 42',
    description_plaintext: 'Complete the exercises on page 42',
    state: AssignmentState.Open,
    created_date: '2025-01-01T12:00:00Z',
    updated_date: '2025-01-01T12:00:00Z',
    properties: {},
    attachments: [],
    assignee_mode: AssignmentAssigneeMode.All, // or Individuals
    assignee_ids: ['person-1'],
    due_date: '2025-01-08T12:00:00Z',
    display_date: '2025-01-01T12:00:00Z',
    start_date: '2025-01-01T12:00:00Z',
    end_date: '2025-01-08T12:00:00Z',
    points_possible: 100,
    grading_type: 'points', // or 'letter_grade', 'pass_fail', 'percent'
    submission_types: ['online_text_entry', 'online_url', 'online_upload'],
    max_attempts: 3,
    session_id: 'session-1',
    category_id: 'category-1',
  },
  {
    id: 'assignment-demo3',
    title: 'Math Homework 3',
    description: 'Complete the exercises on page 42',
    description_plaintext: 'Complete the exercises on page 42',
    state: AssignmentState.Open,
    created_date: '2025-01-01T12:00:00Z',
    updated_date: '2025-01-01T12:00:00Z',
    properties: {},
    attachments: [],
    assignee_mode: AssignmentAssigneeMode.All, // or Individuals
    assignee_ids: ['person-1'],
    due_date: '2025-01-08T12:00:00Z',
    display_date: '2025-01-01T12:00:00Z',
    start_date: '2025-01-01T12:00:00Z',
    end_date: '2025-01-08T12:00:00Z',
    points_possible: 100,
    grading_type: 'points', // or 'letter_grade', 'pass_fail', 'percent'
    submission_types: ['online_text_entry', 'online_url', 'online_upload'],
    max_attempts: 3,
    session_id: 'session-1',
    category_id: 'category-1',
  },
  {
    id: 'assignment-demo4',
    title: 'Math Homework 4',
    description: 'Solve the equations on page 50',
    description_plaintext: 'Solve the equations on page 50',
    state: AssignmentState.Open,
    created_date: '2025-01-02T12:00:00Z',
    updated_date: '2025-01-02T12:00:00Z',
    properties: {},
    attachments: [],
    assignee_mode: AssignmentAssigneeMode.All,
    assignee_ids: ['person-2'],
    due_date: '2025-01-09T12:00:00Z',
    display_date: '2025-01-02T12:00:00Z',
    start_date: '2025-01-02T12:00:00Z',
    end_date: '2025-01-09T12:00:00Z',
    points_possible: 100,
    grading_type: 'points',
    submission_types: ['online_text_entry', 'online_url', 'online_upload'],
    max_attempts: 3,
    session_id: 'session-2',
    category_id: 'category-2',
  },
  {
    id: 'assignment-demo5',
    title: 'Math Homework 5',
    description: 'Graph the functions on page 60',
    description_plaintext: 'Graph the functions on page 60',
    state: AssignmentState.Open,
    created_date: '2025-01-03T12:00:00Z',
    updated_date: '2025-01-03T12:00:00Z',
    properties: {},
    attachments: [],
    assignee_mode: AssignmentAssigneeMode.All,
    assignee_ids: ['person-3'],
    due_date: '2025-01-10T12:00:00Z',
    display_date: '2025-01-03T12:00:00Z',
    start_date: '2025-01-03T12:00:00Z',
    end_date: '2025-01-10T12:00:00Z',
    points_possible: 100,
    grading_type: 'points',
    submission_types: ['online_text_entry', 'online_url', 'online_upload'],
    max_attempts: 3,
    session_id: 'session-3',
    category_id: 'category-3',
  },
  {
    id: 'assignment-demo6',
    title: 'Math Homework 6',
    description: 'Complete the word problems on page 70',
    description_plaintext: 'Complete the word problems on page 70',
    state: AssignmentState.Open,
    created_date: '2025-01-04T12:00:00Z',
    updated_date: '2025-01-04T12:00:00Z',
    properties: {},
    attachments: [],
    assignee_mode: AssignmentAssigneeMode.All,
    assignee_ids: ['person-4'],
    due_date: '2025-01-11T12:00:00Z',
    display_date: '2025-01-04T12:00:00Z',
    start_date: '2025-01-04T12:00:00Z',
    end_date: '2025-01-11T12:00:00Z',
    points_possible: 100,
    grading_type: 'points',
    submission_types: ['online_text_entry', 'online_url', 'online_upload'],
    max_attempts: 3,
    session_id: 'session-4',
    category_id: 'category-4',
  },
  {
    id: 'assignment-demo7',
    title: 'Math Homework 7',
    description: 'Review the concepts from Chapter 3',
    description_plaintext: 'Review the concepts from Chapter 3',
    state: AssignmentState.Open,
    created_date: '2025-01-05T12:00:00Z',
    updated_date: '2025-01-05T12:00:00Z',
    properties: {},
    attachments: [],
    assignee_mode: AssignmentAssigneeMode.All,
    assignee_ids: ['person-5'],
    due_date: '2025-01-12T12:00:00Z',
    display_date: '2025-01-05T12:00:00Z',
    start_date: '2025-01-05T12:00:00Z',
    end_date: '2025-01-12T12:00:00Z',
    points_possible: 100,
    grading_type: 'points',
    submission_types: ['online_text_entry', 'online_url', 'online_upload'],
    max_attempts: 3,
    session_id: 'session-5',
    category_id: 'category-5',
  },
  {
    id: 'assignment-demo8',
    title: 'Math Homework 8',
    description: 'Practice the problems on page 80',
    description_plaintext: 'Practice the problems on page 80',
    state: AssignmentState.Open,
    created_date: '2025-01-06T12:00:00Z',
    updated_date: '2025-01-06T12:00:00Z',
    properties: {},
    attachments: [],
    assignee_mode: AssignmentAssigneeMode.All,
    assignee_ids: ['person-6'],
    due_date: '2025-01-13T12:00:00Z',
    display_date: '2025-01-06T12:00:00Z',
    start_date: '2025-01-06T12:00:00Z',
    end_date: '2025-01-13T12:00:00Z',
    points_possible: 100,
    grading_type: 'points',
    submission_types: ['online_text_entry', 'online_url', 'online_upload'],
    max_attempts: 3,
    session_id: 'session-6',
    category_id: 'category-6',
  },
  {
    id: 'assignment-demo9',
    title: 'Math Homework 9',
    description: 'Solve the practice test on page 90',
    description_plaintext: 'Solve the practice test on page 90',
    state: AssignmentState.Open,
    created_date: '2025-01-07T12:00:00Z',
    updated_date: '2025-01-07T12:00:00Z',
    properties: {},
    attachments: [],
    assignee_mode: AssignmentAssigneeMode.All,
    assignee_ids: ['person-7'],
    due_date: '2025-01-14T12:00:00Z',
    display_date: '2025-01-07T12:00:00Z',
    start_date: '2025-01-07T12:00:00Z',
    end_date: '2025-01-14T12:00:00Z',
    points_possible: 100,
    grading_type: 'points',
    submission_types: ['online_text_entry', 'online_url', 'online_upload'],
    max_attempts: 3,
    session_id: 'session-7',
    category_id: 'category-7',
  },
];

export const MOCK_SUBMISSIONS: Submission[] = [
  {
    id: 'submission-demo1',
    person_id: 'person-1', // edlink person id
    state: SubmissionState.Returned,
    grade: 'A',
    grade_points: 95,
    created_date: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updated_date: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    properties: {},
    flags: [], // ['late', 'missing', 'excused']
    attempts: [],
    grade_comment: 'Good job!',
    extra_attempts: 0,
    override_due_date: null,
    grader_id: null,
  },
  {
    id: 'submission-demo2',
    person_id: 'person-1',
    state: SubmissionState.Submitted,
    grade: 'A',
    grade_points: 90,
    created_date: new Date(Date.now() - 86400000).toISOString(),
    updated_date: new Date(Date.now() - 86400000).toISOString(),
    properties: {},
    flags: [],
    attempts: [],
    grade_comment: null,
    extra_attempts: 0,
    override_due_date: null,
    grader_id: null,
  },
  {
    id: 'submission-demo3',
    person_id: 'person-1',
    state: SubmissionState.Submitted,
    grade: 'A',
    grade_points: 90,
    created_date: new Date(Date.now() - 86400000).toISOString(),
    updated_date: new Date(Date.now() - 86400000).toISOString(),
    properties: {},
    flags: [],
    attempts: [],
    grade_comment: null,
    extra_attempts: 0,
    override_due_date: null,
    grader_id: null,
  },
  {
    id: 'submission-demo4',
    person_id: 'person-2',
    state: SubmissionState.Returned,
    grade: 'B',
    grade_points: 85,
    created_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    properties: {},
    flags: [],
    attempts: [],
    grade_comment: 'Well done!',
    extra_attempts: 0,
    override_due_date: null,
    grader_id: null,
  },
  {
    id: 'submission-demo5',
    person_id: 'person-3',
    state: SubmissionState.Returned,
    grade: 'C',
    grade_points: 75,
    created_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    properties: {},
    flags: [SubmissionFlag.Late],
    attempts: [],
    grade_comment: 'Try to submit on time.',
    extra_attempts: 0,
    override_due_date: null,
    grader_id: null,
  },
  {
    id: 'submission-demo6',
    person_id: 'person-4',
    state: SubmissionState.Returned,
    grade: null,
    grade_points: null,
    created_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updated_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    properties: {},
    flags: [SubmissionFlag.Missing],
    attempts: [],
    grade_comment: null,
    extra_attempts: 0,
    override_due_date: null,
    grader_id: null,
  },
  {
    id: 'submission-demo7',
    person_id: 'person-5',
    state: SubmissionState.Returned,
    grade: 'A',
    grade_points: 95,
    created_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    properties: {},
    flags: [],
    attempts: [],
    grade_comment: 'Excellent work!',
    extra_attempts: 0,
    override_due_date: null,
    grader_id: null,
  },
  {
    id: 'submission-demo8',
    person_id: 'person-6',
    state: SubmissionState.Returned,
    grade: 'B+',
    grade_points: 88,
    created_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updated_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    properties: {},
    flags: [],
    attempts: [],
    grade_comment: 'Good effort!',
    extra_attempts: 0,
    override_due_date: null,
    grader_id: null,
  },
  {
    id: 'submission-demo9',
    person_id: 'person-7',
    state: SubmissionState.Returned,
    grade: null,
    grade_points: null,
    created_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    properties: {},
    flags: [SubmissionFlag.Excused],
    attempts: [],
    grade_comment: 'Excused from this assignment.',
    extra_attempts: 0,
    override_due_date: null,
    grader_id: null,
  },
  // ...more submissions...
];

const rewardEventGenerator = (
  assignment?: Assignment,
  submission?: Submission,
  options: { status: string; createdAt: Date; updatedAt: Date } = {
    status: 'UNCLAIMED',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
): RewardableEvent => {
  return {
    id: uuidv4(),
    // experienceId: null,
    eventType: 'type-1',
    submission: null,
    assignment: null,
    student: null,
    teachers: null,
    school: null,
    class: null,
    experienceEvents: [],
    status: options.status,
    createdAt: options.createdAt,
    updatedAt: options.updatedAt,
  };
};

export const MOCK_REWARDABLE_EVENTS: RewardableEvent[] = [
  rewardEventGenerator(),
  rewardEventGenerator(),
  rewardEventGenerator(),
];
