export const enum EXPANSE_TERMS_OF_SERVICE_SECTIONS {
  AGREE_TO_TERMS = "agree-to-terms",
  INTELLECTUAL_PROPERTY_RIGHTS = "intellectual-property-rights",
  USER_REPRESENTATIONS = "user-representations",
  USER_REGISTRATIONS = "user-registrations",
  PROHIBITED_ACTIVITIES = "social-prohibited_activities",
  USER_GENERATED_CONTRIBUTIONS = "user-generated-contributions",
  CONTRIBUTION_LICENSE = "contribution-license",
  SOCIAL_MEDIA = "social-media",
  SUBMISSIONS = "submissions",
  SITE_MANAGEMENT = "site-management",
  PRIVACY_POLICY = "privacy-policy",
  TERMS_AND_TERMINATION = "terms-and-termiation",
  MODIFICATIONS_AND_INTERRUPTIONS = "modifications-and-interruptions",
  GOVERNING_LAW = "governing-law",
  DISPUTE_RESOLUTION = "dispute-resolution",
  CORRECTIONS = "corrections",
  DISCLAIMER = "disclaimer",
  LIMITATIONS_OF_LIABILITY = "limitations-of-liability",
  INDEMNIFICATION = "indemnification",
  USER_DATA = "viewing-your-data",
  ELECTRONIC_COMMUNICATIONS_TRANSACTIONS_AND_SIGNATURES = "electronic-communications-and-signatures",
  CALIFORNIA_USERS_AND_RESIDENTS = "california-users-and-residents",
  MISCELLANEOUS = "miscellaneous",
  CONTACT_US = "contact-us",
}
