/**
 * Export Service
 *
 * Generates export files for processed Lottie animations:
 * - Schema file (.expanse-lottie.ts)
 * - React component (.tsx)
 * - Theme configuration files
 * - Theme registry file
 */

import { Injectable, Logger } from '@nestjs/common';
import {
  LottieAnimation,
  LottieElement,
  LottieTheme,
  ExportResult,
  ExportedFile,
  ExportOptions,
} from '@/types';

@Injectable()
export class ExportService {
  private readonly logger = new Logger(ExportService.name);

  /**
   * Generate all export files for an animation
   */
  async generateExportFiles(
    animation: LottieAnimation,
    options: ExportOptions = {
      includeSchema: true,
      includeComponent: true,
      includeThemeConfigs: true,
      includeThemesRegistry: true,
      includeLottieJson: true,
    },
  ): Promise<ExportResult> {
    const files: ExportedFile[] = [];
    const errors: string[] = [];

    const animationName = animation.metadata?.animationName || animation.name;

    try {
      // Schema file
      if (options.includeSchema && animation.elements) {
        const schemaFile = this.generateSchemaFile(animationName, animation);
        files.push(schemaFile);
      }

      // React component
      if (options.includeComponent) {
        const componentFile = this.generateComponentFile(animationName);
        files.push(componentFile);
      }

      // Theme config files
      if (options.includeThemeConfigs && animation.themes) {
        const themeFiles = this.generateThemeConfigFiles(animationName, animation.themes);
        files.push(...themeFiles);
      }

      // Theme registry
      if (options.includeThemesRegistry && animation.themes) {
        const registryFile = this.generateThemesRegistryFile(animationName, animation.themes);
        files.push(registryFile);
      }

      // Lottie JSON
      if (options.includeLottieJson) {
        const jsonFile = this.generateLottieJsonFile(animationName, animation.json);
        files.push(jsonFile);
      }

      this.logger.log(`Generated ${files.length} export files for ${animationName}`);

      return {
        success: true,
        files,
      };
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      this.logger.error(`Export failed: ${errorMessage}`);
      errors.push(errorMessage);

      return {
        success: false,
        files,
        errors,
      };
    }
  }

  /**
   * Generate the schema file (.expanse-lottie.ts)
   */
  private generateSchemaFile(
    animationName: string,
    animation: LottieAnimation,
  ): ExportedFile {
    const elements = animation.elements || [];
    const metadata = animation.metadata;

    const elementsCode = elements
      .map((el) => this.formatElementCode(el))
      .join(',\n    ');

    const content = `/**
 * ${animationName} Lottie Schema
 * Generated by Lottie Studio
 */

import type { ExpanseLottie } from 'expanse.dynamicAssets';

export const ${animationName}Schema: ExpanseLottie = {
  name: '${animationName}',
  description: '${this.escapeString(metadata?.description || '')}',
  tags: [${(metadata?.tags || []).map((t) => `'${t}'`).join(', ')}],
  elements: {
    ${elementsCode}
  },
};

export default ${animationName}Schema;
`;

    return {
      filename: `${animationName}.expanse-lottie.ts`,
      path: `${animationName}/${animationName}.expanse-lottie.ts`,
      content,
      type: 'SCHEMA',
    };
  }

  /**
   * Generate the React component file (.tsx)
   */
  private generateComponentFile(animationName: string): ExportedFile {
    const content = `/**
 * ${animationName} Lottie Component
 * Generated by Lottie Studio
 */

import { createLottieComponent } from '@/theming/createLottieComponent';
import animationData from './${animationName}.json';
import { ${animationName}Schema } from './${animationName}.expanse-lottie';

export const ${animationName} = createLottieComponent({
  name: '${animationName}',
  animationData,
  schema: ${animationName}Schema,
});

export default ${animationName};
`;

    return {
      filename: `${animationName}.tsx`,
      path: `${animationName}/${animationName}.tsx`,
      content,
      type: 'COMPONENT',
    };
  }

  /**
   * Generate individual theme config files
   */
  private generateThemeConfigFiles(
    animationName: string,
    themes: LottieTheme[],
  ): ExportedFile[] {
    return themes.map((theme) => {
      const fileName = theme.themeId.replace(`default-`, '');
      const colorsCode = Object.entries(theme.colors)
        .map(([key, value]) => `    ${key}: '${value}'`)
        .join(',\n');

      const content = `/**
 * ${theme.name} Theme for ${animationName}
 * Generated by Lottie Studio
 */

import type { LottieThemeConfig } from '@/theming/types';

export const ${this.toCamelCase(fileName)}Theme: LottieThemeConfig = {
  themeId: '${theme.themeId}',
  name: '${theme.name}',
  baseColor: '${theme.baseColor}',
  mode: '${theme.mode}',
  colors: {
${colorsCode}
  },
  skippedElements: [${theme.skippedElements.map((s) => `'${s}'`).join(', ')}],
};

export default ${this.toCamelCase(fileName)}Theme;
`;

      const folder = `themes/default`;
      
      return {
        filename: `${fileName}.ts`,
        path: `${animationName}/${folder}/${fileName}.ts`,
        content,
        type: 'THEME_CONFIGS',
      };
    });
  }

  /**
   * Generate the themes registry file
   */
  private generateThemesRegistryFile(
    animationName: string,
    themes: LottieTheme[],
  ): ExportedFile {
    const imports = themes
      .map((theme) => {
        const fileName = theme.themeId.replace(`default-`, '');
        const varName = this.toCamelCase(fileName);
        return `import { ${varName}Theme } from './default/${fileName}';`;
      })
      .join('\n');

    const exports = themes
      .map((theme) => {
        const fileName = theme.themeId.replace(`default-`, '');
        return `  '${theme.themeId}': ${this.toCamelCase(fileName)}Theme`;
      })
      .join(',\n');

    const content = `/**
 * ${animationName} Theme Registry
 * Generated by Lottie Studio
 */

${imports}

export const ${animationName}Themes = {
${exports}
};

export default ${animationName}Themes;
`;

    return {
      filename: 'index.ts',
      path: `${animationName}/themes/index.ts`,
      content,
      type: 'THEMES_REGISTRY',
    };
  }

  /**
   * Generate the Lottie JSON file
   */
  private generateLottieJsonFile(
    animationName: string,
    json: Record<string, any>,
  ): ExportedFile {
    return {
      filename: `${animationName}.json`,
      path: `${animationName}/${animationName}.json`,
      content: JSON.stringify(json, null, 2),
      type: 'LOTTIE_JSON',
    };
  }

  /**
   * Format a single element for the schema code
   */
  private formatElementCode(element: LottieElement): string {
    const originalColor =
      typeof element.originalColor === 'string'
        ? `'${element.originalColor}'`
        : element.originalColor === null
          ? 'null'
          : JSON.stringify(element.originalColor);

    return `${element.name}: {
      name: '${element.name}',
      path: '${element.path}',
      description: '${this.escapeString(element.description)}',
      originalColor: ${originalColor},
      elementType: '${element.elementType || 'fill'}',
      roleFunction: '${element.roleFunction || 'supporting_object'}',
      visualLevel: '${element.visualLevel || 'secondary'}',
      semanticRole: '${element.semanticRole || 'illustrative_object'}',
      isThemeable: ${element.isThemeable},
      tags: [${(element.tags || []).map((t) => `'${t}'`).join(', ')}],
    }`;
  }

  /**
   * Convert string to camelCase
   */
  private toCamelCase(str: string): string {
    return str
      .split('-')
      .map((word, index) =>
        index === 0
          ? word.toLowerCase()
          : word.charAt(0).toUpperCase() + word.slice(1).toLowerCase(),
      )
      .join('');
  }

  /**
   * Escape string for use in generated code
   */
  private escapeString(str: string): string {
    return str.replace(/'/g, "\\'").replace(/\n/g, '\\n');
  }
}
