import type { LottieThemeConfig } from "../../../../theming/lottieColorMapping"

export const blueLightTheme: LottieThemeConfig = {
  themeId: "default-blue-light",
  name: "Blue Light",
  description: "Blue light mode theme for Homework animation",
  baseColor: "blue",
  mode: "light",
  colors: {
    PencilBodyFill: "#1976D2",
    PencilEraserFill: "#1565C0",
    PencilEraserBandDarkFill: "#0D47A1",
    PencilEraserBandLightFill: "#64B5F6",
    PencilTipWoodFill: "#FFF8E1",
    PencilTipLeadFill: "#424242",
    NotebookCoverFill: "#1565C0",
    NotebookSpineFill: "#0D47A1",
    NotebookPageBaseFill: "#FAFAFA",
    NotebookPageLeftFill: "#F5F5F5",
    NotebookPageWriteLayer1Fill: "#FAFAFA",
    NotebookPageWriteLayer2Fill: "#FAFAFA",
    NotebookPageWriteLayer3Fill: "#FAFAFA",
    NotebookWrittenLine1Fill: "#1976D2",
    NotebookWrittenLine2Fill: "#1976D2",
    NotebookWrittenLine3Fill: "#1976D2",
    NotebookWrittenLine4Fill: "#1976D2",
    NotebookWrittenLine5Fill: "#1976D2",
    NotebookWrittenLine6Fill: "#1976D2",
    NotebookWrittenLine7Fill: "#1976D2",
    NotebookWrittenLine8Fill: "#1976D2",
    NotebookWrittenLine9Fill: "#1976D2",
    NotebookWrittenLine10Fill: "#1976D2",
    NotebookWrittenLine11Fill: "#1976D2",
    NotebookWrittenLine12Fill: "#1976D2",
    NotebookWrittenLine13Fill: "#1976D2",
    NotebookWrittenLine14Fill: "#1976D2",
    NotebookWrittenLine15Fill: "#1976D2",
    NotebookWrittenLine16Fill: "#1976D2",
    NotebookWrittenLine17Fill: "#1976D2",
    NotebookWrittenLine18Fill: "#1976D2",
    NotebookPageRuledLine1Fill: "#BBDEFB",
    NotebookPageRuledLine2Fill: "#BBDEFB",
    NotebookPageRuledLine3Fill: "#BBDEFB",
    NotebookPageRuledLine4Fill: "#BBDEFB",
    NotebookPageRuledLine5Fill: "#BBDEFB",
    NotebookPageRuledLine6Fill: "#BBDEFB",
    NotebookPageRuledLine7Fill: "#BBDEFB",
    NotebookPageRuledLine8Fill: "#BBDEFB",
    SparkleLeftFill: "#FFFFFF",
    SparkleRightFill: "#FFFFFF",
  },
  skippedElements: [],
}

export default blueLightTheme
