import type { LottieThemeConfig } from "../../../../theming/lottieColorMapping"

export const blueDarkTheme: LottieThemeConfig = {
  themeId: "default-blue-dark",
  name: "Blue Dark",
  description: "Blue dark mode theme for Homework animation",
  baseColor: "blue",
  mode: "dark",
  colors: {
    PencilBodyFill: "#64B5F6",
    PencilEraserFill: "#90CAF9",
    PencilEraserBandDarkFill: "#1976D2",
    PencilEraserBandLightFill: "#E3F2FD",
    PencilTipWoodFill: "#FFF8E1",
    PencilTipLeadFill: "#757575",
    NotebookCoverFill: "#42A5F5",
    NotebookSpineFill: "#1565C0",
    NotebookPageBaseFill: "#2D2D2D",
    NotebookPageLeftFill: "#383838",
    NotebookPageWriteLayer1Fill: "#2D2D2D",
    NotebookPageWriteLayer2Fill: "#2D2D2D",
    NotebookPageWriteLayer3Fill: "#2D2D2D",
    NotebookWrittenLine1Fill: "#64B5F6",
    NotebookWrittenLine2Fill: "#64B5F6",
    NotebookWrittenLine3Fill: "#64B5F6",
    NotebookWrittenLine4Fill: "#64B5F6",
    NotebookWrittenLine5Fill: "#64B5F6",
    NotebookWrittenLine6Fill: "#64B5F6",
    NotebookWrittenLine7Fill: "#64B5F6",
    NotebookWrittenLine8Fill: "#64B5F6",
    NotebookWrittenLine9Fill: "#64B5F6",
    NotebookWrittenLine10Fill: "#64B5F6",
    NotebookWrittenLine11Fill: "#64B5F6",
    NotebookWrittenLine12Fill: "#64B5F6",
    NotebookWrittenLine13Fill: "#64B5F6",
    NotebookWrittenLine14Fill: "#64B5F6",
    NotebookWrittenLine15Fill: "#64B5F6",
    NotebookWrittenLine16Fill: "#64B5F6",
    NotebookWrittenLine17Fill: "#64B5F6",
    NotebookWrittenLine18Fill: "#64B5F6",
    NotebookPageRuledLine1Fill: "#0D47A1",
    NotebookPageRuledLine2Fill: "#0D47A1",
    NotebookPageRuledLine3Fill: "#0D47A1",
    NotebookPageRuledLine4Fill: "#0D47A1",
    NotebookPageRuledLine5Fill: "#0D47A1",
    NotebookPageRuledLine6Fill: "#0D47A1",
    NotebookPageRuledLine7Fill: "#0D47A1",
    NotebookPageRuledLine8Fill: "#0D47A1",
    SparkleLeftFill: "#FFFFFF",
    SparkleRightFill: "#FFFFFF",
  },
  skippedElements: [],
}

export default blueDarkTheme
