import type { LottieThemeConfig } from "../../../../theming/lottieColorMapping"

export const purpleLightTheme: LottieThemeConfig = {
  themeId: "default-purple-light",
  name: "Purple Light",
  description: "Purple light mode theme for Homework animation",
  baseColor: "purple",
  mode: "light",
  colors: {
    PencilBodyFill: "#9C27B0",
    PencilEraserFill: "#7B1FA2",
    PencilEraserBandDarkFill: "#4A148C",
    PencilEraserBandLightFill: "#CE93D8",
    PencilTipWoodFill: "#FFF8E1",
    PencilTipLeadFill: "#424242",
    NotebookCoverFill: "#7B1FA2",
    NotebookSpineFill: "#4A148C",
    NotebookPageBaseFill: "#FAFAFA",
    NotebookPageLeftFill: "#F5F5F5",
    NotebookPageWriteLayer1Fill: "#FAFAFA",
    NotebookPageWriteLayer2Fill: "#FAFAFA",
    NotebookPageWriteLayer3Fill: "#FAFAFA",
    NotebookWrittenLine1Fill: "#9C27B0",
    NotebookWrittenLine2Fill: "#9C27B0",
    NotebookWrittenLine3Fill: "#9C27B0",
    NotebookWrittenLine4Fill: "#9C27B0",
    NotebookWrittenLine5Fill: "#9C27B0",
    NotebookWrittenLine6Fill: "#9C27B0",
    NotebookWrittenLine7Fill: "#9C27B0",
    NotebookWrittenLine8Fill: "#9C27B0",
    NotebookWrittenLine9Fill: "#9C27B0",
    NotebookWrittenLine10Fill: "#9C27B0",
    NotebookWrittenLine11Fill: "#9C27B0",
    NotebookWrittenLine12Fill: "#9C27B0",
    NotebookWrittenLine13Fill: "#9C27B0",
    NotebookWrittenLine14Fill: "#9C27B0",
    NotebookWrittenLine15Fill: "#9C27B0",
    NotebookWrittenLine16Fill: "#9C27B0",
    NotebookWrittenLine17Fill: "#9C27B0",
    NotebookWrittenLine18Fill: "#9C27B0",
    NotebookPageRuledLine1Fill: "#E1BEE7",
    NotebookPageRuledLine2Fill: "#E1BEE7",
    NotebookPageRuledLine3Fill: "#E1BEE7",
    NotebookPageRuledLine4Fill: "#E1BEE7",
    NotebookPageRuledLine5Fill: "#E1BEE7",
    NotebookPageRuledLine6Fill: "#E1BEE7",
    NotebookPageRuledLine7Fill: "#E1BEE7",
    NotebookPageRuledLine8Fill: "#E1BEE7",
    SparkleLeftFill: "#FFFFFF",
    SparkleRightFill: "#FFFFFF",
  },
  skippedElements: [],
}

export default purpleLightTheme
