import type { LottieThemeConfig } from "../../../../theming/lottieColorMapping"

export const purpleDarkTheme: LottieThemeConfig = {
  themeId: "default-purple-dark",
  name: "Purple Dark",
  description: "Purple dark mode theme for Homework animation",
  baseColor: "purple",
  mode: "dark",
  colors: {
    PencilBodyFill: "#CE93D8",
    PencilEraserFill: "#E1BEE7",
    PencilEraserBandDarkFill: "#9C27B0",
    PencilEraserBandLightFill: "#F3E5F5",
    PencilTipWoodFill: "#FFF8E1",
    PencilTipLeadFill: "#757575",
    NotebookCoverFill: "#AB47BC",
    NotebookSpineFill: "#7B1FA2",
    NotebookPageBaseFill: "#2D2D2D",
    NotebookPageLeftFill: "#383838",
    NotebookPageWriteLayer1Fill: "#2D2D2D",
    NotebookPageWriteLayer2Fill: "#2D2D2D",
    NotebookPageWriteLayer3Fill: "#2D2D2D",
    NotebookWrittenLine1Fill: "#CE93D8",
    NotebookWrittenLine2Fill: "#CE93D8",
    NotebookWrittenLine3Fill: "#CE93D8",
    NotebookWrittenLine4Fill: "#CE93D8",
    NotebookWrittenLine5Fill: "#CE93D8",
    NotebookWrittenLine6Fill: "#CE93D8",
    NotebookWrittenLine7Fill: "#CE93D8",
    NotebookWrittenLine8Fill: "#CE93D8",
    NotebookWrittenLine9Fill: "#CE93D8",
    NotebookWrittenLine10Fill: "#CE93D8",
    NotebookWrittenLine11Fill: "#CE93D8",
    NotebookWrittenLine12Fill: "#CE93D8",
    NotebookWrittenLine13Fill: "#CE93D8",
    NotebookWrittenLine14Fill: "#CE93D8",
    NotebookWrittenLine15Fill: "#CE93D8",
    NotebookWrittenLine16Fill: "#CE93D8",
    NotebookWrittenLine17Fill: "#CE93D8",
    NotebookWrittenLine18Fill: "#CE93D8",
    NotebookPageRuledLine1Fill: "#4A148C",
    NotebookPageRuledLine2Fill: "#4A148C",
    NotebookPageRuledLine3Fill: "#4A148C",
    NotebookPageRuledLine4Fill: "#4A148C",
    NotebookPageRuledLine5Fill: "#4A148C",
    NotebookPageRuledLine6Fill: "#4A148C",
    NotebookPageRuledLine7Fill: "#4A148C",
    NotebookPageRuledLine8Fill: "#4A148C",
    SparkleLeftFill: "#FFFFFF",
    SparkleRightFill: "#FFFFFF",
  },
  skippedElements: [],
}

export default purpleDarkTheme
