import type { LottieThemeConfig } from "../../../../theming/lottieColorMapping"

export const blueDarkTheme: LottieThemeConfig = {
  themeId: "minimal-blue-dark",
  name: "Blue Dark (Minimal)",
  description:
    "Blue dark mode theme for Homework animation - minimal variant with only pencil and notebook cover themed",
  baseColor: "blue",
  mode: "dark",
  colors: {
    PencilBodyFill: "#64B5F6",
    PencilEraserFill: "#90CAF9",
    PencilEraserBandDarkFill: "#1976D2",
    PencilEraserBandLightFill: "#E3F2FD",
    NotebookCoverFill: "#42A5F5",
    NotebookSpineFill: "#1565C0",
  },
  skippedElements: [
    "PencilTipWoodFill",
    "PencilTipLeadFill",
    "NotebookPageBaseFill",
    "NotebookPageLeftFill",
    "NotebookPageWriteLayer1Fill",
    "NotebookPageWriteLayer2Fill",
    "NotebookPageWriteLayer3Fill",
    "NotebookWrittenLine1Fill",
    "NotebookWrittenLine2Fill",
    "NotebookWrittenLine3Fill",
    "NotebookWrittenLine4Fill",
    "NotebookWrittenLine5Fill",
    "NotebookWrittenLine6Fill",
    "NotebookWrittenLine7Fill",
    "NotebookWrittenLine8Fill",
    "NotebookWrittenLine9Fill",
    "NotebookWrittenLine10Fill",
    "NotebookWrittenLine11Fill",
    "NotebookWrittenLine12Fill",
    "NotebookWrittenLine13Fill",
    "NotebookWrittenLine14Fill",
    "NotebookWrittenLine15Fill",
    "NotebookWrittenLine16Fill",
    "NotebookWrittenLine17Fill",
    "NotebookWrittenLine18Fill",
    "NotebookPageRuledLine1Fill",
    "NotebookPageRuledLine2Fill",
    "NotebookPageRuledLine3Fill",
    "NotebookPageRuledLine4Fill",
    "NotebookPageRuledLine5Fill",
    "NotebookPageRuledLine6Fill",
    "NotebookPageRuledLine7Fill",
    "NotebookPageRuledLine8Fill",
    "SparkleLeftFill",
    "SparkleRightFill",
  ],
}

export default blueDarkTheme
