import type { LottieThemeConfig } from "../../../../theming/lottieColorMapping"

export const purpleLightTheme: LottieThemeConfig = {
  themeId: "minimal-purple-light",
  name: "Purple Light (Minimal)",
  description:
    "Purple light mode theme for Homework animation - minimal variant with only pencil and notebook cover themed",
  baseColor: "purple",
  mode: "light",
  colors: {
    PencilBodyFill: "#9C27B0",
    PencilEraserFill: "#7B1FA2",
    PencilEraserBandDarkFill: "#4A148C",
    PencilEraserBandLightFill: "#CE93D8",
    NotebookCoverFill: "#7B1FA2",
    NotebookSpineFill: "#4A148C",
  },
  skippedElements: [
    "PencilTipWoodFill",
    "PencilTipLeadFill",
    "NotebookPageBaseFill",
    "NotebookPageLeftFill",
    "NotebookPageWriteLayer1Fill",
    "NotebookPageWriteLayer2Fill",
    "NotebookPageWriteLayer3Fill",
    "NotebookWrittenLine1Fill",
    "NotebookWrittenLine2Fill",
    "NotebookWrittenLine3Fill",
    "NotebookWrittenLine4Fill",
    "NotebookWrittenLine5Fill",
    "NotebookWrittenLine6Fill",
    "NotebookWrittenLine7Fill",
    "NotebookWrittenLine8Fill",
    "NotebookWrittenLine9Fill",
    "NotebookWrittenLine10Fill",
    "NotebookWrittenLine11Fill",
    "NotebookWrittenLine12Fill",
    "NotebookWrittenLine13Fill",
    "NotebookWrittenLine14Fill",
    "NotebookWrittenLine15Fill",
    "NotebookWrittenLine16Fill",
    "NotebookWrittenLine17Fill",
    "NotebookWrittenLine18Fill",
    "NotebookPageRuledLine1Fill",
    "NotebookPageRuledLine2Fill",
    "NotebookPageRuledLine3Fill",
    "NotebookPageRuledLine4Fill",
    "NotebookPageRuledLine5Fill",
    "NotebookPageRuledLine6Fill",
    "NotebookPageRuledLine7Fill",
    "NotebookPageRuledLine8Fill",
    "SparkleLeftFill",
    "SparkleRightFill",
  ],
}

export default purpleLightTheme
