/**
 * Local stub for `expanse.ui/points`.
 *
 * The `expanse.ui` package lives in another repo and is not yet ported to
 * this workspace (see TODO in src/index.ts). This stub provides just enough
 * surface area for the TaskCard family + its Storybook stories to compile
 * and render via the Vite alias configured in `.storybook/main.ts`.
 *
 * Once the real `@expanse/points` (or equivalent) package is migrated,
 * delete this stub and the alias.
 */

export enum TICKET_POINT_OPTIONS {
  ONE_POINT = 1,
  TWO_POINTS = 2,
  THREE_POINTS = 3,
  FIVE_POINTS = 5,
  NINE_POINTS = 9,
  EIGHTEEN_POINTS = 18,
  EIGHTY_ONE_POINTS = 81,
}

export enum TICKET_POINT_VALUES {
  ONE_POINT = 1,
  TWO_POINTS = 4,
  THREE_POINTS = 8,
  FIVE_POINTS = 16,
  NINE_POINTS = 45,
  EIGHTEEN_POINTS = 95,
  EIGHTY_ONE_POINTS = Number.POSITIVE_INFINITY,
}

export const TICKET_POINT_OPTIONS_LIST: TICKET_POINT_OPTIONS[] = [
  TICKET_POINT_OPTIONS.ONE_POINT,
  TICKET_POINT_OPTIONS.TWO_POINTS,
  TICKET_POINT_OPTIONS.THREE_POINTS,
  TICKET_POINT_OPTIONS.FIVE_POINTS,
  TICKET_POINT_OPTIONS.NINE_POINTS,
  TICKET_POINT_OPTIONS.EIGHTEEN_POINTS,
  TICKET_POINT_OPTIONS.EIGHTY_ONE_POINTS,
]

export const TICKET_POINT_OPTIONS_MAP: Record<TICKET_POINT_OPTIONS, number> = {
  [TICKET_POINT_OPTIONS.ONE_POINT]: TICKET_POINT_VALUES.ONE_POINT,
  [TICKET_POINT_OPTIONS.TWO_POINTS]: TICKET_POINT_VALUES.TWO_POINTS,
  [TICKET_POINT_OPTIONS.THREE_POINTS]: TICKET_POINT_VALUES.THREE_POINTS,
  [TICKET_POINT_OPTIONS.FIVE_POINTS]: TICKET_POINT_VALUES.FIVE_POINTS,
  [TICKET_POINT_OPTIONS.NINE_POINTS]: TICKET_POINT_VALUES.NINE_POINTS,
  [TICKET_POINT_OPTIONS.EIGHTEEN_POINTS]: TICKET_POINT_VALUES.EIGHTEEN_POINTS,
  [TICKET_POINT_OPTIONS.EIGHTY_ONE_POINTS]:
    TICKET_POINT_VALUES.EIGHTY_ONE_POINTS,
}

export function mapTicketPointToValue(p: TICKET_POINT_OPTIONS): number {
  return TICKET_POINT_OPTIONS_MAP[p] ?? 0
}

const XP_LABELS: Record<TICKET_POINT_OPTIONS, string> = {
  [TICKET_POINT_OPTIONS.ONE_POINT]: "1 XP",
  [TICKET_POINT_OPTIONS.TWO_POINTS]: "4 XP",
  [TICKET_POINT_OPTIONS.THREE_POINTS]: "8 XP",
  [TICKET_POINT_OPTIONS.FIVE_POINTS]: "16 XP",
  [TICKET_POINT_OPTIONS.NINE_POINTS]: "45 XP",
  [TICKET_POINT_OPTIONS.EIGHTEEN_POINTS]: "95 XP",
  [TICKET_POINT_OPTIONS.EIGHTY_ONE_POINTS]: "∞ XP",
}

const DIFFICULTY_LABELS: Record<TICKET_POINT_OPTIONS, string> = {
  [TICKET_POINT_OPTIONS.ONE_POINT]: "Trivial",
  [TICKET_POINT_OPTIONS.TWO_POINTS]: "Easy",
  [TICKET_POINT_OPTIONS.THREE_POINTS]: "Moderate",
  [TICKET_POINT_OPTIONS.FIVE_POINTS]: "Challenging",
  [TICKET_POINT_OPTIONS.NINE_POINTS]: "Hard",
  [TICKET_POINT_OPTIONS.EIGHTEEN_POINTS]: "Very Hard",
  [TICKET_POINT_OPTIONS.EIGHTY_ONE_POINTS]: "Epic",
}

export function getPointXPLabel(p: TICKET_POINT_OPTIONS): string {
  return XP_LABELS[p] ?? ""
}

export function getPointDifficultyLabel(p: TICKET_POINT_OPTIONS): string {
  return DIFFICULTY_LABELS[p] ?? ""
}
