/**
 * Learning modality types for different educational approaches.
 * Used to represent content in ways that match different learning preferences and cognitive styles.
 */
export enum LearningModality {
    VERBAL = "verbal", // Traditional text explanations
    VISUAL = "visual", // Diagrams, charts, images
    NONVERBAL = "nonverbal", // Body language, gestures, demonstrations
    STORYTELLING = "storytelling", // Narrative-based explanations
    PROBLEM_SOLVING = "problem_solving", // Step-by-step problem approach
    ASSOCIATIONS = "associations", // Connecting to known concepts
    METAPHORS = "metaphors", // Analogies and comparisons
    KINESTHETIC = "kinesthetic", // Hands-on, movement-based
    AUDITORY = "auditory", // Sound, rhythm, music
    LOGICAL = "logical", // Structured, sequential reasoning
    SOCIAL = "social", // Group discussion, peer learning
    EXPERIENTIAL = "experiential", // Real-world examples, case studies
}

/**
 * Comprehensive list of visualization types that can be used to enhance learning.
 * These types will be suggested by the analysis AI and generated by a separate visualization generation system.
 */
export enum VisualizationType {
    // Basic types
    ASCII_ART = 'ascii_art',
    SVG_DIAGRAM = 'svg_diagram',
    ANIMATED_SVG = 'animated_svg',
    HTML_INTERACTIVE = 'html_interactive', // JS, CSS, WEB. Will include interaction. Will be built into full HTML Page based on prompt
    HTML_STATIC = 'html_static',           // JS, CSS, WEB. Will be primarily static and non interactive for visual. Will be built into full HTML Page based on prompt
    MERMAID_DIAGRAM = 'mermaid_diagram',      // Mermaid.js diagrams (flowcharts, sequences, etc.)
    
    // Process & Flow
    FLOW_CHART = 'flow_chart',
    DECISION_TREE = 'decision_tree',
    STEP_SEQUENCE = 'step_sequence',
    CYCLIC_DIAGRAM = 'cyclic_diagram',
    MERMAID_FLOWCHART = 'mermaid_flowchart',  // Mermaid-specific flowchart
    MERMAID_SEQUENCE = 'mermaid_sequence',    // Mermaid sequence diagram
    SWIPER_PRESENTATION = 'swiper_presentation', // Swiper.js step-by-step slides
    
    // Time-based
    TIMELINE = 'timeline',
    TIMELINE_COMPARATIVE = 'timeline_comparative',
    
    // Relationship & Structure
    MIND_MAP = 'mind_map',
    CONCEPT_MAP = 'concept_map',
    NETWORK_GRAPH = 'network_graph',
    TREE_STRUCTURE = 'tree_structure',
    MERMAID_MINDMAP = 'mermaid_mindmap',      // Mermaid mindmap
    MERMAID_GITGRAPH = 'mermaid_gitgraph',    // Mermaid git graph (for version control concepts)
    MERMAID_ERD = 'mermaid_erd',              // Mermaid entity relationship diagram
    MERMAID_CLASS = 'mermaid_class',          // Mermaid class diagram
    
    // Data Visualization
    CHART_BAR = 'chart_bar',
    CHART_LINE = 'chart_line',
    CHART_PIE = 'chart_pie',
    CHART_AREA = 'chart_area',
    PROGRESS_BAR = 'progress_bar',
    METER = 'meter',
    MERMAID_PIE = 'mermaid_pie',              // Mermaid pie chart
    MERMAID_GANTT = 'mermaid_gantt',          // Mermaid Gantt chart (project timelines)
    
    // Comparison & Organization
    TABLE = 'table',
    COMPARISON_MATRIX = 'comparison_matrix',
    BEFORE_AFTER_SLIDER = 'before_after_slider',
    
    // Spatial & Visual
    INFOGRAPHIC = 'infographic',
    SPATIAL_DIAGRAM = 'spatial_diagram',
    LAYERED_REVEAL = 'layered_reveal',
    INTERACTIVE_DIAGRAM = 'interactive_diagram',
    MERMAID_STATE = 'mermaid_state',          // Mermaid state diagram (FSM)
    MERMAID_JOURNEY = 'mermaid_journey',      // Mermaid user journey map
    
    // Effects & Enhancements
    PARTICLE_SYSTEM = 'particle_system',
    TRANSFORMATION = 'transformation',
    TEXT_ANIMATION = 'text_animation',
    
    // Interactive Controls
    SLIDER_CONTROL = 'slider_control',
    ACCORDION = 'accordion',
    TABS = 'tabs',
    CAROUSEL = 'carousel',
    TOGGLE = 'toggle',
    
    // External Media
    IMAGE = 'image',
    VIDEO = 'video',
    THREE_D_MODEL = '3d_model',
    AUDIO = 'audio',
    
    // Text Enhancements
    ANNOTATED_TEXT = 'annotated_text',        // Text with inline explanations
    HIGHLIGHTED_TEXT = 'highlighted_text',    // Color-coded emphasis
    MARGIN_NOTES = 'margin_notes',           // Side notes and callouts
    TOOLTIP_DEFINITIONS = 'tooltip_definitions', // Hover for definitions
    
    // Novel/Creative Types
    COMIC_STRIP = 'comic_strip',             // Sequential art format
    EMOJI_DIAGRAM = 'emoji_diagram',         // Visual using emojis
    ASCII_ANIMATION = 'ascii_animation',     // Animated ASCII art
    CODE_PLAYGROUND = 'code_playground',     // Interactive code editor
    QUIZ_EMBEDDED = 'quiz_embedded',         // Inline quiz/questions
    FLASHCARD = 'flashcard',                 // Flip cards
    MEMORY_GAME = 'memory_game',             // Match pairs
    
    // AI/Custom
    AI_GENERATED = 'ai_generated',           // Novel AI-created visualization
    CUSTOM = 'custom',                       // Fully custom implementation
    HYBRID = 'hybrid'                        // Combination of multiple types
}