/**
 * VersusClash - ExpanseLottie Schema
 * Generated by AI Naming Tool
 */

import type { ExpanseLottie } from "../../types"

export const VersusClashSchema: ExpanseLottie = {
  "animationName": "VersusClash",
  "alternativeNames": [
    "CompetitionIntro",
    "VsScreen",
    "TeamBattle",
    "PlayerVersusPlayer",
    "ChallengeAccepted"
  ],
  "description": "An energetic animation revealing 'VS' text. Two abstract shapes fly in from opposite sides and collide, triggering a burst of radial lines and expanding circles. The central 'VS' letters then scale into view. Ideal for competition, gaming, or comparison screens. The colors of the text, burst effects, and colliding shapes are easily themeable.",
  "tags": [
    "vs",
    "versus",
    "competition",
    "battle",
    "challenge",
    "game",
    "intro",
    "reveal",
    "clash",
    "impact",
    "explosion",
    "text-animation",
    "logo-reveal"
  ],
  "purpose": {
    "primary": "To introduce a competitive event, comparison, or challenge between two opposing sides.",
    "categories": {
      "UI & UX": [
        "Game start screen",
        "Player vs. Player matchup screen",
        "Leaderboard challenge notification"
      ],
      "Marketing & Branding": [
        "Promotional video intro for a competition",
        "Social media post announcing a debate or battle",
        "Product comparison graphic"
      ],
      "Presentations": [
        "Transition slide between two opposing ideas",
        "A/B testing results slide"
      ]
    },
    "contexts": [
      "gamification",
      "web-content",
      "education"
    ],
    "recommendations": [
      "Use as a full-screen transition or modal overlay to build anticipation before a competitive task.",
      "Ideal for loading screens before a match or challenge begins."
    ]
  },
  "contextSpecificMetadata": {
    "gamification": {
      "context": "gamification",
      "primary": "Introduce a head-to-head challenge or player-versus-player (PvP) match.",
      "useCaseExamples": [
        "Displaying player avatars on either side before a match starts.",
        "Announcing a new tournament or competitive league.",
        "Transitioning to a boss battle screen."
      ],
      "recommendations": [
        "Customize the colliding shapes with team colors or logos."
      ],
      "tags": [
        "pvp",
        "matchmaking",
        "challenge",
        "duel",
        "competition",
        "game-start"
      ]
    },
    "education": {
      "context": "education",
      "primary": "Visually represent a debate, comparison, or opposing concepts.",
      "useCaseExamples": [
        "Introducing a debate topic in a history or civics lesson.",
        "Comparing two different scientific theories in a quiz.",
        "A/B testing a hypothesis in a statistics module."
      ],
      "tags": [
        "debate",
        "comparison",
        "pros-and-cons",
        "quiz",
        "challenge"
      ]
    },
    "work": {
      "context": "work",
      "primary": "Illustrate a comparison between two strategies, products, or teams.",
      "useCaseExamples": [
        "Kicking off a sales competition between two teams.",
        "Presenting a competitor analysis slide.",
        "Visualizing the results of an A/B test in a marketing report."
      ],
      "tags": [
        "competition",
        "comparison",
        "a-b-test",
        "competitor-analysis",
        "challenge"
      ]
    },
    "life": {
      "context": "life",
      "primary": "Represent a friendly competition or a choice between two options.",
      "useCaseExamples": [
        "Creating a poll on social media (e.g., 'Coffee vs. Tea').",
        "Announcing a friendly sports match between friends.",
        "Deciding between two vacation spots in a fun way."
      ],
      "tags": [
        "choice",
        "decision",
        "poll",
        "friendly-competition",
        "matchup"
      ]
    },
    "web-content": {
      "context": "web-content",
      "primary": "Create an engaging intro for content comparing two things.",
      "useCaseExamples": [
        "Video intro for a 'Product A vs. Product B' review.",
        "Header animation for a blog post comparing two technologies.",
        "Loading animation for an interactive comparison tool on a website."
      ],
      "tags": [
        "intro",
        "versus",
        "comparison-chart",
        "review",
        "face-off"
      ]
    }
  },
  "recommendations": {
    "recommendedColorPalettes": [
      "Esports Dynamic (Electric Blue & Magenta)",
      "Corporate Challenge (Navy & Teal)",
      "Monochromatic Impact (Shades of Gray & White)",
      "Retro Arcade (Orange & Purple)",
      "Clean & Modern (Mint & Charcoal)"
    ],
    "elementGroups": {
      "logicalGrouped": {
        "vs-text": {
          "elements": [
            "VS Outlines.V.Fill 1",
            "VS Outlines.S.Fill 1"
          ],
          "description": "The central 'V' and 'S' letters that form the main subject."
        },
        "colliding-shapes": {
          "elements": [
            "Outlines.Group 1.Fill 1",
            "Outlines 2.Group 1.Fill 1"
          ],
          "description": "The two abstract shapes that fly in from the sides to create the initial impact."
        },
        "impact-burst": {
          "elements": [
            "Shape 10.Shape 01.Stroke 1"
          ],
          "description": "The radial lines that burst outward from the center upon impact."
        },
        "impact-rings": {
          "elements": [
            "Shape 01.Shape 01.Fill 1",
            "Shape 02.Shape 01.Fill 1",
            "Shape 03.Shape 01.Fill 1",
            "Shape 04.Shape 01.Fill 1"
          ],
          "description": "The series of expanding circular rings that emanate from the center."
        }
      },
      "sharedColor": {
        "primary-purple-elements": {
          "elements": [
            "VS Outlines.V.Fill 1",
            "VS Outlines.S.Fill 1",
            "Shape 01.Shape 01.Fill 1"
          ],
          "description": "The main text and the largest impact ring, sharing the primary theme color.",
          "colorRelationship": "identical"
        },
        "burst-elements": {
          "elements": [
            "Shape 10.Shape 01.Stroke 1",
            "Shape 03.Shape 01.Fill 1"
          ],
          "description": "The radial burst and one of the smaller rings, which use related shades of purple.",
          "colorRelationship": "shades"
        },
        "accent-white-rings": {
          "elements": [
            "Shape 02.Shape 01.Fill 1",
            "Shape 04.Shape 01.Fill 1"
          ],
          "description": "The two expanding rings that are white, providing a bright accent.",
          "colorRelationship": "identical"
        },
        "clash-shapes": {
          "elements": [
            "Outlines.Group 1.Fill 1",
            "Outlines 2.Group 1.Fill 1"
          ],
          "description": "The two opposing shapes that fly in, typically colored identically to represent teams or concepts.",
          "colorRelationship": "identical"
        }
      },
      "themingPriority": {
        "primary-elements": {
          "elements": [
            "VS Outlines.V.Fill 1",
            "VS Outlines.S.Fill 1"
          ],
          "description": "The 'VS' text is the main focal point and should be the highest priority for theming.",
          "priority": "high"
        },
        "impact-colors": {
          "elements": [
            "Shape 01.Shape 01.Fill 1",
            "Shape 10.Shape 01.Stroke 1",
            "Shape 03.Shape 01.Fill 1"
          ],
          "description": "The colored burst elements are key to the animation's energy and are a medium theming priority.",
          "priority": "medium"
        },
        "colliding-shapes-color": {
          "elements": [
            "Outlines.Group 1.Fill 1",
            "Outlines 2.Group 1.Fill 1"
          ],
          "description": "The colliding shapes can be themed, but could also be kept neutral (black/gray) to focus on the reveal.",
          "priority": "medium"
        },
        "accent-rings": {
          "elements": [
            "Shape 02.Shape 01.Fill 1",
            "Shape 04.Shape 01.Fill 1"
          ],
          "description": "The white accent rings have the lowest theming priority as they work well as neutral highlights.",
          "priority": "low"
        }
      },
      "visualHierarchy": {
        "focal-text": {
          "elements": [
            "VS Outlines.V.Fill 1",
            "VS Outlines.S.Fill 1"
          ],
          "description": "The 'VS' text is the primary subject of the animation, revealed at the climax.",
          "hierarchy": "primary"
        },
        "action-effects": {
          "elements": [
            "Shape 10.Shape 01.Stroke 1",
            "Shape 01.Shape 01.Fill 1",
            "Shape 02.Shape 01.Fill 1",
            "Shape 03.Shape 01.Fill 1",
            "Shape 04.Shape 01.Fill 1"
          ],
          "description": "The burst and ring effects are secondary elements that create action and draw attention to the center.",
          "hierarchy": "secondary"
        },
        "intro-elements": {
          "elements": [
            "Outlines.Group 1.Fill 1",
            "Outlines 2.Group 1.Fill 1"
          ],
          "description": "The colliding shapes serve as introductory elements that set up the main action.",
          "hierarchy": "secondary"
        }
      }
    },
    "optionalAiContext": {
      "mood": "Energetic, competitive, impactful, exciting",
      "style": "Modern, graphic, bold, clean",
      "theme": "Competition, challenge, comparison, battle, confrontation"
    },
    "optionalAiStylePrompts": {
      "cinematic": "Generate a cinematic, high-impact 'versus' screen with epic lighting, particle effects, and metallic textures.",
      "retro-8bit": "Create a pixel art, 8-bit retro arcade style 'VS' animation with blocky text and chiptune-inspired visual effects.",
      "minimalist": "Design a clean, minimalist version with simple line art, smooth transitions, and a professional, corporate color palette."
    },
    "optionalAiVariantPrompts": {
      "sports-theme": "Adapt the animation for a sports matchup, replacing the abstract shapes with a football and a basketball, and adding stadium light effects.",
      "elemental-battle": "Create a variant with an elemental theme, where one side is fire (reds/oranges) and the other is ice (blues/whites), with corresponding particle effects.",
      "custom-text": "Replace the 'VS' text with custom placeholders for two competitor names or team logos, ensuring they animate in with similar impact."
    }
  },
  "elements": {
    "TextVFill": {
      "name": "TextVFill",
      "alternativeNames": [
        "VLetterFill"
      ],
      "description": "The fill color for the 'V' letter in the central 'VS' text reveal.",
      "path": "layers[0].shapes[0].it[1].c.k",
      "originalColor": "#a662d0ff",
      "elementType": "fill",
      "roleFunction": "text",
      "visualLevel": "primary",
      "semanticRole": "textual_element",
      "isThemeable": true,
      "isSkinTone": false,
      "isClothing": false,
      "isEffect": false,
      "isBackground": false,
      "elementGroups": [
        "text",
        "vs-logo",
        "primary-accent"
      ],
      "tags": [
        "logo",
        "typography",
        "reveal"
      ]
    },
    "TextSFill": {
      "name": "TextSFill",
      "alternativeNames": [
        "SLetterFill"
      ],
      "description": "The fill color for the 'S' letter in the central 'VS' text reveal.",
      "path": "layers[0].shapes[1].it[1].c.k",
      "originalColor": "#a662d0ff",
      "elementType": "fill",
      "roleFunction": "text",
      "visualLevel": "primary",
      "semanticRole": "textual_element",
      "isThemeable": true,
      "isSkinTone": false,
      "isClothing": false,
      "isEffect": false,
      "isBackground": false,
      "elementGroups": [
        "text",
        "vs-logo",
        "primary-accent"
      ],
      "tags": [
        "logo",
        "typography",
        "reveal"
      ]
    },
    "ClashEffectBurstLineStroke": {
      "name": "ClashEffectBurstLineStroke",
      "alternativeNames": [
        "RadialBurstStroke",
        "ImpactLines"
      ],
      "description": "The stroke color for the radial lines that burst outwards from the central impact point.",
      "path": "layers[1].shapes[0].it[0].it[2].c.k",
      "originalColor": "#a750dcff",
      "elementType": "stroke",
      "roleFunction": "particle",
      "visualLevel": "secondary",
      "semanticRole": "effect",
      "isThemeable": true,
      "isSkinTone": false,
      "isClothing": false,
      "isEffect": true,
      "isBackground": false,
      "elementGroups": [
        "clash-effect",
        "burst-lines",
        "secondary-accent"
      ],
      "tags": [
        "radial-burst",
        "impact",
        "effect"
      ]
    },
    "ClashShapeRightFill": {
      "name": "ClashShapeRightFill",
      "alternativeNames": [
        "RightBlobFill"
      ],
      "description": "The fill color for the abstract shape that flies in from the right side. It is black by default, possibly for a cutout effect.",
      "path": "layers[2].shapes[0].it[4].c.k",
      "originalColor": "#000000ff",
      "elementType": "fill",
      "roleFunction": "primary_subject",
      "visualLevel": "primary",
      "semanticRole": "illustrative_object",
      "isThemeable": true,
      "isSkinTone": false,
      "isClothing": false,
      "isEffect": false,
      "isBackground": false,
      "elementGroups": [
        "colliding-shapes",
        "right-shape",
        "primary-subject"
      ],
      "tags": [
        "abstract-shape",
        "motion"
      ]
    },
    "ClashShapeLeftFill": {
      "name": "ClashShapeLeftFill",
      "alternativeNames": [
        "LeftBlobFill"
      ],
      "description": "The main fill color for the abstract shape that flies in from the left side.",
      "path": "layers[3].shapes[1].it[0].c.k",
      "originalColor": "#621890ff",
      "elementType": "fill",
      "roleFunction": "primary_subject",
      "visualLevel": "primary",
      "semanticRole": "illustrative_object",
      "isThemeable": true,
      "isSkinTone": false,
      "isClothing": false,
      "isEffect": false,
      "isBackground": false,
      "elementGroups": [
        "colliding-shapes",
        "left-shape",
        "primary-subject"
      ],
      "tags": [
        "abstract-shape",
        "motion",
        "primary-color"
      ]
    },
    "ClashEffectRingCenterFill": {
      "name": "ClashEffectRingCenterFill",
      "alternativeNames": [
        "InnermostRingFill"
      ],
      "description": "The fill color for the centermost expanding ring that appears after the shapes collide.",
      "path": "layers[4].shapes[0].it[1].c.k",
      "originalColor": "#ffffffff",
      "elementType": "fill",
      "roleFunction": "highlight",
      "visualLevel": "secondary",
      "semanticRole": "effect",
      "isThemeable": true,
      "isSkinTone": false,
      "isClothing": false,
      "isEffect": true,
      "isBackground": false,
      "elementGroups": [
        "clash-effect",
        "expanding-rings"
      ],
      "tags": [
        "shockwave",
        "impact",
        "white"
      ]
    },
    "ClashEffectRingInnerFill": {
      "name": "ClashEffectRingInnerFill",
      "alternativeNames": [
        "LightPurpleRingFill"
      ],
      "description": "The fill color for the inner, light purple expanding ring that appears after the shapes collide.",
      "path": "layers[5].shapes[0].it[1].c.k",
      "originalColor": "#d79bfdff",
      "elementType": "fill",
      "roleFunction": "highlight",
      "visualLevel": "secondary",
      "semanticRole": "effect",
      "isThemeable": true,
      "isSkinTone": false,
      "isClothing": false,
      "isEffect": true,
      "isBackground": false,
      "elementGroups": [
        "clash-effect",
        "expanding-rings",
        "secondary-accent"
      ],
      "tags": [
        "shockwave",
        "impact"
      ]
    },
    "ClashEffectRingMiddleFill": {
      "name": "ClashEffectRingMiddleFill",
      "alternativeNames": [
        "WhiteRingFill"
      ],
      "description": "The fill color for the middle, white expanding ring that appears after the shapes collide.",
      "path": "layers[6].shapes[0].it[1].c.k",
      "originalColor": "#ffffffff",
      "elementType": "fill",
      "roleFunction": "highlight",
      "visualLevel": "secondary",
      "semanticRole": "effect",
      "isThemeable": true,
      "isSkinTone": false,
      "isClothing": false,
      "isEffect": true,
      "isBackground": false,
      "elementGroups": [
        "clash-effect",
        "expanding-rings"
      ],
      "tags": [
        "shockwave",
        "impact",
        "white"
      ]
    },
    "ClashEffectRingOuterFill": {
      "name": "ClashEffectRingOuterFill",
      "alternativeNames": [
        "OutermostRingFill"
      ],
      "description": "The fill color for the outermost expanding ring that appears after the shapes collide. It shares its color with the VS text.",
      "path": "layers[7].shapes[0].it[1].c.k",
      "originalColor": "#a662d0ff",
      "elementType": "fill",
      "roleFunction": "highlight",
      "visualLevel": "secondary",
      "semanticRole": "effect",
      "isThemeable": true,
      "isSkinTone": false,
      "isClothing": false,
      "isEffect": true,
      "isBackground": false,
      "elementGroups": [
        "clash-effect",
        "expanding-rings",
        "primary-accent"
      ],
      "tags": [
        "shockwave",
        "impact"
      ]
    }
  }
}
