/**
 * VersusClash Theme Configurations
 * Generated by Lottie Naming Tool
 *
 * Variant: default
 * Total themes: 10
 */

import type { LottieThemeConfig } from "../../theming/lottieColorMapping"

export const defaultPurpleLightTheme: LottieThemeConfig = {
  themeId: "default-purple-light",
  name: "Purple Light",
  description: "A clean and professional theme with a light background, using shades of purple for an energetic yet sophisticated feel.",
  baseColor: "purple",
  mode: "light",
  colors: {
    TextVFill: "#3c1a51",
    TextSFill: "#3c1a51",
    ClashEffectBurstLineStroke: "#a15bca",
    ClashShapeRightFill: "#3c1a51",
    ClashShapeLeftFill: "#a15bca",
    ClashEffectRingCenterFill: "#FFFFFF",
    ClashEffectRingInnerFill: "#e0c9ee",
    ClashEffectRingMiddleFill: "#e1c2f5",
    ClashEffectRingOuterFill: "#a15bca",
  },
  skippedElements: [],
}

export const defaultPurpleDarkTheme: LottieThemeConfig = {
  themeId: "default-purple-dark",
  name: "Purple Dark",
  description: "A vibrant and energetic theme for dark mode, featuring bright purples and a hot pink accent for a high-contrast, gaming-inspired look.",
  baseColor: "purple",
  mode: "dark",
  colors: {
    TextVFill: "#F9F5FF",
    TextSFill: "#F9F5FF",
    ClashEffectBurstLineStroke: "#a15bca",
    ClashShapeRightFill: "#D90479",
    ClashShapeLeftFill: "#a15bca",
    ClashEffectRingCenterFill: "#FFFFFF",
    ClashEffectRingInnerFill: "#e1c2f5",
    ClashEffectRingMiddleFill: "#e0c9ee",
    ClashEffectRingOuterFill: "#a15bca",
  },
  skippedElements: [],
}

export const defaultBlueLightTheme: LottieThemeConfig = {
  themeId: "default-blue-light",
  name: "Versus Clash - Ocean Light",
  description: "A crisp and clean theme with bright blues, simulating a daytime clash of water and sky.",
  baseColor: "blue",
  mode: "light",
  colors: {
    TextVFill: "#1976D2",
    TextSFill: "#1976D2",
    ClashEffectBurstLineStroke: "#03A9F4",
    ClashShapeRightFill: "#03A9F4",
    ClashShapeLeftFill: "#1976D2",
    ClashEffectRingCenterFill: "#FFFFFF",
    ClashEffectRingInnerFill: "#90CAF9",
    ClashEffectRingMiddleFill: "#FFFFFF",
    ClashEffectRingOuterFill: "#4285F4",
  },
  skippedElements: [],
}

export const defaultBlueDarkTheme: LottieThemeConfig = {
  themeId: "default-blue-dark",
  name: "Versus Clash - Neon Dark",
  description: "An electrifying theme set against a dark background, with vibrant blues that glow like neon.",
  baseColor: "blue",
  mode: "dark",
  colors: {
    TextVFill: "#E8F5FE",
    TextSFill: "#E8F5FE",
    ClashEffectBurstLineStroke: "#29B6F6",
    ClashShapeRightFill: "#03A9F4",
    ClashShapeLeftFill: "#2196F3",
    ClashEffectRingCenterFill: "#FFFFFF",
    ClashEffectRingInnerFill: "#BBDEFB",
    ClashEffectRingMiddleFill: "#FFFFFF",
    ClashEffectRingOuterFill: "#2196F3",
  },
  skippedElements: [],
}

export const defaultGreenLightTheme: LottieThemeConfig = {
  themeId: "default-green-light",
  name: "Versus Clash - Verdant Rivalry",
  description: "A fresh and energetic theme using lush greens and teals, perfect for a clean, light interface.",
  baseColor: "green",
  mode: "light",
  colors: {
    TextVFill: "#388E3C",
    TextSFill: "#388E3C",
    ClashEffectBurstLineStroke: "#26A69A",
    ClashShapeRightFill: "#4CAF50",
    ClashShapeLeftFill: "#26A69A",
    ClashEffectRingCenterFill: "#FFFFFF",
    ClashEffectRingInnerFill: "#A5D6A7",
    ClashEffectRingMiddleFill: "#FFFFFF",
    ClashEffectRingOuterFill: "#4CAF50",
  },
  skippedElements: [],
}

export const defaultGreenDarkTheme: LottieThemeConfig = {
  themeId: "default-green-dark",
  name: "Versus Clash - Neon Forest",
  description: "A vibrant, high-contrast theme with glowing greens and teals set against a deep, dark background.",
  baseColor: "green",
  mode: "dark",
  colors: {
    TextVFill: "#A5D6A7",
    TextSFill: "#A5D6A7",
    ClashEffectBurstLineStroke: "#4DB6AC",
    ClashShapeRightFill: "#66BB6A",
    ClashShapeLeftFill: "#26A69A",
    ClashEffectRingCenterFill: "#FFFFFF",
    ClashEffectRingInnerFill: "#A5D6A7",
    ClashEffectRingMiddleFill: "#FFFFFF",
    ClashEffectRingOuterFill: "#66BB6A",
  },
  skippedElements: [],
}

export const defaultOrangeLightTheme: LottieThemeConfig = {
  themeId: "default-orange-light",
  name: "Versus Clash - Sunset Flare",
  description: "A warm and energetic theme with bright oranges and deep reds, optimized for light backgrounds.",
  baseColor: "orange",
  mode: "light",
  colors: {
    TextVFill: "#010203",
    TextSFill: "#010203",
    ClashEffectBurstLineStroke: "#FF9800",
    ClashShapeRightFill: "#FF7043",
    ClashShapeLeftFill: "#EF6C00",
    ClashEffectRingCenterFill: "#FFFFFF",
    ClashEffectRingInnerFill: "#FFB74D",
    ClashEffectRingMiddleFill: "#FF8A65",
    ClashEffectRingOuterFill: "#FF9800",
  },
  skippedElements: [],
}

export const defaultOrangeDarkTheme: LottieThemeConfig = {
  themeId: "default-orange-dark",
  name: "Versus Clash - Ember Glow",
  description: "A vibrant and glowing theme with luminous oranges against a dark, cool background.",
  baseColor: "orange",
  mode: "dark",
  colors: {
    TextVFill: "#FFF8F0",
    TextSFill: "#FFF8F0",
    ClashEffectBurstLineStroke: "#FFB74D",
    ClashShapeRightFill: "#FF7043",
    ClashShapeLeftFill: "#FFA726",
    ClashEffectRingCenterFill: "#FFFFFF",
    ClashEffectRingInnerFill: "#FF8A65",
    ClashEffectRingMiddleFill: "#FFA726",
    ClashEffectRingOuterFill: "#FF7043",
  },
  skippedElements: [],
}

export const defaultRedLightTheme: LottieThemeConfig = {
  themeId: "default-red-light",
  name: "Red Light",
  description: "A classic and energetic theme with strong reds, designed for high visibility on light backgrounds.",
  baseColor: "red",
  mode: "light",
  colors: {
    TextVFill: "#B71C1C",
    TextSFill: "#B71C1C",
    ClashEffectBurstLineStroke: "#FF1744",
    ClashShapeRightFill: "#E53935",
    ClashShapeLeftFill: "#B71C1C",
    ClashEffectRingCenterFill: "#FFFFFF",
    ClashEffectRingInnerFill: "#EF9A9A",
    ClashEffectRingMiddleFill: "#FFFFFF",
    ClashEffectRingOuterFill: "#E53935",
  },
  skippedElements: [],
}

export const defaultRedDarkTheme: LottieThemeConfig = {
  themeId: "default-red-dark",
  name: "Red Dark",
  description: "A vibrant and intense theme for dark mode, using fiery reds and a deep magenta for a dramatic clash.",
  baseColor: "red",
  mode: "dark",
  colors: {
    TextVFill: "#E57373",
    TextSFill: "#E57373",
    ClashEffectBurstLineStroke: "#FF5252",
    ClashShapeRightFill: "#be3030",
    ClashShapeLeftFill: "#880E4F",
    ClashEffectRingCenterFill: "#FFFFFF",
    ClashEffectRingInnerFill: "#FF5252",
    ClashEffectRingMiddleFill: "#E57373",
    ClashEffectRingOuterFill: "#be3030",
  },
  skippedElements: [],
}

/**
 * All themes for this animation
 */
export const allThemes: LottieThemeConfig[] = [
  defaultPurpleLightTheme,
  defaultPurpleDarkTheme,
  defaultBlueLightTheme,
  defaultBlueDarkTheme,
  defaultGreenLightTheme,
  defaultGreenDarkTheme,
  defaultOrangeLightTheme,
  defaultOrangeDarkTheme,
  defaultRedLightTheme,
  defaultRedDarkTheme,
]

/**
 * Theme lookup by ID
 */
export const themesById: Record<string, LottieThemeConfig> = {
  "default-purple-light": defaultPurpleLightTheme,
  "default-purple-dark": defaultPurpleDarkTheme,
  "default-blue-light": defaultBlueLightTheme,
  "default-blue-dark": defaultBlueDarkTheme,
  "default-green-light": defaultGreenLightTheme,
  "default-green-dark": defaultGreenDarkTheme,
  "default-orange-light": defaultOrangeLightTheme,
  "default-orange-dark": defaultOrangeDarkTheme,
  "default-red-light": defaultRedLightTheme,
  "default-red-dark": defaultRedDarkTheme,
}
