/**
 * TriangleFaceCharacter - ExpanseLottie Schema
 * Generated by AI Naming Tool
 */

import type { ExpanseLottie } from "../../types"

export const TriangleFaceCharacterSchema: ExpanseLottie = {
  "animationName": "TriangleFaceCharacter",
  "alternativeNames": [
    "BouncingTriangleBot",
    "GeometricAvatar",
    "TalkingTriangle",
    "ExpressiveMascot"
  ],
  "description": "A playful, animated character with a large blue triangular head, wearing sunglasses that continuously cycle through a vibrant spectrum of colors. The character bounces energetically, blinks its simple eyes, and features an expressive mouth that moves as if talking. Key themeable elements include the head color, the glasses fill, and the outline stroke color.",
  "tags": [
    "character",
    "avatar",
    "mascot",
    "triangle",
    "geometric",
    "bouncing",
    "talking",
    "expressive",
    "friendly",
    "tech",
    "icon",
    "loop",
    "sunglasses"
  ],
  "purpose": {
    "primary": "To serve as a friendly and engaging animated avatar or mascot, suitable for representing AI, chatbots, or brand personalities in a dynamic way.",
    "categories": {
      "UI/UX Feedback": [
        "Loading indicator",
        "Onboarding assistant",
        "Interactive help icon",
        "Success or confirmation message"
      ],
      "Branding & Identity": [
        "Animated logo",
        "Brand mascot for social media",
        "Website welcome animation",
        "Profile picture for a bot or service account"
      ],
      "Content Enhancement": [
        "Attention-grabbing icon for a section",
        "Expressive element in presentations",
        "Visual aid in educational videos"
      ]
    },
    "contexts": [
      "web-content",
      "gamification",
      "work",
      "education"
    ],
    "recommendations": [
      "Use as a looping element to signify an active or waiting state.",
      "Ideal for placement in corners of the UI as a persistent assistant or chatbot icon.",
      "Effective as a central element on loading screens or 404 pages."
    ]
  },
  "contextSpecificMetadata": {
    "education": {
      "context": "education",
      "primary": "An animated tutor or guide to make learning more engaging for students.",
      "useCaseExamples": [
        "Mascot for a children's coding platform.",
        "Character providing feedback in an interactive quiz.",
        "Animated guide in a course onboarding tutorial.",
        "Friendly face for a learning app's help section."
      ],
      "tags": [
        "tutor",
        "guide",
        "learning-assistant",
        "kids-app",
        "educational-mascot"
      ]
    },
    "work": {
      "context": "work",
      "primary": "A friendly and approachable avatar for a chatbot, AI assistant, or support tool.",
      "useCaseExamples": [
        "Avatar for an internal helpdesk chatbot.",
        "Loading animation while generating a report.",
        "Onboarding guide for new software features.",
        "Profile icon for an automated workflow bot in a messaging platform."
      ],
      "tags": [
        "chatbot",
        "ai-assistant",
        "support-bot",
        "onboarding",
        "automation"
      ]
    },
    "gamification": {
      "context": "gamification",
      "primary": "An expressive character to provide feedback, encouragement, or act as a user avatar.",
      "useCaseExamples": [
        "Character reacting to earning points or achievements.",
        "A customizable avatar for user profiles.",
        "A non-player character (NPC) that guides the user through tasks.",
        "Mascot on a leaderboard to add personality."
      ],
      "tags": [
        "avatar",
        "npc",
        "reward-feedback",
        "mascot",
        "achievement"
      ]
    },
    "life": {
      "context": "life",
      "primary": "A fun, expressive avatar for personal profiles or digital communication.",
      "useCaseExamples": [
        "Animated profile picture for social media.",
        "Reaction sticker or GIF in messaging apps.",
        "Personal mascot for a blog or portfolio website.",
        "Avatar for a personal finance or productivity app."
      ],
      "tags": [
        "avatar",
        "profile-picture",
        "sticker",
        "personal-brand",
        "expressive"
      ]
    },
    "web-content": {
      "context": "web-content",
      "primary": "An engaging visual element to improve user experience and guide interaction on a website.",
      "useCaseExamples": [
        "Friendly mascot on a 404 error page.",
        "Interactive element on a landing page that follows the cursor.",
        "Icon to launch a customer support chatbot.",
        "Loading animation for website content or images."
      ],
      "tags": [
        "mascot",
        "404-page",
        "chatbot-icon",
        "loading-animation",
        "interactive-element"
      ]
    }
  },
  "recommendations": {
    "recommendedColorPalettes": [
      "Vibrant Tech",
      "Corporate Blue & Gray",
      "Neon Cyberpunk",
      "Playful Pastels",
      "Monochrome with Accent"
    ],
    "elementGroups": {
      "logicalGrouped": {
        "head": {
          "elements": [
            "Layer 1"
          ],
          "description": "The main triangular shape of the character's head."
        },
        "glasses": {
          "elements": [
            "glass"
          ],
          "description": "The sunglasses/visor that animates through different colors."
        },
        "eyes": {
          "elements": [
            "Layer 7",
            "Layer 6"
          ],
          "description": "The two small, blinking eyes."
        },
        "mouth": {
          "elements": [
            "Layer 9",
            "Layer 4"
          ],
          "description": "The two animated lines that form the expressive mouth."
        },
        "nose": {
          "elements": [
            "Layer 8"
          ],
          "description": "The simple v-shaped line that serves as the nose."
        }
      },
      "sharedColor": {
        "outline-strokes": {
          "elements": [
            "Layer 1",
            "glass",
            "Layer 9",
            "Layer 4"
          ],
          "description": "The dark gray outlines defining the character's main shapes.",
          "colorRelationship": "identical"
        },
        "facial-details": {
          "elements": [
            "Layer 7",
            "Layer 6",
            "Layer 8"
          ],
          "description": "The light gray/off-white colors used for the eyes and nose.",
          "colorRelationship": "shades"
        },
        "head-fill": {
          "elements": [
            "Layer 1"
          ],
          "description": "The primary solid blue color of the head.",
          "colorRelationship": "single-color"
        },
        "glasses-fill": {
          "elements": [
            "glass"
          ],
          "description": "The fill of the glasses, which cycles through a spectrum of colors.",
          "colorRelationship": "color-cycle"
        }
      },
      "themingPriority": {
        "primary-fills": {
          "elements": [
            "Layer 1",
            "glass"
          ],
          "description": "The head and glasses colors are the most dominant and define the character's personality.",
          "priority": "high"
        },
        "outline-style": {
          "elements": [
            "Layer 1",
            "glass",
            "Layer 9",
            "Layer 4"
          ],
          "description": "The color of the main outlines, which sets the overall contrast and style.",
          "priority": "medium"
        },
        "detail-accents": {
          "elements": [
            "Layer 7",
            "Layer 6",
            "Layer 8"
          ],
          "description": "The subtle colors for the eyes and nose.",
          "priority": "low"
        }
      },
      "visualHierarchy": {
        "primary-focus": {
          "elements": [
            "Layer 1",
            "glass"
          ],
          "description": "The large head shape and color-changing glasses are the main focal points.",
          "hierarchy": "primary"
        },
        "secondary-features": {
          "elements": [
            "Layer 9",
            "Layer 4",
            "Layer 7",
            "Layer 6"
          ],
          "description": "The moving mouth and blinking eyes convey expression and are secondary elements.",
          "hierarchy": "secondary"
        },
        "subtle-details": {
          "elements": [
            "Layer 8"
          ],
          "description": "The nose is a subtle detail that completes the face.",
          "hierarchy": "accent"
        }
      }
    },
    "optionalAiContext": {
      "mood": "Playful, energetic, friendly, futuristic, helpful",
      "style": "Geometric, minimalist, flat design, character animation, vector art",
      "theme": "Technology, communication, AI, personality, digital assistant"
    },
    "optionalAiStylePrompts": {
      "aesthetic": "A minimalist geometric character, flat 2D vector style, bold outlines, vibrant accent colors, smooth looping animation",
      "style-adjectives": "Playful, modern, clean, digital, expressive, friendly"
    },
    "optionalAiVariantPrompts": {
      "character-variation": "Create a similar geometric character but with a hexagon-shaped head and a single monacle instead of sunglasses.",
      "emotion-variation": "Animate a 'surprised' version of this character, where it stops bouncing, its eyes widen, and its mouth forms an 'O' shape.",
      "theme-variation": "Adapt this character for a 'finance' theme, using green and gold colors, and changing the glasses to a dollar sign shape."
    }
  },
  "elements": {
    "GlassesFrameStroke": {
      "name": "GlassesFrameStroke",
      "alternativeNames": [
        "SunglassesOutline"
      ],
      "description": "The dark stroke that outlines the frame of the character's sunglasses.",
      "path": "layers[1].shapes[0].it[1].c.k",
      "originalColor": "#231f20ff",
      "elementType": "stroke",
      "roleFunction": "primary_subject",
      "visualLevel": "secondary",
      "semanticRole": "illustrative_object",
      "isThemeable": true,
      "isClothing": true,
      "isEffect": false,
      "isBackground": false,
      "elementGroups": [
        "character",
        "apparel",
        "glasses",
        "outline"
      ],
      "tags": [
        "sunglasses",
        "frame",
        "dark"
      ]
    },
    "GlassesLensFill": {
      "name": "GlassesLensFill",
      "alternativeNames": [
        "SunglassesLens"
      ],
      "description": "The animated, color-cycling fill for the lenses of the sunglasses.",
      "path": "layers[1].shapes[0].it[2].c.k",
      "originalColor": "#ff3ba2ff",
      "elementType": "fill",
      "roleFunction": "primary_subject",
      "visualLevel": "primary",
      "semanticRole": "illustrative_object",
      "isThemeable": true,
      "isClothing": true,
      "isEffect": false,
      "isBackground": false,
      "elementGroups": [
        "character",
        "apparel",
        "glasses",
        "fill"
      ],
      "tags": [
        "sunglasses",
        "lens",
        "animated",
        "color-cycle"
      ]
    },
    "GlassesHighlightStroke": {
      "name": "GlassesHighlightStroke",
      "alternativeNames": [
        "GlassesReflection"
      ],
      "description": "A subtle, light-colored stroke that acts as a highlight or reflection on the sunglasses.",
      "path": "layers[2].shapes[0].it[1].c.k",
      "originalColor": "#f2f4f9ff",
      "elementType": "stroke",
      "roleFunction": "highlight",
      "visualLevel": "tertiary",
      "semanticRole": "effect",
      "isThemeable": true,
      "isClothing": false,
      "isEffect": true,
      "isBackground": false,
      "elementGroups": [
        "character",
        "glasses",
        "effects",
        "highlight"
      ],
      "tags": [
        "reflection",
        "highlight",
        "subtle"
      ]
    },
    "EyeRightFill": {
      "name": "EyeRightFill",
      "description": "The fill color for the character's right eye, which blinks.",
      "path": "layers[3].shapes[0].it[1].c.k",
      "originalColor": "#dfe5f2ff",
      "elementType": "fill",
      "roleFunction": "primary_subject",
      "visualLevel": "secondary",
      "semanticRole": "illustrative_object",
      "isThemeable": true,
      "isClothing": false,
      "isEffect": false,
      "isBackground": false,
      "elementGroups": [
        "character",
        "face",
        "eyes"
      ],
      "tags": [
        "eye",
        "blinking",
        "animated"
      ]
    },
    "EyeLeftFill": {
      "name": "EyeLeftFill",
      "description": "The fill color for the character's left eye, which blinks.",
      "path": "layers[4].shapes[0].it[1].c.k",
      "originalColor": "#dfe5f2ff",
      "elementType": "fill",
      "roleFunction": "primary_subject",
      "visualLevel": "secondary",
      "semanticRole": "illustrative_object",
      "isThemeable": true,
      "isClothing": false,
      "isEffect": false,
      "isBackground": false,
      "elementGroups": [
        "character",
        "face",
        "eyes"
      ],
      "tags": [
        "eye",
        "blinking",
        "animated"
      ]
    },
    "MouthRightStroke": {
      "name": "MouthRightStroke",
      "description": "The stroke for the right side of the character's expressive, animated mouth.",
      "path": "layers[5].shapes[0].it[1].c.k",
      "originalColor": "#231f20ff",
      "elementType": "stroke",
      "roleFunction": "primary_subject",
      "visualLevel": "secondary",
      "semanticRole": "illustrative_object",
      "isThemeable": true,
      "isClothing": false,
      "isEffect": false,
      "isBackground": false,
      "elementGroups": [
        "character",
        "face",
        "mouth",
        "outline"
      ],
      "tags": [
        "mouth",
        "talking",
        "animated"
      ]
    },
    "MouthLeftStroke": {
      "name": "MouthLeftStroke",
      "description": "The stroke for the left side of the character's expressive, animated mouth.",
      "path": "layers[6].shapes[0].it[1].c.k",
      "originalColor": "#231f20ff",
      "elementType": "stroke",
      "roleFunction": "primary_subject",
      "visualLevel": "secondary",
      "semanticRole": "illustrative_object",
      "isThemeable": true,
      "isClothing": false,
      "isEffect": false,
      "isBackground": false,
      "elementGroups": [
        "character",
        "face",
        "mouth",
        "outline"
      ],
      "tags": [
        "mouth",
        "talking",
        "animated"
      ]
    },
    "HeadOutlineStroke": {
      "name": "HeadOutlineStroke",
      "description": "The main outline stroke for the character's triangular head.",
      "path": "layers[7].shapes[0].it[1].c.k",
      "originalColor": "#231f20ff",
      "elementType": "stroke",
      "roleFunction": "primary_subject",
      "visualLevel": "primary",
      "semanticRole": "illustrative_object",
      "isThemeable": true,
      "isClothing": false,
      "isEffect": false,
      "isBackground": false,
      "elementGroups": [
        "character",
        "face",
        "head",
        "outline"
      ],
      "tags": [
        "head",
        "outline",
        "primary"
      ]
    },
    "HeadMainFill": {
      "name": "HeadMainFill",
      "description": "The primary blue fill color for the character's triangular head.",
      "path": "layers[7].shapes[0].it[2].c.k",
      "originalColor": "#277af7ff",
      "elementType": "fill",
      "roleFunction": "primary_subject",
      "visualLevel": "primary",
      "semanticRole": "illustrative_object",
      "isThemeable": true,
      "isSkinTone": true,
      "isClothing": false,
      "isEffect": false,
      "isBackground": false,
      "elementGroups": [
        "character",
        "face",
        "head",
        "fill",
        "skin-tone"
      ],
      "tags": [
        "head",
        "fill",
        "primary",
        "blue"
      ]
    }
  }
}
