/**
 * TriangleFaceCharacter Theme Configurations
 * Generated by Lottie Naming Tool
 *
 * Variant: default
 * Total themes: 10
 */

import type { LottieThemeConfig } from "../../theming/lottieColorMapping"

export const defaultPurpleLightTheme: LottieThemeConfig = {
  themeId: "default-purple-light",
  name: "Purple Light",
  description:
    "A playful and bright theme with a primary purple character, dark outlines, and vibrant pink accents on a light background.",
  baseColor: "purple",
  mode: "light",
  colors: {
    GlassesFrameStroke: "#3c1a51",
    GlassesLensFill: "#D90479",
    GlassesHighlightStroke: "#e1c2f5",
    EyeRightFill: "#e1c2f5",
    EyeLeftFill: "#e1c2f5",
    MouthRightStroke: "#3c1a51",
    MouthLeftStroke: "#3c1a51",
    HeadOutlineStroke: "#3c1a51",
    HeadMainFill: "#a15bca",
  },
  skippedElements: ["GlassesLensFill"],
}

export const defaultPurpleDarkTheme: LottieThemeConfig = {
  themeId: "default-purple-dark",
  name: "Purple Dark",
  description:
    "A cool, neon-like theme featuring a vibrant purple character with glowing light purple outlines against a dark backdrop.",
  baseColor: "purple",
  mode: "dark",
  colors: {
    GlassesFrameStroke: "#e1c2f5",
    GlassesLensFill: "#D90479",
    GlassesHighlightStroke: "#F9F5FF",
    EyeRightFill: "#e1c2f5",
    EyeLeftFill: "#e1c2f5",
    MouthRightStroke: "#e1c2f5",
    MouthLeftStroke: "#e1c2f5",
    HeadOutlineStroke: "#e1c2f5",
    HeadMainFill: "#a15bca",
  },
  skippedElements: ["GlassesLensFill"],
}

export const defaultBlueLightTheme: LottieThemeConfig = {
  themeId: "default-blue-light",
  name: "Azure Pop",
  description:
    "A bright and energetic theme featuring a classic blue character with vibrant yellow sunglasses for a playful contrast.",
  baseColor: "blue",
  mode: "light",
  colors: {
    GlassesFrameStroke: "#343434",
    GlassesLensFill: "#FFC107",
    GlassesHighlightStroke: "#FFFFFF",
    EyeRightFill: "#E3F2FD",
    EyeLeftFill: "#E3F2FD",
    MouthRightStroke: "#343434",
    MouthLeftStroke: "#343434",
    HeadOutlineStroke: "#343434",
    HeadMainFill: "#4285F4",
  },
  skippedElements: ["GlassesLensFill"],
}

export const defaultBlueDarkTheme: LottieThemeConfig = {
  themeId: "default-blue-dark",
  name: "Midnight Glow",
  description:
    "A cool, high-contrast dark theme where the character's features and outlines glow against the dark.",
  baseColor: "blue",
  mode: "dark",
  colors: {
    GlassesFrameStroke: "#BBDEFB",
    GlassesLensFill: "#29B6F6",
    GlassesHighlightStroke: "#E8F5FE",
    EyeRightFill: "#BBDEFB",
    EyeLeftFill: "#BBDEFB",
    MouthRightStroke: "#BBDEFB",
    MouthLeftStroke: "#BBDEFB",
    HeadOutlineStroke: "#BBDEFB",
    HeadMainFill: "#2196F3",
  },
  skippedElements: ["GlassesLensFill"],
}

export const defaultGreenLightTheme: LottieThemeConfig = {
  themeId: "default-green-light",
  name: "Evergreen Pop",
  description:
    "A fresh and energetic theme with a vibrant green base, accented by cool teal and playful complementary colors. Designed for light backgrounds.",
  baseColor: "green",
  mode: "light",
  colors: {
    GlassesFrameStroke: "#343434",
    GlassesLensFill: "#26A69A",
    GlassesHighlightStroke: "#FFFFFF",
    EyeRightFill: "#FFFFFF",
    EyeLeftFill: "#FFFFFF",
    MouthRightStroke: "#343434",
    MouthLeftStroke: "#343434",
    HeadOutlineStroke: "#388E3C",
    HeadMainFill: "#4CAF50",
  },
  skippedElements: ["GlassesLensFill"],
}

export const defaultGreenDarkTheme: LottieThemeConfig = {
  themeId: "default-green-dark",
  name: "Neon Forest",
  description:
    "A high-contrast theme for dark interfaces, featuring a bright, glowing green character with vivid, luminous accents.",
  baseColor: "green",
  mode: "dark",
  colors: {
    GlassesFrameStroke: "#E8F5E9",
    GlassesLensFill: "#4DB6AC",
    GlassesHighlightStroke: "#FFFFFF",
    EyeRightFill: "#E8F5E9",
    EyeLeftFill: "#E8F5E9",
    MouthRightStroke: "#E8F5E9",
    MouthLeftStroke: "#E8F5E9",
    HeadOutlineStroke: "#A5D6A7",
    HeadMainFill: "#66BB6A",
  },
  skippedElements: ["GlassesLensFill"],
}

export const defaultOrangeLightTheme: LottieThemeConfig = {
  themeId: "default-orange-light",
  name: "Orange Light",
  description:
    "A bright and energetic theme featuring a warm orange character against a clean white background, accented with a cool cyan for a playful contrast.",
  baseColor: "orange",
  mode: "light",
  colors: {
    GlassesFrameStroke: "#343434",
    GlassesLensFill: "#00CFDE",
    GlassesHighlightStroke: "#FFFFFF",
    EyeRightFill: "#FFFFFF",
    EyeLeftFill: "#FFFFFF",
    MouthRightStroke: "#343434",
    MouthLeftStroke: "#343434",
    HeadOutlineStroke: "#343434",
    HeadMainFill: "#FF9800",
  },
  skippedElements: ["GlassesLensFill"],
}

export const defaultOrangeDarkTheme: LottieThemeConfig = {
  themeId: "default-orange-dark",
  name: "Orange Dark",
  description:
    "A high-contrast, glowing theme with a vibrant orange character set against a deep blue-gray background. Light outlines and vivid purple accents create a bold, modern look.",
  baseColor: "orange",
  mode: "dark",
  colors: {
    GlassesFrameStroke: "#FFF8F0",
    GlassesLensFill: "#B452E3",
    GlassesHighlightStroke: "#FFF8F0",
    EyeRightFill: "#A9A7AD",
    EyeLeftFill: "#A9A7AD",
    MouthRightStroke: "#FFF8F0",
    MouthLeftStroke: "#FFF8F0",
    HeadOutlineStroke: "#FFF8F0",
    HeadMainFill: "#FFA726",
  },
  skippedElements: ["GlassesLensFill"],
}

export const defaultRedLightTheme: LottieThemeConfig = {
  themeId: "default-red-light",
  name: "Crimson Cool",
  description:
    "A vibrant and energetic theme with a bold red head and classic black sunglasses, designed for light backgrounds.",
  baseColor: "red",
  mode: "light",
  colors: {
    GlassesFrameStroke: "#B71C1C",
    GlassesLensFill: "#010203",
    GlassesHighlightStroke: "#FFFFFF",
    EyeRightFill: "#FFFFFF",
    EyeLeftFill: "#FFFFFF",
    MouthRightStroke: "#B71C1C",
    MouthLeftStroke: "#B71C1C",
    HeadOutlineStroke: "#B71C1C",
    HeadMainFill: "#E53935",
  },
  skippedElements: ["GlassesLensFill"],
}

export const defaultRedDarkTheme: LottieThemeConfig = {
  themeId: "default-red-dark",
  name: "Ruby Glow",
  description:
    "A radiant dark mode theme featuring a softer red character with glowing lenses and bright white outlines for maximum contrast.",
  baseColor: "red",
  mode: "dark",
  colors: {
    GlassesFrameStroke: "#FFFFFF",
    GlassesLensFill: "#FF5252",
    GlassesHighlightStroke: "#FFFFFF",
    EyeRightFill: "#FFFFFF",
    EyeLeftFill: "#FFFFFF",
    MouthRightStroke: "#FFFFFF",
    MouthLeftStroke: "#FFFFFF",
    HeadOutlineStroke: "#FFFFFF",
    HeadMainFill: "#E57373",
  },
  skippedElements: ["GlassesLensFill"],
}

/**
 * All themes for this animation
 */
export const allThemes: LottieThemeConfig[] = [
  defaultPurpleLightTheme,
  defaultPurpleDarkTheme,
  defaultBlueLightTheme,
  defaultBlueDarkTheme,
  defaultGreenLightTheme,
  defaultGreenDarkTheme,
  defaultOrangeLightTheme,
  defaultOrangeDarkTheme,
  defaultRedLightTheme,
  defaultRedDarkTheme,
]

/**
 * Theme lookup by ID
 */
export const themesById: Record<string, LottieThemeConfig> = {
  "default-purple-light": defaultPurpleLightTheme,
  "default-purple-dark": defaultPurpleDarkTheme,
  "default-blue-light": defaultBlueLightTheme,
  "default-blue-dark": defaultBlueDarkTheme,
  "default-green-light": defaultGreenLightTheme,
  "default-green-dark": defaultGreenDarkTheme,
  "default-orange-light": defaultOrangeLightTheme,
  "default-orange-dark": defaultOrangeDarkTheme,
  "default-red-light": defaultRedLightTheme,
  "default-red-dark": defaultRedDarkTheme,
}
