/**
 * Homework Theme Configurations
 * Consolidated from individual theme files
 *
 * Variants: default, minimal
 * Total themes: 8
 */

import type { LottieThemeConfig } from "../../theming/lottieColorMapping"

export const defaultblueDarkTheme: LottieThemeConfig = {
  themeId: "default-blue-dark",
  name: "Blue Dark",
  description: "Blue dark mode theme for Homework animation",
  baseColor: "blue",
  mode: "dark",
  colors: {
    PencilBodyFill: "#64B5F6",
    PencilEraserFill: "#90CAF9",
    PencilEraserBandDarkFill: "#1976D2",
    PencilEraserBandLightFill: "#E3F2FD",
    PencilTipWoodFill: "#FFF8E1",
    PencilTipLeadFill: "#757575",
    NotebookCoverFill: "#42A5F5",
    NotebookSpineFill: "#1565C0",
    NotebookPageBaseFill: "#2D2D2D",
    NotebookPageLeftFill: "#383838",
    NotebookPageWriteLayer1Fill: "#2D2D2D",
    NotebookPageWriteLayer2Fill: "#2D2D2D",
    NotebookPageWriteLayer3Fill: "#2D2D2D",
    NotebookWrittenLine1Fill: "#64B5F6",
    NotebookWrittenLine2Fill: "#64B5F6",
    NotebookWrittenLine3Fill: "#64B5F6",
    NotebookWrittenLine4Fill: "#64B5F6",
    NotebookWrittenLine5Fill: "#64B5F6",
    NotebookWrittenLine6Fill: "#64B5F6",
    NotebookWrittenLine7Fill: "#64B5F6",
    NotebookWrittenLine8Fill: "#64B5F6",
    NotebookWrittenLine9Fill: "#64B5F6",
    NotebookWrittenLine10Fill: "#64B5F6",
    NotebookWrittenLine11Fill: "#64B5F6",
    NotebookWrittenLine12Fill: "#64B5F6",
    NotebookWrittenLine13Fill: "#64B5F6",
    NotebookWrittenLine14Fill: "#64B5F6",
    NotebookWrittenLine15Fill: "#64B5F6",
    NotebookWrittenLine16Fill: "#64B5F6",
    NotebookWrittenLine17Fill: "#64B5F6",
    NotebookWrittenLine18Fill: "#64B5F6",
    NotebookPageRuledLine1Fill: "#0D47A1",
    NotebookPageRuledLine2Fill: "#0D47A1",
    NotebookPageRuledLine3Fill: "#0D47A1",
    NotebookPageRuledLine4Fill: "#0D47A1",
    NotebookPageRuledLine5Fill: "#0D47A1",
    NotebookPageRuledLine6Fill: "#0D47A1",
    NotebookPageRuledLine7Fill: "#0D47A1",
    NotebookPageRuledLine8Fill: "#0D47A1",
    SparkleLeftFill: "#FFFFFF",
    SparkleRightFill: "#FFFFFF",
  },
  skippedElements: [],
}

export const defaultblueLightTheme: LottieThemeConfig = {
  themeId: "default-blue-light",
  name: "Blue Light",
  description: "Blue light mode theme for Homework animation",
  baseColor: "blue",
  mode: "light",
  colors: {
    PencilBodyFill: "#1976D2",
    PencilEraserFill: "#1565C0",
    PencilEraserBandDarkFill: "#0D47A1",
    PencilEraserBandLightFill: "#64B5F6",
    PencilTipWoodFill: "#FFF8E1",
    PencilTipLeadFill: "#424242",
    NotebookCoverFill: "#1565C0",
    NotebookSpineFill: "#0D47A1",
    NotebookPageBaseFill: "#FAFAFA",
    NotebookPageLeftFill: "#F5F5F5",
    NotebookPageWriteLayer1Fill: "#FAFAFA",
    NotebookPageWriteLayer2Fill: "#FAFAFA",
    NotebookPageWriteLayer3Fill: "#FAFAFA",
    NotebookWrittenLine1Fill: "#1976D2",
    NotebookWrittenLine2Fill: "#1976D2",
    NotebookWrittenLine3Fill: "#1976D2",
    NotebookWrittenLine4Fill: "#1976D2",
    NotebookWrittenLine5Fill: "#1976D2",
    NotebookWrittenLine6Fill: "#1976D2",
    NotebookWrittenLine7Fill: "#1976D2",
    NotebookWrittenLine8Fill: "#1976D2",
    NotebookWrittenLine9Fill: "#1976D2",
    NotebookWrittenLine10Fill: "#1976D2",
    NotebookWrittenLine11Fill: "#1976D2",
    NotebookWrittenLine12Fill: "#1976D2",
    NotebookWrittenLine13Fill: "#1976D2",
    NotebookWrittenLine14Fill: "#1976D2",
    NotebookWrittenLine15Fill: "#1976D2",
    NotebookWrittenLine16Fill: "#1976D2",
    NotebookWrittenLine17Fill: "#1976D2",
    NotebookWrittenLine18Fill: "#1976D2",
    NotebookPageRuledLine1Fill: "#BBDEFB",
    NotebookPageRuledLine2Fill: "#BBDEFB",
    NotebookPageRuledLine3Fill: "#BBDEFB",
    NotebookPageRuledLine4Fill: "#BBDEFB",
    NotebookPageRuledLine5Fill: "#BBDEFB",
    NotebookPageRuledLine6Fill: "#BBDEFB",
    NotebookPageRuledLine7Fill: "#BBDEFB",
    NotebookPageRuledLine8Fill: "#BBDEFB",
    SparkleLeftFill: "#FFFFFF",
    SparkleRightFill: "#FFFFFF",
  },
  skippedElements: [],
}

export const defaultpurpleDarkTheme: LottieThemeConfig = {
  themeId: "default-purple-dark",
  name: "Purple Dark",
  description: "Purple dark mode theme for Homework animation",
  baseColor: "purple",
  mode: "dark",
  colors: {
    PencilBodyFill: "#CE93D8",
    PencilEraserFill: "#E1BEE7",
    PencilEraserBandDarkFill: "#9C27B0",
    PencilEraserBandLightFill: "#F3E5F5",
    PencilTipWoodFill: "#FFF8E1",
    PencilTipLeadFill: "#757575",
    NotebookCoverFill: "#AB47BC",
    NotebookSpineFill: "#7B1FA2",
    NotebookPageBaseFill: "#2D2D2D",
    NotebookPageLeftFill: "#383838",
    NotebookPageWriteLayer1Fill: "#2D2D2D",
    NotebookPageWriteLayer2Fill: "#2D2D2D",
    NotebookPageWriteLayer3Fill: "#2D2D2D",
    NotebookWrittenLine1Fill: "#CE93D8",
    NotebookWrittenLine2Fill: "#CE93D8",
    NotebookWrittenLine3Fill: "#CE93D8",
    NotebookWrittenLine4Fill: "#CE93D8",
    NotebookWrittenLine5Fill: "#CE93D8",
    NotebookWrittenLine6Fill: "#CE93D8",
    NotebookWrittenLine7Fill: "#CE93D8",
    NotebookWrittenLine8Fill: "#CE93D8",
    NotebookWrittenLine9Fill: "#CE93D8",
    NotebookWrittenLine10Fill: "#CE93D8",
    NotebookWrittenLine11Fill: "#CE93D8",
    NotebookWrittenLine12Fill: "#CE93D8",
    NotebookWrittenLine13Fill: "#CE93D8",
    NotebookWrittenLine14Fill: "#CE93D8",
    NotebookWrittenLine15Fill: "#CE93D8",
    NotebookWrittenLine16Fill: "#CE93D8",
    NotebookWrittenLine17Fill: "#CE93D8",
    NotebookWrittenLine18Fill: "#CE93D8",
    NotebookPageRuledLine1Fill: "#4A148C",
    NotebookPageRuledLine2Fill: "#4A148C",
    NotebookPageRuledLine3Fill: "#4A148C",
    NotebookPageRuledLine4Fill: "#4A148C",
    NotebookPageRuledLine5Fill: "#4A148C",
    NotebookPageRuledLine6Fill: "#4A148C",
    NotebookPageRuledLine7Fill: "#4A148C",
    NotebookPageRuledLine8Fill: "#4A148C",
    SparkleLeftFill: "#FFFFFF",
    SparkleRightFill: "#FFFFFF",
  },
  skippedElements: [],
}

export const defaultpurpleLightTheme: LottieThemeConfig = {
  themeId: "default-purple-light",
  name: "Purple Light",
  description: "Purple light mode theme for Homework animation",
  baseColor: "purple",
  mode: "light",
  colors: {
    PencilBodyFill: "#9C27B0",
    PencilEraserFill: "#7B1FA2",
    PencilEraserBandDarkFill: "#4A148C",
    PencilEraserBandLightFill: "#CE93D8",
    PencilTipWoodFill: "#FFF8E1",
    PencilTipLeadFill: "#424242",
    NotebookCoverFill: "#7B1FA2",
    NotebookSpineFill: "#4A148C",
    NotebookPageBaseFill: "#FAFAFA",
    NotebookPageLeftFill: "#F5F5F5",
    NotebookPageWriteLayer1Fill: "#FAFAFA",
    NotebookPageWriteLayer2Fill: "#FAFAFA",
    NotebookPageWriteLayer3Fill: "#FAFAFA",
    NotebookWrittenLine1Fill: "#9C27B0",
    NotebookWrittenLine2Fill: "#9C27B0",
    NotebookWrittenLine3Fill: "#9C27B0",
    NotebookWrittenLine4Fill: "#9C27B0",
    NotebookWrittenLine5Fill: "#9C27B0",
    NotebookWrittenLine6Fill: "#9C27B0",
    NotebookWrittenLine7Fill: "#9C27B0",
    NotebookWrittenLine8Fill: "#9C27B0",
    NotebookWrittenLine9Fill: "#9C27B0",
    NotebookWrittenLine10Fill: "#9C27B0",
    NotebookWrittenLine11Fill: "#9C27B0",
    NotebookWrittenLine12Fill: "#9C27B0",
    NotebookWrittenLine13Fill: "#9C27B0",
    NotebookWrittenLine14Fill: "#9C27B0",
    NotebookWrittenLine15Fill: "#9C27B0",
    NotebookWrittenLine16Fill: "#9C27B0",
    NotebookWrittenLine17Fill: "#9C27B0",
    NotebookWrittenLine18Fill: "#9C27B0",
    NotebookPageRuledLine1Fill: "#E1BEE7",
    NotebookPageRuledLine2Fill: "#E1BEE7",
    NotebookPageRuledLine3Fill: "#E1BEE7",
    NotebookPageRuledLine4Fill: "#E1BEE7",
    NotebookPageRuledLine5Fill: "#E1BEE7",
    NotebookPageRuledLine6Fill: "#E1BEE7",
    NotebookPageRuledLine7Fill: "#E1BEE7",
    NotebookPageRuledLine8Fill: "#E1BEE7",
    SparkleLeftFill: "#FFFFFF",
    SparkleRightFill: "#FFFFFF",
  },
  skippedElements: [],
}

export const minimalblueDarkTheme: LottieThemeConfig = {
  themeId: "minimal-blue-dark",
  name: "Blue Dark (Minimal)",
  description: "Blue dark mode theme for Homework animation - minimal variant with only pencil and notebook cover themed",
  baseColor: "blue",
  mode: "dark",
  colors: {
    PencilBodyFill: "#64B5F6",
    PencilEraserFill: "#90CAF9",
    PencilEraserBandDarkFill: "#1976D2",
    PencilEraserBandLightFill: "#E3F2FD",
    NotebookCoverFill: "#42A5F5",
    NotebookSpineFill: "#1565C0",
  },
  skippedElements: [
    "PencilTipWoodFill",
    "PencilTipLeadFill",
    "NotebookPageBaseFill",
    "NotebookPageLeftFill",
    "NotebookPageWriteLayer1Fill",
    "NotebookPageWriteLayer2Fill",
    "NotebookPageWriteLayer3Fill",
    "NotebookWrittenLine1Fill",
    "NotebookWrittenLine2Fill",
    "NotebookWrittenLine3Fill",
    "NotebookWrittenLine4Fill",
    "NotebookWrittenLine5Fill",
    "NotebookWrittenLine6Fill",
    "NotebookWrittenLine7Fill",
    "NotebookWrittenLine8Fill",
    "NotebookWrittenLine9Fill",
    "NotebookWrittenLine10Fill",
    "NotebookWrittenLine11Fill",
    "NotebookWrittenLine12Fill",
    "NotebookWrittenLine13Fill",
    "NotebookWrittenLine14Fill",
    "NotebookWrittenLine15Fill",
    "NotebookWrittenLine16Fill",
    "NotebookWrittenLine17Fill",
    "NotebookWrittenLine18Fill",
    "NotebookPageRuledLine1Fill",
    "NotebookPageRuledLine2Fill",
    "NotebookPageRuledLine3Fill",
    "NotebookPageRuledLine4Fill",
    "NotebookPageRuledLine5Fill",
    "NotebookPageRuledLine6Fill",
    "NotebookPageRuledLine7Fill",
    "NotebookPageRuledLine8Fill",
    "SparkleLeftFill",
    "SparkleRightFill",
  ],
}

export const minimalblueLightTheme: LottieThemeConfig = {
  themeId: "minimal-blue-light",
  name: "Blue Light (Minimal)",
  description: "Blue light mode theme for Homework animation - minimal variant with only pencil and notebook cover themed",
  baseColor: "blue",
  mode: "light",
  colors: {
    PencilBodyFill: "#1976D2",
    PencilEraserFill: "#1565C0",
    PencilEraserBandDarkFill: "#0D47A1",
    PencilEraserBandLightFill: "#64B5F6",
    NotebookCoverFill: "#1565C0",
    NotebookSpineFill: "#0D47A1",
  },
  skippedElements: [
    "PencilTipWoodFill",
    "PencilTipLeadFill",
    "NotebookPageBaseFill",
    "NotebookPageLeftFill",
    "NotebookPageWriteLayer1Fill",
    "NotebookPageWriteLayer2Fill",
    "NotebookPageWriteLayer3Fill",
    "NotebookWrittenLine1Fill",
    "NotebookWrittenLine2Fill",
    "NotebookWrittenLine3Fill",
    "NotebookWrittenLine4Fill",
    "NotebookWrittenLine5Fill",
    "NotebookWrittenLine6Fill",
    "NotebookWrittenLine7Fill",
    "NotebookWrittenLine8Fill",
    "NotebookWrittenLine9Fill",
    "NotebookWrittenLine10Fill",
    "NotebookWrittenLine11Fill",
    "NotebookWrittenLine12Fill",
    "NotebookWrittenLine13Fill",
    "NotebookWrittenLine14Fill",
    "NotebookWrittenLine15Fill",
    "NotebookWrittenLine16Fill",
    "NotebookWrittenLine17Fill",
    "NotebookWrittenLine18Fill",
    "NotebookPageRuledLine1Fill",
    "NotebookPageRuledLine2Fill",
    "NotebookPageRuledLine3Fill",
    "NotebookPageRuledLine4Fill",
    "NotebookPageRuledLine5Fill",
    "NotebookPageRuledLine6Fill",
    "NotebookPageRuledLine7Fill",
    "NotebookPageRuledLine8Fill",
    "SparkleLeftFill",
    "SparkleRightFill",
  ],
}

export const minimalpurpleDarkTheme: LottieThemeConfig = {
  themeId: "minimal-purple-dark",
  name: "Purple Dark (Minimal)",
  description: "Purple dark mode theme for Homework animation - minimal variant with only pencil and notebook cover themed",
  baseColor: "purple",
  mode: "dark",
  colors: {
    PencilBodyFill: "#CE93D8",
    PencilEraserFill: "#E1BEE7",
    PencilEraserBandDarkFill: "#9C27B0",
    PencilEraserBandLightFill: "#F3E5F5",
    NotebookCoverFill: "#AB47BC",
    NotebookSpineFill: "#7B1FA2",
  },
  skippedElements: [
    "PencilTipWoodFill",
    "PencilTipLeadFill",
    "NotebookPageBaseFill",
    "NotebookPageLeftFill",
    "NotebookPageWriteLayer1Fill",
    "NotebookPageWriteLayer2Fill",
    "NotebookPageWriteLayer3Fill",
    "NotebookWrittenLine1Fill",
    "NotebookWrittenLine2Fill",
    "NotebookWrittenLine3Fill",
    "NotebookWrittenLine4Fill",
    "NotebookWrittenLine5Fill",
    "NotebookWrittenLine6Fill",
    "NotebookWrittenLine7Fill",
    "NotebookWrittenLine8Fill",
    "NotebookWrittenLine9Fill",
    "NotebookWrittenLine10Fill",
    "NotebookWrittenLine11Fill",
    "NotebookWrittenLine12Fill",
    "NotebookWrittenLine13Fill",
    "NotebookWrittenLine14Fill",
    "NotebookWrittenLine15Fill",
    "NotebookWrittenLine16Fill",
    "NotebookWrittenLine17Fill",
    "NotebookWrittenLine18Fill",
    "NotebookPageRuledLine1Fill",
    "NotebookPageRuledLine2Fill",
    "NotebookPageRuledLine3Fill",
    "NotebookPageRuledLine4Fill",
    "NotebookPageRuledLine5Fill",
    "NotebookPageRuledLine6Fill",
    "NotebookPageRuledLine7Fill",
    "NotebookPageRuledLine8Fill",
    "SparkleLeftFill",
    "SparkleRightFill",
  ],
}

export const minimalpurpleLightTheme: LottieThemeConfig = {
  themeId: "minimal-purple-light",
  name: "Purple Light (Minimal)",
  description: "Purple light mode theme for Homework animation - minimal variant with only pencil and notebook cover themed",
  baseColor: "purple",
  mode: "light",
  colors: {
    PencilBodyFill: "#9C27B0",
    PencilEraserFill: "#7B1FA2",
    PencilEraserBandDarkFill: "#4A148C",
    PencilEraserBandLightFill: "#CE93D8",
    NotebookCoverFill: "#7B1FA2",
    NotebookSpineFill: "#4A148C",
  },
  skippedElements: [
    "PencilTipWoodFill",
    "PencilTipLeadFill",
    "NotebookPageBaseFill",
    "NotebookPageLeftFill",
    "NotebookPageWriteLayer1Fill",
    "NotebookPageWriteLayer2Fill",
    "NotebookPageWriteLayer3Fill",
    "NotebookWrittenLine1Fill",
    "NotebookWrittenLine2Fill",
    "NotebookWrittenLine3Fill",
    "NotebookWrittenLine4Fill",
    "NotebookWrittenLine5Fill",
    "NotebookWrittenLine6Fill",
    "NotebookWrittenLine7Fill",
    "NotebookWrittenLine8Fill",
    "NotebookWrittenLine9Fill",
    "NotebookWrittenLine10Fill",
    "NotebookWrittenLine11Fill",
    "NotebookWrittenLine12Fill",
    "NotebookWrittenLine13Fill",
    "NotebookWrittenLine14Fill",
    "NotebookWrittenLine15Fill",
    "NotebookWrittenLine16Fill",
    "NotebookWrittenLine17Fill",
    "NotebookWrittenLine18Fill",
    "NotebookPageRuledLine1Fill",
    "NotebookPageRuledLine2Fill",
    "NotebookPageRuledLine3Fill",
    "NotebookPageRuledLine4Fill",
    "NotebookPageRuledLine5Fill",
    "NotebookPageRuledLine6Fill",
    "NotebookPageRuledLine7Fill",
    "NotebookPageRuledLine8Fill",
    "SparkleLeftFill",
    "SparkleRightFill",
  ],
}

/**
 * All themes for this animation
 */
export const allThemes: LottieThemeConfig[] = [
  defaultblueDarkTheme,
  defaultblueLightTheme,
  defaultpurpleDarkTheme,
  defaultpurpleLightTheme,
  minimalblueDarkTheme,
  minimalblueLightTheme,
  minimalpurpleDarkTheme,
  minimalpurpleLightTheme,
]

/**
 * Theme lookup by ID
 */
export const themesById: Record<string, LottieThemeConfig> = {
  "default-blue-dark": defaultblueDarkTheme,
  "default-blue-light": defaultblueLightTheme,
  "default-purple-dark": defaultpurpleDarkTheme,
  "default-purple-light": defaultpurpleLightTheme,
  "minimal-blue-dark": minimalblueDarkTheme,
  "minimal-blue-light": minimalblueLightTheme,
  "minimal-purple-dark": minimalpurpleDarkTheme,
  "minimal-purple-light": minimalpurpleLightTheme,
}
