/**
 * SmilingFaceAnimation - Unified Theme Schema
 * Generated by AI Metadata Tool
 *
 * This schema defines the themeable elements and metadata for the SmilingFaceAnimation animation.
 */

import type { ExpanseLottieSchema } from "../../types/ExpanseLottie"

const SmilingFaceAnimationSchema: ExpanseLottieSchema = {
  animationName: "SmilingFaceAnimation",

  // Alternative names suggested by AI
  alternativeNames: [
    "SmilingFaceAnimation",
    "HappyFaceIcon",
    "FriendlyFaceLottie",
    "JoyfulExpression",
    "CheerfulFace",
  ],

  // Animation description
  description:
    "This Lottie animation features a smiling face with a joyful expression. The face is rendered in purple hues and white, and it animates with a subtle, cheerful bounce. The animation conveys positivity and happiness.",

  // Metadata tags for categorization
  tags: [
    "happy",
    "smiling",
    "face",
    "joyful",
    "cheerful",
    "purple",
    "friendly",
    "positive",
    "icon",
    "emotion",
  ],

  // General purpose and use cases
  purpose: {
    primary:
      "To visually represent happiness, agreement, or a positive affirmation.",
    categories: {
      celebration: [
        "Display after a successful action or achievement.",
        "Use as a visual cue for positive feedback.",
        "Integrate into celebratory messages.",
      ],
      motivation: [
        "Show when a user completes a small task to provide encouragement.",
        "Use as a visual reminder to stay positive.",
        "Display after a user achieves a goal.",
      ],
      ambient: [
        "Serve as a background element in a calming or positive interface.",
        "Create a cheerful atmosphere within an application.",
        "Enhance the visual appeal of a website.",
      ],
    },
    contexts: ["Generic", "Life", "Web Content"],
    recommendations: [
      "Use sparingly to avoid diluting its impact.",
      "Ensure the animation matches the overall tone and style of the interface.",
      "Consider accessibility when choosing colors and animation speed.",
    ],
  },

  // Context-specific purposes for different application domains
  contextSpecificPurposes: {
    education: {
      primary:
        "To encourage students and provide positive reinforcement during learning activities.",
      useCases: [
        "Display after correctly answering a quiz question.",
        "Show after completing a lesson or module.",
        "Use as a visual reward for participation.",
      ],
    },
    work: {
      primary:
        "To acknowledge task completion or positive feedback within a professional setting.",
      useCases: [
        "Show after successfully submitting a report.",
        "Display upon receiving positive peer feedback.",
        "Use in project management tools to indicate task completion.",
      ],
    },
    gamification: {
      primary:
        "To reward players and provide visual feedback for positive actions within a game.",
      useCases: [
        "Display after earning points or completing a level.",
        "Show after unlocking an achievement or reward.",
        "Use as a visual cue for positive game events.",
      ],
    },
    life: {
      primary:
        "To enhance personal apps with positive and encouraging visuals.",
      useCases: [
        "Display after completing a workout.",
        "Show after achieving a personal goal.",
        "Use in habit-tracking apps to celebrate streaks.",
      ],
    },
    webContent: {
      primary:
        "To add a touch of positivity and engagement to websites and landing pages.",
      useCases: [
        "Use as a visual cue for positive feedback or approval.",
        "Display after a user submits a form or makes a purchase.",
        "Integrate into marketing materials to convey a friendly and approachable brand image.",
      ],
    },
    softwareDevelopment: {
      primary:
        "To provide positive feedback and visual cues in development tools and platforms.",
      useCases: [
        "Show after successfully compiling code.",
        "Display after completing a tutorial or learning module.",
        "Use in code review tools to indicate approval.",
      ],
    },
    marketing: {
      primary:
        "To create engaging and positive marketing campaigns and advertisements.",
      useCases: [
        "Use in social media posts to convey happiness or excitement.",
        "Display in advertisements to create a positive brand association.",
        "Integrate into email marketing campaigns to encourage engagement.",
      ],
    },
  },

  // TODO: Add themed elements configuration
  // Uncomment and configure the elements that need theming
  elements: [
    // Example:
    // {
    //   name: "ElementName",
    //   path: "LayerName.ShapeName",
    //   type: "fill" | "stroke",
    //   description: "What this element represents",
    //   defaultColor: "#HEXCODE",
    //   aiGenerationPrompt: "How AI should interpret this element",
    // },
  ],
}

export default SmilingFaceAnimationSchema
