/**
 * SmilingFaceAnimation - Unified Theme Schema
 * Generated by AI Metadata Tool
 *
 * This schema defines the themeable elements and metadata for the SmilingFaceAnimation animation.
 */

import type { ExpanseLottieSchema } from "../../types/ExpanseLottie"

const SmilingFaceAnimationSchema: ExpanseLottieSchema = {
  animationName: "SmilingFaceAnimation",

  // Alternative names suggested by AI
  alternativeNames: [
    "SmilingFaceAnimation",
    "HappyFaceWink",
    "FriendlyFaceIcon",
    "PurpleSmiley",
    "JoyfulExpression",
  ],

  // Animation description
  description:
    "This animation features a stylized purple face with a wide smile and a playful wink. The face subtly pulses and winks, conveying a feeling of happiness, friendliness, and positive emotion. The clean design and smooth animation make it suitable for a variety of applications.",

  // Metadata tags for categorization
  tags: [
    "smile",
    "happy",
    "face",
    "wink",
    "purple",
    "friendly",
    "joyful",
    "positive",
    "greeting",
    "emoji",
  ],

  // General purpose and use cases
  purpose: {
    primary:
      "To visually represent happiness, agreement, or a positive affirmation.",
    categories: {
      motivation: [
        "Positive reinforcement in user interfaces",
        "Encouraging user engagement",
        "Boosting morale in team communications",
      ],
      completion: [
        "Signifying successful task completion",
        "Confirmation of a positive outcome",
        "Acknowledgement of user interaction",
      ],
      reward: [
        "Visual reward for achieving a goal",
        "Acknowledgement of positive behavior",
        "Positive feedback mechanism",
      ],
    },
    contexts: ["Generic", "Web Content", "Gamification"],
    recommendations: [
      "Use sparingly to avoid visual clutter",
      "Ensure the color scheme matches the overall design",
      "Consider using sound effects to enhance the animation's impact",
    ],
  },

  // Context-specific purposes for different application domains
  contextSpecificPurposes: {
    education: {
      primary:
        "Used to provide positive feedback and encouragement to students.",
      useCases: [
        "Acknowledging correct answers",
        "Celebrating completion of a lesson",
        "Encouraging participation in activities",
      ],
    },
    work: {
      primary:
        "Used in team communication and productivity tools to convey positive sentiment and acknowledge accomplishments.",
      useCases: [
        "Acknowledging a task completion",
        "Showing appreciation for team contributions",
        "Boosting morale in chat applications",
      ],
    },
    gamification: {
      primary:
        "Used as a visual reward or positive feedback mechanism in games and interactive experiences.",
      useCases: [
        "Rewarding players for completing challenges",
        "Providing positive feedback for good performance",
        "Celebrating level completion",
      ],
    },
    life: {
      primary:
        "Used in personal apps and communications to express happiness and positive emotions.",
      useCases: [
        "Responding to messages with a positive reaction",
        "Expressing joy in personal journaling apps",
        "Celebrating personal achievements in habit trackers",
      ],
    },
    webContent: {
      primary:
        "Used in websites and apps to create a friendly and engaging user experience.",
      useCases: [
        "Providing positive feedback on form submissions",
        "Welcoming users to the website",
        "Celebrating successful transactions",
      ],
    },
    softwareDevelopment: {
      primary:
        "Used in development tools to provide positive feedback during coding and testing.",
      useCases: [
        "Signifying successful build completion",
        "Acknowledging successful code execution",
        "Indicating passing test cases",
      ],
    },
    marketing: {
      primary:
        "Used in marketing materials to convey a positive and friendly brand image.",
      useCases: [
        "Welcoming new customers",
        "Celebrating sales milestones",
        "Expressing gratitude to loyal customers",
      ],
    },
  },

  // TODO: Add themed elements configuration
  // Uncomment and configure the elements that need theming
  elements: [
    // Example:
    // {
    //   name: "ElementName",
    //   path: "LayerName.ShapeName",
    //   type: "fill" | "stroke",
    //   description: "What this element represents",
    //   defaultColor: "#HEXCODE",
    //   aiGenerationPrompt: "How AI should interpret this element",
    // },
  ],
}

export default SmilingFaceAnimationSchema
