/**
 * RocketLaunch Theme Configurations
 * Consolidated from individual theme files
 *
 * Variants: ImprovedDualToneColor, ImprovedMonochromeColoring, default
 * Total themes: 34
 */

import type { LottieThemeConfig } from "../../theming/lottieColorMapping"

export const improveddualtonecolorblueDarkTheme: LottieThemeConfig = {
  themeId: "ImprovedDualToneColor-blue-dark",
  name: "Blue Dark",
  description:
    "Improved dual-tone blue+gold dark theme with complementary colors for enhanced visual appeal. Blue (#2196F3 from MUI dark) for characters, gold (#FFB300 from MUI dark) for rocket and effects.",
  baseColor: "blue",
  mode: "dark",
  colors: {
    MainCharacterRightHandPalmFill: "#2196F3ff",
    MainCharacterRightHandThumbFill: "#64b5f6ff",
    MainCharacterLeftHandPalmFill: "#2196F3ff",
    MainCharacterLeftHandThumbFill: "#64b5f6ff",
    MainCharacterHeadBaseFill: "#1976d2ff",
    MainCharacterHeadFaceFill: "#0d47a1ff",
    MainCharacterNeckFill: "#42a5f5ff",
    MainCharacterTorsoFill: "#2196F3ff",
    MainCharacterLegUpperFill: "#64b5f6ff",
    MainCharacterFootFill: "#64b5f6ff",
    MainCharacterLegLowerFill: "#1976d2ff",
    RocketExhaustCloudFill: "#f57f17ff",
    SidekickCharacterLeftHandThumbFill: "#64b5f6ff",
    SidekickCharacterLeftHandPalmFill: "#42a5f5ff",
    SidekickCharacterHeadBaseFill: "#2196F3ff",
    SidekickCharacterHeadFaceFill: "#0d47a1ff",
    SidekickCharacterRightHandPalmFill: "#42a5f5ff",
    SidekickCharacterNeckFill: "#42a5f5ff",
    SidekickCharacterTorsoFill: "#42a5f5ff",
    SidekickCharacterLegUpperFill: "#2196F3ff",
    SidekickCharacterFootFill: "#2196F3ff",
    SidekickCharacterLegLowerFill: "#1976d2ff",
    RocketWindowLeftFill: "#f57f17ff",
    RocketWindowLeftFrameFill: "#FFB300ff",
    RocketWindowRightFill: "#f57f17ff",
    RocketWindowRightFrameFill: "#FFB300ff",
    RocketWindowBottomFill: "#f57f17ff",
    RocketWindowBottomFrameFill: "#FFB300ff",
    RocketNoseConeFill: "#f9a825ff",
    RocketFinBottomFill: "#ffc107ff",
    RocketFinLeftFill: "#ffc107ff",
    RocketExhaustOuterFlameFill: "#ffe082ff",
    RocketExhaustInnerFlameFill: "#FFB300ff",
    SparkleTopRightFill: "#ffecb3ff",
    SparkleTopRightLateFill: "#ffecb3ff",
    SparkleTopCenterFill: "#ffecb3ff",
    SparkleFarRightFill: "#FFB300ff",
    SparkleFarLeftFill: "#FFB300ff",
    SparkleTopLeftFill: "#f9a825ff",
    SparkleBottomLeftFill: "#f9a825ff",
    SparkleBottomCenterFill: "#f9a825ff",
    SparkleBottomRightFill: "#ffe082ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete dual-tone dark theme using blue (primary) for characters and gold (secondary) for rocket and effects. Optimized for dark backgrounds with rich colors and maintained contrast.",
  },
}

export const improveddualtonecolorblueLightTheme: LottieThemeConfig = {
  themeId: "ImprovedDualToneColor-blue-light",
  name: "Blue Light",
  description:
    "Improved dual-tone blue+gold light theme with complementary colors for enhanced visual appeal. Blue (#4285f4 from MUI) for characters, gold (#F9A825 from MUI) for rocket and effects.",
  baseColor: "blue",
  mode: "light",
  colors: {
    MainCharacterRightHandPalmFill: "#4285f4ff",
    MainCharacterRightHandThumbFill: "#80b3f8ff",
    MainCharacterLeftHandPalmFill: "#4285f4ff",
    MainCharacterLeftHandThumbFill: "#80b3f8ff",
    MainCharacterHeadBaseFill: "#1a5dc7ff",
    MainCharacterHeadFaceFill: "#d4e3fcff",
    MainCharacterNeckFill: "#5a9af6ff",
    MainCharacterTorsoFill: "#4285f4ff",
    MainCharacterLegUpperFill: "#80b3f8ff",
    MainCharacterFootFill: "#80b3f8ff",
    MainCharacterLegLowerFill: "#1a5dc7ff",
    RocketExhaustCloudFill: "#fff9e6ff",
    SidekickCharacterLeftHandThumbFill: "#80b3f8ff",
    SidekickCharacterLeftHandPalmFill: "#5a9af6ff",
    SidekickCharacterHeadBaseFill: "#4285f4ff",
    SidekickCharacterHeadFaceFill: "#d4e3fcff",
    SidekickCharacterRightHandPalmFill: "#5a9af6ff",
    SidekickCharacterNeckFill: "#5a9af6ff",
    SidekickCharacterTorsoFill: "#5a9af6ff",
    SidekickCharacterLegUpperFill: "#4285f4ff",
    SidekickCharacterFootFill: "#4285f4ff",
    SidekickCharacterLegLowerFill: "#1a5dc7ff",
    RocketWindowLeftFill: "#fff9e6ff",
    RocketWindowLeftFrameFill: "#F9A825ff",
    RocketWindowRightFill: "#fff9e6ff",
    RocketWindowRightFrameFill: "#F9A825ff",
    RocketWindowBottomFill: "#fff9e6ff",
    RocketWindowBottomFrameFill: "#F9A825ff",
    RocketNoseConeFill: "#F57F17ff",
    RocketFinBottomFill: "#F9A825ff",
    RocketFinLeftFill: "#F9A825ff",
    RocketExhaustOuterFlameFill: "#FFD54Fff",
    RocketExhaustInnerFlameFill: "#F9A825ff",
    SparkleTopRightFill: "#fff3ccff",
    SparkleTopRightLateFill: "#fff3ccff",
    SparkleTopCenterFill: "#fff3ccff",
    SparkleFarRightFill: "#F9A825ff",
    SparkleFarLeftFill: "#F9A825ff",
    SparkleTopLeftFill: "#F57F17ff",
    SparkleBottomLeftFill: "#F57F17ff",
    SparkleBottomCenterFill: "#F57F17ff",
    SparkleBottomRightFill: "#FFD54Fff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete dual-tone theme using blue (primary) for characters and gold (secondary) for rocket and effects. Blue provides the main visual identity while gold creates warm complementary contrast. Character faces use light blue, rocket/window highlights use light gold. All elements themed for full dual-tone visual cohesion.",
  },
}

export const improveddualtonecolorgreenDarkTheme: LottieThemeConfig = {
  themeId: "ImprovedDualToneColor-green-dark",
  name: "Green Dark",
  description:
    "Improved dual-tone green+red dark theme with complementary colors for enhanced visual appeal. Green (#66BB6A from MUI dark) for characters, red (#be3030 from MUI dark) for rocket and effects.",
  baseColor: "green",
  mode: "dark",
  colors: {
    MainCharacterRightHandPalmFill: "#66BB6Aff",
    MainCharacterRightHandThumbFill: "#a5d6a7ff",
    MainCharacterLeftHandPalmFill: "#66BB6Aff",
    MainCharacterLeftHandThumbFill: "#a5d6a7ff",
    MainCharacterHeadBaseFill: "#43a047ff",
    MainCharacterHeadFaceFill: "#2e7d32ff",
    MainCharacterNeckFill: "#81c784ff",
    MainCharacterTorsoFill: "#66BB6Aff",
    MainCharacterLegUpperFill: "#a5d6a7ff",
    MainCharacterFootFill: "#a5d6a7ff",
    MainCharacterLegLowerFill: "#43a047ff",
    RocketExhaustCloudFill: "#8b2424ff",
    SidekickCharacterLeftHandThumbFill: "#a5d6a7ff",
    SidekickCharacterLeftHandPalmFill: "#81c784ff",
    SidekickCharacterHeadBaseFill: "#66BB6Aff",
    SidekickCharacterHeadFaceFill: "#2e7d32ff",
    SidekickCharacterRightHandPalmFill: "#81c784ff",
    SidekickCharacterNeckFill: "#81c784ff",
    SidekickCharacterTorsoFill: "#81c784ff",
    SidekickCharacterLegUpperFill: "#66BB6Aff",
    SidekickCharacterFootFill: "#66BB6Aff",
    SidekickCharacterLegLowerFill: "#43a047ff",
    RocketWindowLeftFill: "#8b2424ff",
    RocketWindowLeftFrameFill: "#be3030ff",
    RocketWindowRightFill: "#8b2424ff",
    RocketWindowRightFrameFill: "#be3030ff",
    RocketWindowBottomFill: "#8b2424ff",
    RocketWindowBottomFrameFill: "#be3030ff",
    RocketNoseConeFill: "#c62828ff",
    RocketFinBottomFill: "#d32f2fff",
    RocketFinLeftFill: "#d32f2fff",
    RocketExhaustOuterFlameFill: "#ef9a9aff",
    RocketExhaustInnerFlameFill: "#be3030ff",
    SparkleTopRightFill: "#ffcdd2ff",
    SparkleTopRightLateFill: "#ffcdd2ff",
    SparkleTopCenterFill: "#ffcdd2ff",
    SparkleFarRightFill: "#be3030ff",
    SparkleFarLeftFill: "#be3030ff",
    SparkleTopLeftFill: "#c62828ff",
    SparkleBottomLeftFill: "#c62828ff",
    SparkleBottomCenterFill: "#c62828ff",
    SparkleBottomRightFill: "#ef9a9aff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete dual-tone dark theme using green (primary) for characters and red (secondary) for rocket and effects. Optimized for dark backgrounds with rich colors and maintained contrast.",
  },
}

export const improveddualtonecolorgreenLightTheme: LottieThemeConfig = {
  themeId: "ImprovedDualToneColor-green-light",
  name: "Green Light",
  description:
    "Improved dual-tone green+red light theme with complementary colors for enhanced visual appeal. Green (#4CAF50 from MUI) for characters, red (#be3030 from MUI) for rocket and effects.",
  baseColor: "green",
  mode: "light",
  colors: {
    MainCharacterRightHandPalmFill: "#4CAF50ff",
    MainCharacterRightHandThumbFill: "#81c784ff",
    MainCharacterLeftHandPalmFill: "#4CAF50ff",
    MainCharacterLeftHandThumbFill: "#81c784ff",
    MainCharacterHeadBaseFill: "#2e7d32ff",
    MainCharacterHeadFaceFill: "#d7f3d8ff",
    MainCharacterNeckFill: "#66bb6aff",
    MainCharacterTorsoFill: "#4CAF50ff",
    MainCharacterLegUpperFill: "#81c784ff",
    MainCharacterFootFill: "#81c784ff",
    MainCharacterLegLowerFill: "#2e7d32ff",
    RocketExhaustCloudFill: "#ffebebff",
    SidekickCharacterLeftHandThumbFill: "#81c784ff",
    SidekickCharacterLeftHandPalmFill: "#66bb6aff",
    SidekickCharacterHeadBaseFill: "#4CAF50ff",
    SidekickCharacterHeadFaceFill: "#d7f3d8ff",
    SidekickCharacterRightHandPalmFill: "#66bb6aff",
    SidekickCharacterNeckFill: "#66bb6aff",
    SidekickCharacterTorsoFill: "#66bb6aff",
    SidekickCharacterLegUpperFill: "#4CAF50ff",
    SidekickCharacterFootFill: "#4CAF50ff",
    SidekickCharacterLegLowerFill: "#2e7d32ff",
    RocketWindowLeftFill: "#ffebebff",
    RocketWindowLeftFrameFill: "#be3030ff",
    RocketWindowRightFill: "#ffebebff",
    RocketWindowRightFrameFill: "#be3030ff",
    RocketWindowBottomFill: "#ffebebff",
    RocketWindowBottomFrameFill: "#be3030ff",
    RocketNoseConeFill: "#8b2424ff",
    RocketFinBottomFill: "#c62828ff",
    RocketFinLeftFill: "#c62828ff",
    RocketExhaustOuterFlameFill: "#ef9a9aff",
    RocketExhaustInnerFlameFill: "#be3030ff",
    SparkleTopRightFill: "#ffcdd2ff",
    SparkleTopRightLateFill: "#ffcdd2ff",
    SparkleTopCenterFill: "#ffcdd2ff",
    SparkleFarRightFill: "#be3030ff",
    SparkleFarLeftFill: "#be3030ff",
    SparkleTopLeftFill: "#8b2424ff",
    SparkleBottomLeftFill: "#8b2424ff",
    SparkleBottomCenterFill: "#8b2424ff",
    SparkleBottomRightFill: "#ef9a9aff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete dual-tone theme using green (primary) for characters and red (secondary) for rocket and effects. Green provides the main visual identity while red creates exciting complementary contrast. Character faces use light green, rocket/window highlights use light red. All elements themed for full dual-tone visual cohesion.",
  },
}

export const improveddualtonecolororangeDarkTheme: LottieThemeConfig = {
  themeId: "ImprovedDualToneColor-orange-dark",
  name: "Orange Dark",
  description:
    "Improved dual-tone orange+blue dark theme with complementary colors for enhanced visual appeal. Orange (#FFA726 from MUI dark) for characters, blue (#2196F3 from MUI dark) for rocket and effects.",
  baseColor: "orange",
  mode: "dark",
  colors: {
    MainCharacterRightHandPalmFill: "#FFA726ff",
    MainCharacterRightHandThumbFill: "#ffcc80ff",
    MainCharacterLeftHandPalmFill: "#FFA726ff",
    MainCharacterLeftHandThumbFill: "#ffcc80ff",
    MainCharacterHeadBaseFill: "#f57c00ff",
    MainCharacterHeadFaceFill: "#e65100ff",
    MainCharacterNeckFill: "#ffb74dff",
    MainCharacterTorsoFill: "#FFA726ff",
    MainCharacterLegUpperFill: "#ffcc80ff",
    MainCharacterFootFill: "#ffcc80ff",
    MainCharacterLegLowerFill: "#f57c00ff",
    RocketExhaustCloudFill: "#0d47a1ff",
    SidekickCharacterLeftHandThumbFill: "#ffcc80ff",
    SidekickCharacterLeftHandPalmFill: "#ffb74dff",
    SidekickCharacterHeadBaseFill: "#FFA726ff",
    SidekickCharacterHeadFaceFill: "#e65100ff",
    SidekickCharacterRightHandPalmFill: "#ffb74dff",
    SidekickCharacterNeckFill: "#ffb74dff",
    SidekickCharacterTorsoFill: "#ffb74dff",
    SidekickCharacterLegUpperFill: "#FFA726ff",
    SidekickCharacterFootFill: "#FFA726ff",
    SidekickCharacterLegLowerFill: "#f57c00ff",
    RocketWindowLeftFill: "#0d47a1ff",
    RocketWindowLeftFrameFill: "#2196F3ff",
    RocketWindowRightFill: "#0d47a1ff",
    RocketWindowRightFrameFill: "#2196F3ff",
    RocketWindowBottomFill: "#0d47a1ff",
    RocketWindowBottomFrameFill: "#2196F3ff",
    RocketNoseConeFill: "#1976d2ff",
    RocketFinBottomFill: "#1e88e5ff",
    RocketFinLeftFill: "#1e88e5ff",
    RocketExhaustOuterFlameFill: "#64b5f6ff",
    RocketExhaustInnerFlameFill: "#2196F3ff",
    SparkleTopRightFill: "#90caf9ff",
    SparkleTopRightLateFill: "#90caf9ff",
    SparkleTopCenterFill: "#90caf9ff",
    SparkleFarRightFill: "#2196F3ff",
    SparkleFarLeftFill: "#2196F3ff",
    SparkleTopLeftFill: "#1976d2ff",
    SparkleBottomLeftFill: "#1976d2ff",
    SparkleBottomCenterFill: "#1976d2ff",
    SparkleBottomRightFill: "#64b5f6ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete dual-tone dark theme using orange (primary) for characters and blue (secondary) for rocket and effects. Optimized for dark backgrounds with rich colors and maintained contrast.",
  },
}

export const improveddualtonecolororangeLightTheme: LottieThemeConfig = {
  themeId: "ImprovedDualToneColor-orange-light",
  name: "Orange Light",
  description:
    "Improved dual-tone orange+blue light theme with complementary colors for enhanced visual appeal. Orange (#FF9800 from MUI) for characters, blue (#4285f4 from MUI) for rocket and effects.",
  baseColor: "orange",
  mode: "light",
  colors: {
    MainCharacterRightHandPalmFill: "#FF9800ff",
    MainCharacterRightHandThumbFill: "#ffb74dff",
    MainCharacterLeftHandPalmFill: "#FF9800ff",
    MainCharacterLeftHandThumbFill: "#ffb74dff",
    MainCharacterHeadBaseFill: "#e65100ff",
    MainCharacterHeadFaceFill: "#ffe5ccff",
    MainCharacterNeckFill: "#ffa726ff",
    MainCharacterTorsoFill: "#FF9800ff",
    MainCharacterLegUpperFill: "#ffb74dff",
    MainCharacterFootFill: "#ffb74dff",
    MainCharacterLegLowerFill: "#e65100ff",
    RocketExhaustCloudFill: "#e3f2fdff",
    SidekickCharacterLeftHandThumbFill: "#ffb74dff",
    SidekickCharacterLeftHandPalmFill: "#ffa726ff",
    SidekickCharacterHeadBaseFill: "#FF9800ff",
    SidekickCharacterHeadFaceFill: "#ffe5ccff",
    SidekickCharacterRightHandPalmFill: "#ffa726ff",
    SidekickCharacterNeckFill: "#ffa726ff",
    SidekickCharacterTorsoFill: "#ffa726ff",
    SidekickCharacterLegUpperFill: "#FF9800ff",
    SidekickCharacterFootFill: "#FF9800ff",
    SidekickCharacterLegLowerFill: "#e65100ff",
    RocketWindowLeftFill: "#e3f2fdff",
    RocketWindowLeftFrameFill: "#4285f4ff",
    RocketWindowRightFill: "#e3f2fdff",
    RocketWindowRightFrameFill: "#4285f4ff",
    RocketWindowBottomFill: "#e3f2fdff",
    RocketWindowBottomFrameFill: "#4285f4ff",
    RocketNoseConeFill: "#1565c0ff",
    RocketFinBottomFill: "#1976d2ff",
    RocketFinLeftFill: "#1976d2ff",
    RocketExhaustOuterFlameFill: "#90caf9ff",
    RocketExhaustInnerFlameFill: "#4285f4ff",
    SparkleTopRightFill: "#bbdefbff",
    SparkleTopRightLateFill: "#bbdefbff",
    SparkleTopCenterFill: "#bbdefbff",
    SparkleFarRightFill: "#4285f4ff",
    SparkleFarLeftFill: "#4285f4ff",
    SparkleTopLeftFill: "#1565c0ff",
    SparkleBottomLeftFill: "#1565c0ff",
    SparkleBottomCenterFill: "#1565c0ff",
    SparkleBottomRightFill: "#90caf9ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete dual-tone theme using orange (primary) for characters and blue (secondary) for rocket and effects. Orange provides warmth while blue creates cool complementary contrast. Character faces use light orange, rocket/window highlights use light blue. All elements themed for full dual-tone visual cohesion.",
  },
}

export const improveddualtonecolorpurpleDarkTheme: LottieThemeConfig = {
  themeId: "ImprovedDualToneColor-purple-dark",
  name: "Purple Dark",
  description:
    "Improved dual-tone purple+orange dark theme with complementary colors for enhanced visual appeal. Purple (#a15bca from MUI dark) for characters, orange (#FFA726 from MUI dark) for rocket and effects.",
  baseColor: "purple",
  mode: "dark",
  colors: {
    MainCharacterRightHandPalmFill: "#a15bcaff",
    MainCharacterRightHandThumbFill: "#ce93d8ff",
    MainCharacterLeftHandPalmFill: "#a15bcaff",
    MainCharacterLeftHandThumbFill: "#ce93d8ff",
    MainCharacterHeadBaseFill: "#7b1fa2ff",
    MainCharacterHeadFaceFill: "#4a148cff",
    MainCharacterNeckFill: "#ba68c8ff",
    MainCharacterTorsoFill: "#a15bcaff",
    MainCharacterLegUpperFill: "#ce93d8ff",
    MainCharacterFootFill: "#ce93d8ff",
    MainCharacterLegLowerFill: "#7b1fa2ff",
    RocketExhaustCloudFill: "#e65100ff",
    SidekickCharacterLeftHandThumbFill: "#ce93d8ff",
    SidekickCharacterLeftHandPalmFill: "#ba68c8ff",
    SidekickCharacterHeadBaseFill: "#a15bcaff",
    SidekickCharacterHeadFaceFill: "#4a148cff",
    SidekickCharacterRightHandPalmFill: "#ba68c8ff",
    SidekickCharacterNeckFill: "#ba68c8ff",
    SidekickCharacterTorsoFill: "#ba68c8ff",
    SidekickCharacterLegUpperFill: "#a15bcaff",
    SidekickCharacterFootFill: "#a15bcaff",
    SidekickCharacterLegLowerFill: "#7b1fa2ff",
    RocketWindowLeftFill: "#e65100ff",
    RocketWindowLeftFrameFill: "#FFA726ff",
    RocketWindowRightFill: "#e65100ff",
    RocketWindowRightFrameFill: "#FFA726ff",
    RocketWindowBottomFill: "#e65100ff",
    RocketWindowBottomFrameFill: "#FFA726ff",
    RocketNoseConeFill: "#f57c00ff",
    RocketFinBottomFill: "#fb8c00ff",
    RocketFinLeftFill: "#fb8c00ff",
    RocketExhaustOuterFlameFill: "#ffcc80ff",
    RocketExhaustInnerFlameFill: "#FFA726ff",
    SparkleTopRightFill: "#ffe0b2ff",
    SparkleTopRightLateFill: "#ffe0b2ff",
    SparkleTopCenterFill: "#ffe0b2ff",
    SparkleFarRightFill: "#FFA726ff",
    SparkleFarLeftFill: "#FFA726ff",
    SparkleTopLeftFill: "#f57c00ff",
    SparkleBottomLeftFill: "#f57c00ff",
    SparkleBottomCenterFill: "#f57c00ff",
    SparkleBottomRightFill: "#ffcc80ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete dual-tone dark theme using purple (primary) for characters and orange (secondary) for rocket and effects. Optimized for dark backgrounds with rich colors and maintained contrast.",
  },
}

export const improveddualtonecolorpurpleLightTheme: LottieThemeConfig = {
  themeId: "ImprovedDualToneColor-purple-light",
  name: "Purple Light",
  description:
    "Improved dual-tone purple+orange light theme with complementary colors for enhanced visual appeal. Purple (#621890 from MUI) for characters, orange (#FF9800 from MUI) for rocket and effects.",
  baseColor: "purple",
  mode: "light",
  colors: {
    MainCharacterRightHandPalmFill: "#621890ff",
    MainCharacterRightHandThumbFill: "#a662d0ff",
    MainCharacterLeftHandPalmFill: "#621890ff",
    MainCharacterLeftHandThumbFill: "#a662d0ff",
    MainCharacterHeadBaseFill: "#3e105cff",
    MainCharacterHeadFaceFill: "#e8d4f5ff",
    MainCharacterNeckFill: "#7d3fb3ff",
    MainCharacterTorsoFill: "#621890ff",
    MainCharacterLegUpperFill: "#a662d0ff",
    MainCharacterFootFill: "#a662d0ff",
    MainCharacterLegLowerFill: "#3e105cff",
    RocketExhaustCloudFill: "#fff8f0ff",
    SidekickCharacterLeftHandThumbFill: "#a662d0ff",
    SidekickCharacterLeftHandPalmFill: "#7d3fb3ff",
    SidekickCharacterHeadBaseFill: "#621890ff",
    SidekickCharacterHeadFaceFill: "#e8d4f5ff",
    SidekickCharacterRightHandPalmFill: "#7d3fb3ff",
    SidekickCharacterNeckFill: "#7d3fb3ff",
    SidekickCharacterTorsoFill: "#7d3fb3ff",
    SidekickCharacterLegUpperFill: "#621890ff",
    SidekickCharacterFootFill: "#621890ff",
    SidekickCharacterLegLowerFill: "#3e105cff",
    RocketWindowLeftFill: "#fff8f0ff",
    RocketWindowLeftFrameFill: "#FF9800ff",
    RocketWindowRightFill: "#fff8f0ff",
    RocketWindowRightFrameFill: "#FF9800ff",
    RocketWindowBottomFill: "#fff8f0ff",
    RocketWindowBottomFrameFill: "#FF9800ff",
    RocketNoseConeFill: "#E65100ff",
    RocketFinBottomFill: "#F57C00ff",
    RocketFinLeftFill: "#F57C00ff",
    RocketExhaustOuterFlameFill: "#FFB74Dff",
    RocketExhaustInnerFlameFill: "#FF9800ff",
    SparkleTopRightFill: "#ffe4c4ff",
    SparkleTopRightLateFill: "#ffe4c4ff",
    SparkleTopCenterFill: "#ffe4c4ff",
    SparkleFarRightFill: "#FF9800ff",
    SparkleFarLeftFill: "#FF9800ff",
    SparkleTopLeftFill: "#E65100ff",
    SparkleBottomLeftFill: "#E65100ff",
    SparkleBottomCenterFill: "#E65100ff",
    SparkleBottomRightFill: "#FFB74Dff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete dual-tone theme using purple (primary) for characters and orange (secondary) for rocket and effects. Purple provides the main visual identity while orange creates exciting complementary contrast. Character faces use light purple (#E1BEE7ff), rocket/window highlights use light orange (#FFE0B2ff, #FFF3E0ff). All elements themed for full dual-tone visual cohesion.",
  },
}

export const improveddualtonecolorredDarkTheme: LottieThemeConfig = {
  themeId: "ImprovedDualToneColor-red-dark",
  name: "Red Dark",
  description:
    "Improved dual-tone red+teal dark theme with complementary colors for enhanced visual appeal. Red (#be3030 from MUI dark) for characters, teal (#26A69A from MUI dark) for rocket and effects.",
  baseColor: "red",
  mode: "dark",
  colors: {
    MainCharacterRightHandPalmFill: "#be3030ff",
    MainCharacterRightHandThumbFill: "#ef5350ff",
    MainCharacterLeftHandPalmFill: "#be3030ff",
    MainCharacterLeftHandThumbFill: "#ef5350ff",
    MainCharacterHeadBaseFill: "#c62828ff",
    MainCharacterHeadFaceFill: "#8b2424ff",
    MainCharacterNeckFill: "#e57373ff",
    MainCharacterTorsoFill: "#be3030ff",
    MainCharacterLegUpperFill: "#ef5350ff",
    MainCharacterFootFill: "#ef5350ff",
    MainCharacterLegLowerFill: "#c62828ff",
    RocketExhaustCloudFill: "#00695cff",
    SidekickCharacterLeftHandThumbFill: "#ef5350ff",
    SidekickCharacterLeftHandPalmFill: "#e57373ff",
    SidekickCharacterHeadBaseFill: "#be3030ff",
    SidekickCharacterHeadFaceFill: "#8b2424ff",
    SidekickCharacterRightHandPalmFill: "#e57373ff",
    SidekickCharacterNeckFill: "#e57373ff",
    SidekickCharacterTorsoFill: "#e57373ff",
    SidekickCharacterLegUpperFill: "#be3030ff",
    SidekickCharacterFootFill: "#be3030ff",
    SidekickCharacterLegLowerFill: "#c62828ff",
    RocketWindowLeftFill: "#00695cff",
    RocketWindowLeftFrameFill: "#26A69Aff",
    RocketWindowRightFill: "#00695cff",
    RocketWindowRightFrameFill: "#26A69Aff",
    RocketWindowBottomFill: "#00695cff",
    RocketWindowBottomFrameFill: "#26A69Aff",
    RocketNoseConeFill: "#00897bff",
    RocketFinBottomFill: "#00acc1ff",
    RocketFinLeftFill: "#00acc1ff",
    RocketExhaustOuterFlameFill: "#80cbc4ff",
    RocketExhaustInnerFlameFill: "#26A69Aff",
    SparkleTopRightFill: "#b2dfdbff",
    SparkleTopRightLateFill: "#b2dfdbff",
    SparkleTopCenterFill: "#b2dfdbff",
    SparkleFarRightFill: "#26A69Aff",
    SparkleFarLeftFill: "#26A69Aff",
    SparkleTopLeftFill: "#00897bff",
    SparkleBottomLeftFill: "#00897bff",
    SparkleBottomCenterFill: "#00897bff",
    SparkleBottomRightFill: "#80cbc4ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete dual-tone dark theme using red (primary) for characters and teal (secondary) for rocket and effects. Optimized for dark backgrounds with rich colors and maintained contrast.",
  },
}

export const improveddualtonecolorredLightTheme: LottieThemeConfig = {
  themeId: "ImprovedDualToneColor-red-light",
  name: "Red Light",
  description:
    "Improved dual-tone red+teal light theme with complementary colors for enhanced visual appeal. Red (#be3030 from MUI) for characters, teal (#00796B from MUI) for rocket and effects.",
  baseColor: "red",
  mode: "light",
  colors: {
    MainCharacterRightHandPalmFill: "#be3030ff",
    MainCharacterRightHandThumbFill: "#d66f6fff",
    MainCharacterLeftHandPalmFill: "#be3030ff",
    MainCharacterLeftHandThumbFill: "#d66f6fff",
    MainCharacterHeadBaseFill: "#8b2424ff",
    MainCharacterHeadFaceFill: "#f5d9d9ff",
    MainCharacterNeckFill: "#c94a4aff",
    MainCharacterTorsoFill: "#be3030ff",
    MainCharacterLegUpperFill: "#d66f6fff",
    MainCharacterFootFill: "#d66f6fff",
    MainCharacterLegLowerFill: "#8b2424ff",
    RocketExhaustCloudFill: "#e0f2f1ff",
    SidekickCharacterLeftHandThumbFill: "#d66f6fff",
    SidekickCharacterLeftHandPalmFill: "#c94a4aff",
    SidekickCharacterHeadBaseFill: "#be3030ff",
    SidekickCharacterHeadFaceFill: "#f5d9d9ff",
    SidekickCharacterRightHandPalmFill: "#c94a4aff",
    SidekickCharacterNeckFill: "#c94a4aff",
    SidekickCharacterTorsoFill: "#c94a4aff",
    SidekickCharacterLegUpperFill: "#be3030ff",
    SidekickCharacterFootFill: "#be3030ff",
    SidekickCharacterLegLowerFill: "#8b2424ff",
    RocketWindowLeftFill: "#e0f2f1ff",
    RocketWindowLeftFrameFill: "#00796Bff",
    RocketWindowRightFill: "#e0f2f1ff",
    RocketWindowRightFrameFill: "#00796Bff",
    RocketWindowBottomFill: "#e0f2f1ff",
    RocketWindowBottomFrameFill: "#00796Bff",
    RocketNoseConeFill: "#004d40ff",
    RocketFinBottomFill: "#00695cff",
    RocketFinLeftFill: "#00695cff",
    RocketExhaustOuterFlameFill: "#80cbc4ff",
    RocketExhaustInnerFlameFill: "#00796Bff",
    SparkleTopRightFill: "#b2dfdbff",
    SparkleTopRightLateFill: "#b2dfdbff",
    SparkleTopCenterFill: "#b2dfdbff",
    SparkleFarRightFill: "#00796Bff",
    SparkleFarLeftFill: "#00796Bff",
    SparkleTopLeftFill: "#004d40ff",
    SparkleBottomLeftFill: "#004d40ff",
    SparkleBottomCenterFill: "#004d40ff",
    SparkleBottomRightFill: "#80cbc4ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete dual-tone theme using red (primary) for characters and teal (secondary) for rocket and effects. Red provides energy while teal creates calming complementary contrast. Character faces use light red, rocket/window highlights use light teal. All elements themed for full dual-tone visual cohesion.",
  },
}

export const improveddualtonecolortealDarkTheme: LottieThemeConfig = {
  themeId: "ImprovedDualToneColor-teal-dark",
  name: "Teal Dark",
  description:
    "Improved dual-tone teal+pink dark theme with complementary colors for enhanced visual appeal. Teal (#26A69A from MUI dark) for characters, pink (#EC407A from MUI dark) for rocket and effects.",
  baseColor: "teal",
  mode: "dark",
  colors: {
    MainCharacterRightHandPalmFill: "#26A69Aff",
    MainCharacterRightHandThumbFill: "#80cbc4ff",
    MainCharacterLeftHandPalmFill: "#26A69Aff",
    MainCharacterLeftHandThumbFill: "#80cbc4ff",
    MainCharacterHeadBaseFill: "#00897bff",
    MainCharacterHeadFaceFill: "#00695cff",
    MainCharacterNeckFill: "#4db6acff",
    MainCharacterTorsoFill: "#26A69Aff",
    MainCharacterLegUpperFill: "#80cbc4ff",
    MainCharacterFootFill: "#80cbc4ff",
    MainCharacterLegLowerFill: "#00897bff",
    RocketExhaustCloudFill: "#ad1457ff",
    SidekickCharacterLeftHandThumbFill: "#80cbc4ff",
    SidekickCharacterLeftHandPalmFill: "#4db6acff",
    SidekickCharacterHeadBaseFill: "#26A69Aff",
    SidekickCharacterHeadFaceFill: "#00695cff",
    SidekickCharacterRightHandPalmFill: "#4db6acff",
    SidekickCharacterNeckFill: "#4db6acff",
    SidekickCharacterTorsoFill: "#4db6acff",
    SidekickCharacterLegUpperFill: "#26A69Aff",
    SidekickCharacterFootFill: "#26A69Aff",
    SidekickCharacterLegLowerFill: "#00897bff",
    RocketWindowLeftFill: "#ad1457ff",
    RocketWindowLeftFrameFill: "#EC407Aff",
    RocketWindowRightFill: "#ad1457ff",
    RocketWindowRightFrameFill: "#EC407Aff",
    RocketWindowBottomFill: "#ad1457ff",
    RocketWindowBottomFrameFill: "#EC407Aff",
    RocketNoseConeFill: "#c2185bff",
    RocketFinBottomFill: "#d81b60ff",
    RocketFinLeftFill: "#d81b60ff",
    RocketExhaustOuterFlameFill: "#f48fb1ff",
    RocketExhaustInnerFlameFill: "#EC407Aff",
    SparkleTopRightFill: "#f8bbd0ff",
    SparkleTopRightLateFill: "#f8bbd0ff",
    SparkleTopCenterFill: "#f8bbd0ff",
    SparkleFarRightFill: "#EC407Aff",
    SparkleFarLeftFill: "#EC407Aff",
    SparkleTopLeftFill: "#c2185bff",
    SparkleBottomLeftFill: "#c2185bff",
    SparkleBottomCenterFill: "#c2185bff",
    SparkleBottomRightFill: "#f48fb1ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete dual-tone dark theme using teal (primary) for characters and pink (secondary) for rocket and effects. Optimized for dark backgrounds with rich colors and maintained contrast.",
  },
}

export const improveddualtonecolortealLightTheme: LottieThemeConfig = {
  themeId: "ImprovedDualToneColor-teal-light",
  name: "Teal Light",
  description:
    "Improved dual-tone teal+pink light theme with complementary colors for enhanced visual appeal. Teal (#00796B from MUI) for characters, pink (#C2185B from MUI) for rocket and effects.",
  baseColor: "teal",
  mode: "light",
  colors: {
    MainCharacterRightHandPalmFill: "#00796Bff",
    MainCharacterRightHandThumbFill: "#4db6acff",
    MainCharacterLeftHandPalmFill: "#00796Bff",
    MainCharacterLeftHandThumbFill: "#4db6acff",
    MainCharacterHeadBaseFill: "#004d40ff",
    MainCharacterHeadFaceFill: "#d5f0edff",
    MainCharacterNeckFill: "#26a69aff",
    MainCharacterTorsoFill: "#00796Bff",
    MainCharacterLegUpperFill: "#4db6acff",
    MainCharacterFootFill: "#4db6acff",
    MainCharacterLegLowerFill: "#004d40ff",
    RocketExhaustCloudFill: "#fce4ecff",
    SidekickCharacterLeftHandThumbFill: "#4db6acff",
    SidekickCharacterLeftHandPalmFill: "#26a69aff",
    SidekickCharacterHeadBaseFill: "#00796Bff",
    SidekickCharacterHeadFaceFill: "#d5f0edff",
    SidekickCharacterRightHandPalmFill: "#26a69aff",
    SidekickCharacterNeckFill: "#26a69aff",
    SidekickCharacterTorsoFill: "#26a69aff",
    SidekickCharacterLegUpperFill: "#00796Bff",
    SidekickCharacterFootFill: "#00796Bff",
    SidekickCharacterLegLowerFill: "#004d40ff",
    RocketWindowLeftFill: "#fce4ecff",
    RocketWindowLeftFrameFill: "#C2185Bff",
    RocketWindowRightFill: "#fce4ecff",
    RocketWindowRightFrameFill: "#C2185Bff",
    RocketWindowBottomFill: "#fce4ecff",
    RocketWindowBottomFrameFill: "#C2185Bff",
    RocketNoseConeFill: "#880e4fff",
    RocketFinBottomFill: "#ad1457ff",
    RocketFinLeftFill: "#ad1457ff",
    RocketExhaustOuterFlameFill: "#f48fb1ff",
    RocketExhaustInnerFlameFill: "#C2185Bff",
    SparkleTopRightFill: "#f8bbd0ff",
    SparkleTopRightLateFill: "#f8bbd0ff",
    SparkleTopCenterFill: "#f8bbd0ff",
    SparkleFarRightFill: "#C2185Bff",
    SparkleFarLeftFill: "#C2185Bff",
    SparkleTopLeftFill: "#880e4fff",
    SparkleBottomLeftFill: "#880e4fff",
    SparkleBottomCenterFill: "#880e4fff",
    SparkleBottomRightFill: "#f48fb1ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete dual-tone theme using teal (primary) for characters and pink (secondary) for rocket and effects. Teal provides calm sophistication while pink creates vibrant complementary contrast. Character faces use light teal, rocket/window highlights use light pink. All elements themed for full dual-tone visual cohesion.",
  },
}

export const improvedmonochromecoloringblueDarkTheme: LottieThemeConfig = {
  themeId: "ImprovedMonochromeColoring-blue-dark",
  name: "Blue Dark",
  description:
    "Improved monochrome blue dark theme with enhanced contrast for RocketLaunch animation. Uses varying shades of blue (#2196F3 from MUI dark palette) optimized for dark backgrounds.",
  baseColor: "blue",
  mode: "dark",
  colors: {
    MainCharacterRightHandPalmFill: "#2196F3ff",
    MainCharacterRightHandThumbFill: "#64b5f6ff",
    MainCharacterLeftHandPalmFill: "#2196F3ff",
    MainCharacterLeftHandThumbFill: "#64b5f6ff",
    MainCharacterHeadBaseFill: "#1976d2ff",
    MainCharacterHeadFaceFill: "#0d47a1ff",
    MainCharacterNeckFill: "#42a5f5ff",
    MainCharacterTorsoFill: "#2196F3ff",
    MainCharacterLegUpperFill: "#64b5f6ff",
    MainCharacterFootFill: "#64b5f6ff",
    MainCharacterLegLowerFill: "#1976d2ff",
    RocketExhaustCloudFill: "#0d47a1ff",
    SidekickCharacterLeftHandThumbFill: "#64b5f6ff",
    SidekickCharacterLeftHandPalmFill: "#42a5f5ff",
    SidekickCharacterHeadBaseFill: "#2196F3ff",
    SidekickCharacterHeadFaceFill: "#0d47a1ff",
    SidekickCharacterRightHandPalmFill: "#42a5f5ff",
    SidekickCharacterNeckFill: "#42a5f5ff",
    SidekickCharacterTorsoFill: "#42a5f5ff",
    SidekickCharacterLegUpperFill: "#2196F3ff",
    SidekickCharacterFootFill: "#2196F3ff",
    SidekickCharacterLegLowerFill: "#1976d2ff",
    RocketWindowLeftFill: "#0d47a1ff",
    RocketWindowLeftFrameFill: "#42a5f5ff",
    RocketWindowRightFill: "#0d47a1ff",
    RocketWindowRightFrameFill: "#42a5f5ff",
    RocketWindowBottomFill: "#0d47a1ff",
    RocketWindowBottomFrameFill: "#42a5f5ff",
    RocketNoseConeFill: "#1976d2ff",
    RocketFinBottomFill: "#1e88e5ff",
    RocketFinLeftFill: "#1e88e5ff",
    RocketExhaustOuterFlameFill: "#90caf9ff",
    RocketExhaustInnerFlameFill: "#2196F3ff",
    SparkleTopRightFill: "#0d47a1ff",
    SparkleTopRightLateFill: "#0d47a1ff",
    SparkleTopCenterFill: "#0d47a1ff",
    SparkleFarRightFill: "#2196F3ff",
    SparkleFarLeftFill: "#2196F3ff",
    SparkleTopLeftFill: "#1976d2ff",
    SparkleBottomLeftFill: "#1976d2ff",
    SparkleBottomCenterFill: "#1976d2ff",
    SparkleBottomRightFill: "#64b5f6ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete monochrome blue dark theme with enhanced contrast for dark backgrounds. Richer blue tones for main elements, deeper shades for structural elements, and very dark blues for highlights and glass elements. Optimized for #263237 background.",
  },
}

export const improvedmonochromecoloringblueLightTheme: LottieThemeConfig = {
  themeId: "ImprovedMonochromeColoring-blue-light",
  name: "Blue Light",
  description:
    "Improved monochrome blue light theme with enhanced contrast for RocketLaunch animation. Uses varying shades of blue (#4285f4 from MUI palette) to create depth and visual hierarchy across all elements.",
  baseColor: "blue",
  mode: "light",
  colors: {
    MainCharacterRightHandPalmFill: "#4285f4ff",
    MainCharacterRightHandThumbFill: "#80b3f8ff",
    MainCharacterLeftHandPalmFill: "#4285f4ff",
    MainCharacterLeftHandThumbFill: "#80b3f8ff",
    MainCharacterHeadBaseFill: "#1a5dc7ff",
    MainCharacterHeadFaceFill: "#d4e3fcff",
    MainCharacterNeckFill: "#5a9af6ff",
    MainCharacterTorsoFill: "#4285f4ff",
    MainCharacterLegUpperFill: "#80b3f8ff",
    MainCharacterFootFill: "#80b3f8ff",
    MainCharacterLegLowerFill: "#1a5dc7ff",
    RocketExhaustCloudFill: "#eff5feff",
    SidekickCharacterLeftHandThumbFill: "#80b3f8ff",
    SidekickCharacterLeftHandPalmFill: "#5a9af6ff",
    SidekickCharacterHeadBaseFill: "#4285f4ff",
    SidekickCharacterHeadFaceFill: "#d4e3fcff",
    SidekickCharacterRightHandPalmFill: "#5a9af6ff",
    SidekickCharacterNeckFill: "#5a9af6ff",
    SidekickCharacterTorsoFill: "#5a9af6ff",
    SidekickCharacterLegUpperFill: "#4285f4ff",
    SidekickCharacterFootFill: "#4285f4ff",
    SidekickCharacterLegLowerFill: "#1a5dc7ff",
    RocketWindowLeftFill: "#eff5feff",
    RocketWindowLeftFrameFill: "#5a9af6ff",
    RocketWindowRightFill: "#eff5feff",
    RocketWindowRightFrameFill: "#5a9af6ff",
    RocketWindowBottomFill: "#eff5feff",
    RocketWindowBottomFrameFill: "#5a9af6ff",
    RocketNoseConeFill: "#1a5dc7ff",
    RocketFinBottomFill: "#2e6fe3ff",
    RocketFinLeftFill: "#2e6fe3ff",
    RocketExhaustOuterFlameFill: "#a3c9faff",
    RocketExhaustInnerFlameFill: "#4285f4ff",
    SparkleTopRightFill: "#d4e3fcff",
    SparkleTopRightLateFill: "#d4e3fcff",
    SparkleTopCenterFill: "#d4e3fcff",
    SparkleFarRightFill: "#4285f4ff",
    SparkleFarLeftFill: "#4285f4ff",
    SparkleTopLeftFill: "#1a5dc7ff",
    SparkleBottomLeftFill: "#1a5dc7ff",
    SparkleBottomCenterFill: "#1a5dc7ff",
    SparkleBottomRightFill: "#80b3f8ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete monochrome blue theme with enhanced contrast. Darker blues for structural elements and shadows, mid-range blues for main character elements, lighter blues for highlights and effects, and very light blues for face details, windows, and cloud effects. All elements themed for full monochrome visual cohesion.",
  },
}

export const improvedmonochromecoloringgreenDarkTheme: LottieThemeConfig = {
  themeId: "ImprovedMonochromeColoring-green-dark",
  name: "Green Dark",
  description:
    "Improved monochrome green dark theme with enhanced contrast for RocketLaunch animation. Uses varying shades of green (#66BB6A from MUI dark palette) optimized for dark backgrounds.",
  baseColor: "green",
  mode: "dark",
  colors: {
    MainCharacterRightHandPalmFill: "#66BB6Aff",
    MainCharacterRightHandThumbFill: "#a5d6a7ff",
    MainCharacterLeftHandPalmFill: "#66BB6Aff",
    MainCharacterLeftHandThumbFill: "#a5d6a7ff",
    MainCharacterHeadBaseFill: "#43a047ff",
    MainCharacterHeadFaceFill: "#2e7d32ff",
    MainCharacterNeckFill: "#81c784ff",
    MainCharacterTorsoFill: "#66BB6Aff",
    MainCharacterLegUpperFill: "#a5d6a7ff",
    MainCharacterFootFill: "#a5d6a7ff",
    MainCharacterLegLowerFill: "#43a047ff",
    RocketExhaustCloudFill: "#2e7d32ff",
    SidekickCharacterLeftHandThumbFill: "#a5d6a7ff",
    SidekickCharacterLeftHandPalmFill: "#81c784ff",
    SidekickCharacterHeadBaseFill: "#66BB6Aff",
    SidekickCharacterHeadFaceFill: "#2e7d32ff",
    SidekickCharacterRightHandPalmFill: "#81c784ff",
    SidekickCharacterNeckFill: "#81c784ff",
    SidekickCharacterTorsoFill: "#81c784ff",
    SidekickCharacterLegUpperFill: "#66BB6Aff",
    SidekickCharacterFootFill: "#66BB6Aff",
    SidekickCharacterLegLowerFill: "#43a047ff",
    RocketWindowLeftFill: "#2e7d32ff",
    RocketWindowLeftFrameFill: "#81c784ff",
    RocketWindowRightFill: "#2e7d32ff",
    RocketWindowRightFrameFill: "#81c784ff",
    RocketWindowBottomFill: "#2e7d32ff",
    RocketWindowBottomFrameFill: "#81c784ff",
    RocketNoseConeFill: "#43a047ff",
    RocketFinBottomFill: "#4caf50ff",
    RocketFinLeftFill: "#4caf50ff",
    RocketExhaustOuterFlameFill: "#c5e1a5ff",
    RocketExhaustInnerFlameFill: "#66BB6Aff",
    SparkleTopRightFill: "#2e7d32ff",
    SparkleTopRightLateFill: "#2e7d32ff",
    SparkleTopCenterFill: "#2e7d32ff",
    SparkleFarRightFill: "#66BB6Aff",
    SparkleFarLeftFill: "#66BB6Aff",
    SparkleTopLeftFill: "#43a047ff",
    SparkleBottomLeftFill: "#43a047ff",
    SparkleBottomCenterFill: "#43a047ff",
    SparkleBottomRightFill: "#a5d6a7ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete monochrome green dark theme with enhanced contrast for dark backgrounds. Richer green tones for main elements, deeper shades for structural elements, and very dark greens for highlights and glass elements. Optimized for #263237 background.",
  },
}

export const improvedmonochromecoloringgreenLightTheme: LottieThemeConfig = {
  themeId: "ImprovedMonochromeColoring-green-light",
  name: "Green Light",
  description:
    "Improved monochrome green light theme with enhanced contrast for RocketLaunch animation. Uses varying shades of green (#4CAF50 from MUI palette) to create depth and visual hierarchy across all elements.",
  baseColor: "green",
  mode: "light",
  colors: {
    MainCharacterRightHandPalmFill: "#4CAF50ff",
    MainCharacterRightHandThumbFill: "#81c784ff",
    MainCharacterLeftHandPalmFill: "#4CAF50ff",
    MainCharacterLeftHandThumbFill: "#81c784ff",
    MainCharacterHeadBaseFill: "#2e7d32ff",
    MainCharacterHeadFaceFill: "#d7f3d8ff",
    MainCharacterNeckFill: "#66bb6aff",
    MainCharacterTorsoFill: "#4CAF50ff",
    MainCharacterLegUpperFill: "#81c784ff",
    MainCharacterFootFill: "#81c784ff",
    MainCharacterLegLowerFill: "#2e7d32ff",
    RocketExhaustCloudFill: "#f1f8f1ff",
    SidekickCharacterLeftHandThumbFill: "#81c784ff",
    SidekickCharacterLeftHandPalmFill: "#66bb6aff",
    SidekickCharacterHeadBaseFill: "#4CAF50ff",
    SidekickCharacterHeadFaceFill: "#d7f3d8ff",
    SidekickCharacterRightHandPalmFill: "#66bb6aff",
    SidekickCharacterNeckFill: "#66bb6aff",
    SidekickCharacterTorsoFill: "#66bb6aff",
    SidekickCharacterLegUpperFill: "#4CAF50ff",
    SidekickCharacterFootFill: "#4CAF50ff",
    SidekickCharacterLegLowerFill: "#2e7d32ff",
    RocketWindowLeftFill: "#f1f8f1ff",
    RocketWindowLeftFrameFill: "#66bb6aff",
    RocketWindowRightFill: "#f1f8f1ff",
    RocketWindowRightFrameFill: "#66bb6aff",
    RocketWindowBottomFill: "#f1f8f1ff",
    RocketWindowBottomFrameFill: "#66bb6aff",
    RocketNoseConeFill: "#2e7d32ff",
    RocketFinBottomFill: "#388e3cff",
    RocketFinLeftFill: "#388e3cff",
    RocketExhaustOuterFlameFill: "#a5d6a7ff",
    RocketExhaustInnerFlameFill: "#4CAF50ff",
    SparkleTopRightFill: "#d7f3d8ff",
    SparkleTopRightLateFill: "#d7f3d8ff",
    SparkleTopCenterFill: "#d7f3d8ff",
    SparkleFarRightFill: "#4CAF50ff",
    SparkleFarLeftFill: "#4CAF50ff",
    SparkleTopLeftFill: "#2e7d32ff",
    SparkleBottomLeftFill: "#2e7d32ff",
    SparkleBottomCenterFill: "#2e7d32ff",
    SparkleBottomRightFill: "#81c784ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete monochrome green theme with enhanced contrast. Darker greens for structural elements and shadows, mid-range greens for main character elements, lighter greens for highlights and effects, and very light greens for face details, windows, and cloud effects. All elements themed for full monochrome visual cohesion.",
  },
}

export const improvedmonochromecoloringorangeDarkTheme: LottieThemeConfig = {
  themeId: "ImprovedMonochromeColoring-orange-dark",
  name: "Orange Dark",
  description:
    "Improved monochrome orange dark theme with enhanced contrast for RocketLaunch animation. Uses varying shades of orange (#FFA726 from MUI dark palette) optimized for dark backgrounds.",
  baseColor: "orange",
  mode: "dark",
  colors: {
    MainCharacterRightHandPalmFill: "#FFA726ff",
    MainCharacterRightHandThumbFill: "#ffcc80ff",
    MainCharacterLeftHandPalmFill: "#FFA726ff",
    MainCharacterLeftHandThumbFill: "#ffcc80ff",
    MainCharacterHeadBaseFill: "#f57c00ff",
    MainCharacterHeadFaceFill: "#e65100ff",
    MainCharacterNeckFill: "#ffb74dff",
    MainCharacterTorsoFill: "#FFA726ff",
    MainCharacterLegUpperFill: "#ffcc80ff",
    MainCharacterFootFill: "#ffcc80ff",
    MainCharacterLegLowerFill: "#f57c00ff",
    RocketExhaustCloudFill: "#e65100ff",
    SidekickCharacterLeftHandThumbFill: "#ffcc80ff",
    SidekickCharacterLeftHandPalmFill: "#ffb74dff",
    SidekickCharacterHeadBaseFill: "#FFA726ff",
    SidekickCharacterHeadFaceFill: "#e65100ff",
    SidekickCharacterRightHandPalmFill: "#ffb74dff",
    SidekickCharacterNeckFill: "#ffb74dff",
    SidekickCharacterTorsoFill: "#ffb74dff",
    SidekickCharacterLegUpperFill: "#FFA726ff",
    SidekickCharacterFootFill: "#FFA726ff",
    SidekickCharacterLegLowerFill: "#f57c00ff",
    RocketWindowLeftFill: "#e65100ff",
    RocketWindowLeftFrameFill: "#ffb74dff",
    RocketWindowRightFill: "#e65100ff",
    RocketWindowRightFrameFill: "#ffb74dff",
    RocketWindowBottomFill: "#e65100ff",
    RocketWindowBottomFrameFill: "#ffb74dff",
    RocketNoseConeFill: "#f57c00ff",
    RocketFinBottomFill: "#fb8c00ff",
    RocketFinLeftFill: "#fb8c00ff",
    RocketExhaustOuterFlameFill: "#ffe0b2ff",
    RocketExhaustInnerFlameFill: "#FFA726ff",
    SparkleTopRightFill: "#e65100ff",
    SparkleTopRightLateFill: "#e65100ff",
    SparkleTopCenterFill: "#e65100ff",
    SparkleFarRightFill: "#FFA726ff",
    SparkleFarLeftFill: "#FFA726ff",
    SparkleTopLeftFill: "#f57c00ff",
    SparkleBottomLeftFill: "#f57c00ff",
    SparkleBottomCenterFill: "#f57c00ff",
    SparkleBottomRightFill: "#ffcc80ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete monochrome orange dark theme with enhanced contrast for dark backgrounds. Richer orange tones for main elements, deeper shades for structural elements, and very dark oranges for highlights and glass elements. Optimized for #263237 background.",
  },
}

export const improvedmonochromecoloringorangeLightTheme: LottieThemeConfig = {
  themeId: "ImprovedMonochromeColoring-orange-light",
  name: "Orange Light",
  description:
    "Improved monochrome orange light theme with enhanced contrast for RocketLaunch animation. Uses varying shades of orange (#FF9800 from MUI palette) to create depth and visual hierarchy across all elements.",
  baseColor: "orange",
  mode: "light",
  colors: {
    MainCharacterRightHandPalmFill: "#FF9800ff",
    MainCharacterRightHandThumbFill: "#ffb74dff",
    MainCharacterLeftHandPalmFill: "#FF9800ff",
    MainCharacterLeftHandThumbFill: "#ffb74dff",
    MainCharacterHeadBaseFill: "#e65100ff",
    MainCharacterHeadFaceFill: "#ffe5ccff",
    MainCharacterNeckFill: "#ffa726ff",
    MainCharacterTorsoFill: "#FF9800ff",
    MainCharacterLegUpperFill: "#ffb74dff",
    MainCharacterFootFill: "#ffb74dff",
    MainCharacterLegLowerFill: "#e65100ff",
    RocketExhaustCloudFill: "#fff8f0ff",
    SidekickCharacterLeftHandThumbFill: "#ffb74dff",
    SidekickCharacterLeftHandPalmFill: "#ffa726ff",
    SidekickCharacterHeadBaseFill: "#FF9800ff",
    SidekickCharacterHeadFaceFill: "#ffe5ccff",
    SidekickCharacterRightHandPalmFill: "#ffa726ff",
    SidekickCharacterNeckFill: "#ffa726ff",
    SidekickCharacterTorsoFill: "#ffa726ff",
    SidekickCharacterLegUpperFill: "#FF9800ff",
    SidekickCharacterFootFill: "#FF9800ff",
    SidekickCharacterLegLowerFill: "#e65100ff",
    RocketWindowLeftFill: "#fff8f0ff",
    RocketWindowLeftFrameFill: "#ffa726ff",
    RocketWindowRightFill: "#fff8f0ff",
    RocketWindowRightFrameFill: "#ffa726ff",
    RocketWindowBottomFill: "#fff8f0ff",
    RocketWindowBottomFrameFill: "#ffa726ff",
    RocketNoseConeFill: "#e65100ff",
    RocketFinBottomFill: "#f57c00ff",
    RocketFinLeftFill: "#f57c00ff",
    RocketExhaustOuterFlameFill: "#ffcc80ff",
    RocketExhaustInnerFlameFill: "#FF9800ff",
    SparkleTopRightFill: "#ffe5ccff",
    SparkleTopRightLateFill: "#ffe5ccff",
    SparkleTopCenterFill: "#ffe5ccff",
    SparkleFarRightFill: "#FF9800ff",
    SparkleFarLeftFill: "#FF9800ff",
    SparkleTopLeftFill: "#e65100ff",
    SparkleBottomLeftFill: "#e65100ff",
    SparkleBottomCenterFill: "#e65100ff",
    SparkleBottomRightFill: "#ffb74dff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete monochrome orange theme with enhanced contrast. Darker oranges for structural elements and shadows, mid-range oranges for main character elements, lighter oranges for highlights and effects, and very light oranges for face details, windows, and cloud effects. All elements themed for full monochrome visual cohesion.",
  },
}

export const improvedmonochromecoloringpurpleDarkTheme: LottieThemeConfig = {
  themeId: "ImprovedMonochromeColoring-purple-dark",
  name: "Purple Dark",
  description:
    "Improved monochrome purple dark theme with enhanced contrast for RocketLaunch animation. Uses varying shades of purple (#a15bca from MUI dark palette) optimized for dark backgrounds.",
  baseColor: "purple",
  mode: "dark",
  colors: {
    MainCharacterRightHandPalmFill: "#a15bcaff",
    MainCharacterRightHandThumbFill: "#ce93d8ff",
    MainCharacterLeftHandPalmFill: "#a15bcaff",
    MainCharacterLeftHandThumbFill: "#ce93d8ff",
    MainCharacterHeadBaseFill: "#7b1fa2ff",
    MainCharacterHeadFaceFill: "#4a148cff",
    MainCharacterNeckFill: "#ba68c8ff",
    MainCharacterTorsoFill: "#a15bcaff",
    MainCharacterLegUpperFill: "#ce93d8ff",
    MainCharacterFootFill: "#ce93d8ff",
    MainCharacterLegLowerFill: "#7b1fa2ff",
    RocketExhaustCloudFill: "#4a148cff",
    SidekickCharacterLeftHandThumbFill: "#ce93d8ff",
    SidekickCharacterLeftHandPalmFill: "#ba68c8ff",
    SidekickCharacterHeadBaseFill: "#a15bcaff",
    SidekickCharacterHeadFaceFill: "#4a148cff",
    SidekickCharacterRightHandPalmFill: "#ba68c8ff",
    SidekickCharacterNeckFill: "#ba68c8ff",
    SidekickCharacterTorsoFill: "#ba68c8ff",
    SidekickCharacterLegUpperFill: "#a15bcaff",
    SidekickCharacterFootFill: "#a15bcaff",
    SidekickCharacterLegLowerFill: "#7b1fa2ff",
    RocketWindowLeftFill: "#4a148cff",
    RocketWindowLeftFrameFill: "#ba68c8ff",
    RocketWindowRightFill: "#4a148cff",
    RocketWindowRightFrameFill: "#ba68c8ff",
    RocketWindowBottomFill: "#4a148cff",
    RocketWindowBottomFrameFill: "#ba68c8ff",
    RocketNoseConeFill: "#7b1fa2ff",
    RocketFinBottomFill: "#8e24aaff",
    RocketFinLeftFill: "#8e24aaff",
    RocketExhaustOuterFlameFill: "#e1bee7ff",
    RocketExhaustInnerFlameFill: "#a15bcaff",
    SparkleTopRightFill: "#4a148cff",
    SparkleTopRightLateFill: "#4a148cff",
    SparkleTopCenterFill: "#4a148cff",
    SparkleFarRightFill: "#a15bcaff",
    SparkleFarLeftFill: "#a15bcaff",
    SparkleTopLeftFill: "#7b1fa2ff",
    SparkleBottomLeftFill: "#7b1fa2ff",
    SparkleBottomCenterFill: "#7b1fa2ff",
    SparkleBottomRightFill: "#ce93d8ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete monochrome purple dark theme with enhanced contrast for dark backgrounds. Richer purple tones for main elements, deeper shades for structural elements, and very dark purples for highlights and glass elements. Optimized for #263237 background.",
  },
}

export const improvedmonochromecoloringpurpleLightTheme: LottieThemeConfig = {
  themeId: "ImprovedMonochromeColoring-purple-light",
  name: "Purple Light",
  description:
    "Improved monochrome purple light theme with enhanced contrast for RocketLaunch animation. Uses varying shades of purple (#621890 from MUI palette) to create depth and visual hierarchy across all elements.",
  baseColor: "purple",
  mode: "light",
  colors: {
    MainCharacterRightHandPalmFill: "#621890ff",
    MainCharacterRightHandThumbFill: "#a662d0ff",
    MainCharacterLeftHandPalmFill: "#621890ff",
    MainCharacterLeftHandThumbFill: "#a662d0ff",
    MainCharacterHeadBaseFill: "#3e105cff",
    MainCharacterHeadFaceFill: "#e8d4f5ff",
    MainCharacterNeckFill: "#7d3fb3ff",
    MainCharacterTorsoFill: "#621890ff",
    MainCharacterLegUpperFill: "#a662d0ff",
    MainCharacterFootFill: "#a662d0ff",
    MainCharacterLegLowerFill: "#3e105cff",
    RocketExhaustCloudFill: "#f5edf9ff",
    SidekickCharacterLeftHandThumbFill: "#a662d0ff",
    SidekickCharacterLeftHandPalmFill: "#7d3fb3ff",
    SidekickCharacterHeadBaseFill: "#621890ff",
    SidekickCharacterHeadFaceFill: "#e8d4f5ff",
    SidekickCharacterRightHandPalmFill: "#7d3fb3ff",
    SidekickCharacterNeckFill: "#7d3fb3ff",
    SidekickCharacterTorsoFill: "#7d3fb3ff",
    SidekickCharacterLegUpperFill: "#621890ff",
    SidekickCharacterFootFill: "#621890ff",
    SidekickCharacterLegLowerFill: "#3e105cff",
    RocketWindowLeftFill: "#f5edf9ff",
    RocketWindowLeftFrameFill: "#7d3fb3ff",
    RocketWindowRightFill: "#f5edf9ff",
    RocketWindowRightFrameFill: "#7d3fb3ff",
    RocketWindowBottomFill: "#f5edf9ff",
    RocketWindowBottomFrameFill: "#7d3fb3ff",
    RocketNoseConeFill: "#3e105cff",
    RocketFinBottomFill: "#502973ff",
    RocketFinLeftFill: "#502973ff",
    RocketExhaustOuterFlameFill: "#c99be3ff",
    RocketExhaustInnerFlameFill: "#621890ff",
    SparkleTopRightFill: "#e8d4f5ff",
    SparkleTopRightLateFill: "#e8d4f5ff",
    SparkleTopCenterFill: "#e8d4f5ff",
    SparkleFarRightFill: "#621890ff",
    SparkleFarLeftFill: "#621890ff",
    SparkleTopLeftFill: "#3e105cff",
    SparkleBottomLeftFill: "#3e105cff",
    SparkleBottomCenterFill: "#3e105cff",
    SparkleBottomRightFill: "#a662d0ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete monochrome purple theme with enhanced contrast. Darker purples (#6A1B9A, #7B1FA2) for structural elements and shadows, mid-range purples (#9C27B0, #AB47BC) for main character elements, lighter purples (#BA68C8, #CE93D8) for highlights and effects, and very light purples (#E1BEE7, #F3E5F5) for face details, windows, and cloud effects. All elements themed for full monochrome visual cohesion.",
  },
}

export const improvedmonochromecoloringredDarkTheme: LottieThemeConfig = {
  themeId: "ImprovedMonochromeColoring-red-dark",
  name: "Red Dark",
  description:
    "Improved monochrome red dark theme with enhanced contrast for RocketLaunch animation. Uses varying shades of red (#be3030 from MUI dark palette) optimized for dark backgrounds.",
  baseColor: "red",
  mode: "dark",
  colors: {
    MainCharacterRightHandPalmFill: "#be3030ff",
    MainCharacterRightHandThumbFill: "#ef5350ff",
    MainCharacterLeftHandPalmFill: "#be3030ff",
    MainCharacterLeftHandThumbFill: "#ef5350ff",
    MainCharacterHeadBaseFill: "#c62828ff",
    MainCharacterHeadFaceFill: "#8b2424ff",
    MainCharacterNeckFill: "#e57373ff",
    MainCharacterTorsoFill: "#be3030ff",
    MainCharacterLegUpperFill: "#ef5350ff",
    MainCharacterFootFill: "#ef5350ff",
    MainCharacterLegLowerFill: "#c62828ff",
    RocketExhaustCloudFill: "#8b2424ff",
    SidekickCharacterLeftHandThumbFill: "#ef5350ff",
    SidekickCharacterLeftHandPalmFill: "#e57373ff",
    SidekickCharacterHeadBaseFill: "#be3030ff",
    SidekickCharacterHeadFaceFill: "#8b2424ff",
    SidekickCharacterRightHandPalmFill: "#e57373ff",
    SidekickCharacterNeckFill: "#e57373ff",
    SidekickCharacterTorsoFill: "#e57373ff",
    SidekickCharacterLegUpperFill: "#be3030ff",
    SidekickCharacterFootFill: "#be3030ff",
    SidekickCharacterLegLowerFill: "#c62828ff",
    RocketWindowLeftFill: "#8b2424ff",
    RocketWindowLeftFrameFill: "#e57373ff",
    RocketWindowRightFill: "#8b2424ff",
    RocketWindowRightFrameFill: "#e57373ff",
    RocketWindowBottomFill: "#8b2424ff",
    RocketWindowBottomFrameFill: "#e57373ff",
    RocketNoseConeFill: "#c62828ff",
    RocketFinBottomFill: "#d32f2fff",
    RocketFinLeftFill: "#d32f2fff",
    RocketExhaustOuterFlameFill: "#ffcdd2ff",
    RocketExhaustInnerFlameFill: "#be3030ff",
    SparkleTopRightFill: "#8b2424ff",
    SparkleTopRightLateFill: "#8b2424ff",
    SparkleTopCenterFill: "#8b2424ff",
    SparkleFarRightFill: "#be3030ff",
    SparkleFarLeftFill: "#be3030ff",
    SparkleTopLeftFill: "#c62828ff",
    SparkleBottomLeftFill: "#c62828ff",
    SparkleBottomCenterFill: "#c62828ff",
    SparkleBottomRightFill: "#ef5350ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete monochrome red dark theme with enhanced contrast for dark backgrounds. Richer red tones for main elements, deeper shades for structural elements, and very dark reds for highlights and glass elements. Optimized for #263237 background.",
  },
}

export const improvedmonochromecoloringredLightTheme: LottieThemeConfig = {
  themeId: "ImprovedMonochromeColoring-red-light",
  name: "Red Light",
  description:
    "Improved monochrome red light theme with enhanced contrast for RocketLaunch animation. Uses varying shades of red (#be3030 from MUI palette) to create depth and visual hierarchy across all elements.",
  baseColor: "red",
  mode: "light",
  colors: {
    MainCharacterRightHandPalmFill: "#be3030ff",
    MainCharacterRightHandThumbFill: "#d66f6fff",
    MainCharacterLeftHandPalmFill: "#be3030ff",
    MainCharacterLeftHandThumbFill: "#d66f6fff",
    MainCharacterHeadBaseFill: "#8b2424ff",
    MainCharacterHeadFaceFill: "#f5d9d9ff",
    MainCharacterNeckFill: "#c94a4aff",
    MainCharacterTorsoFill: "#be3030ff",
    MainCharacterLegUpperFill: "#d66f6fff",
    MainCharacterFootFill: "#d66f6fff",
    MainCharacterLegLowerFill: "#8b2424ff",
    RocketExhaustCloudFill: "#fef5f5ff",
    SidekickCharacterLeftHandThumbFill: "#d66f6fff",
    SidekickCharacterLeftHandPalmFill: "#c94a4aff",
    SidekickCharacterHeadBaseFill: "#be3030ff",
    SidekickCharacterHeadFaceFill: "#f5d9d9ff",
    SidekickCharacterRightHandPalmFill: "#c94a4aff",
    SidekickCharacterNeckFill: "#c94a4aff",
    SidekickCharacterTorsoFill: "#c94a4aff",
    SidekickCharacterLegUpperFill: "#be3030ff",
    SidekickCharacterFootFill: "#be3030ff",
    SidekickCharacterLegLowerFill: "#8b2424ff",
    RocketWindowLeftFill: "#fef5f5ff",
    RocketWindowLeftFrameFill: "#c94a4aff",
    RocketWindowRightFill: "#fef5f5ff",
    RocketWindowRightFrameFill: "#c94a4aff",
    RocketWindowBottomFill: "#fef5f5ff",
    RocketWindowBottomFrameFill: "#c94a4aff",
    RocketNoseConeFill: "#8b2424ff",
    RocketFinBottomFill: "#a32a2aff",
    RocketFinLeftFill: "#a32a2aff",
    RocketExhaustOuterFlameFill: "#e29d9dff",
    RocketExhaustInnerFlameFill: "#be3030ff",
    SparkleTopRightFill: "#f5d9d9ff",
    SparkleTopRightLateFill: "#f5d9d9ff",
    SparkleTopCenterFill: "#f5d9d9ff",
    SparkleFarRightFill: "#be3030ff",
    SparkleFarLeftFill: "#be3030ff",
    SparkleTopLeftFill: "#8b2424ff",
    SparkleBottomLeftFill: "#8b2424ff",
    SparkleBottomCenterFill: "#8b2424ff",
    SparkleBottomRightFill: "#d66f6fff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete monochrome red theme with enhanced contrast. Darker reds for structural elements and shadows, mid-range reds for main character elements, lighter reds for highlights and effects, and very light reds for face details, windows, and cloud effects. All elements themed for full monochrome visual cohesion.",
  },
}

export const improvedmonochromecoloringtealDarkTheme: LottieThemeConfig = {
  themeId: "ImprovedMonochromeColoring-teal-dark",
  name: "Teal Dark",
  description:
    "Improved monochrome teal dark theme with enhanced contrast for RocketLaunch animation. Uses varying shades of teal (#26A69A from MUI dark palette) optimized for dark backgrounds.",
  baseColor: "teal",
  mode: "dark",
  colors: {
    MainCharacterRightHandPalmFill: "#26A69Aff",
    MainCharacterRightHandThumbFill: "#80cbc4ff",
    MainCharacterLeftHandPalmFill: "#26A69Aff",
    MainCharacterLeftHandThumbFill: "#80cbc4ff",
    MainCharacterHeadBaseFill: "#00897bff",
    MainCharacterHeadFaceFill: "#00695cff",
    MainCharacterNeckFill: "#4db6acff",
    MainCharacterTorsoFill: "#26A69Aff",
    MainCharacterLegUpperFill: "#80cbc4ff",
    MainCharacterFootFill: "#80cbc4ff",
    MainCharacterLegLowerFill: "#00897bff",
    RocketExhaustCloudFill: "#00695cff",
    SidekickCharacterLeftHandThumbFill: "#80cbc4ff",
    SidekickCharacterLeftHandPalmFill: "#4db6acff",
    SidekickCharacterHeadBaseFill: "#26A69Aff",
    SidekickCharacterHeadFaceFill: "#00695cff",
    SidekickCharacterRightHandPalmFill: "#4db6acff",
    SidekickCharacterNeckFill: "#4db6acff",
    SidekickCharacterTorsoFill: "#4db6acff",
    SidekickCharacterLegUpperFill: "#26A69Aff",
    SidekickCharacterFootFill: "#26A69Aff",
    SidekickCharacterLegLowerFill: "#00897bff",
    RocketWindowLeftFill: "#00695cff",
    RocketWindowLeftFrameFill: "#4db6acff",
    RocketWindowRightFill: "#00695cff",
    RocketWindowRightFrameFill: "#4db6acff",
    RocketWindowBottomFill: "#00695cff",
    RocketWindowBottomFrameFill: "#4db6acff",
    RocketNoseConeFill: "#00897bff",
    RocketFinBottomFill: "#00acc1ff",
    RocketFinLeftFill: "#00acc1ff",
    RocketExhaustOuterFlameFill: "#b2dfdbff",
    RocketExhaustInnerFlameFill: "#26A69Aff",
    SparkleTopRightFill: "#00695cff",
    SparkleTopRightLateFill: "#00695cff",
    SparkleTopCenterFill: "#00695cff",
    SparkleFarRightFill: "#26A69Aff",
    SparkleFarLeftFill: "#26A69Aff",
    SparkleTopLeftFill: "#00897bff",
    SparkleBottomLeftFill: "#00897bff",
    SparkleBottomCenterFill: "#00897bff",
    SparkleBottomRightFill: "#80cbc4ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete monochrome teal dark theme with enhanced contrast for dark backgrounds. Richer teal tones for main elements, deeper shades for structural elements, and very dark teals for highlights and glass elements. Optimized for #263237 background.",
  },
}

export const improvedmonochromecoloringtealLightTheme: LottieThemeConfig = {
  themeId: "ImprovedMonochromeColoring-teal-light",
  name: "Teal Light",
  description:
    "Improved monochrome teal light theme with enhanced contrast for RocketLaunch animation. Uses varying shades of teal (#00796B from MUI palette) to create depth and visual hierarchy across all elements.",
  baseColor: "teal",
  mode: "light",
  colors: {
    MainCharacterRightHandPalmFill: "#00796Bff",
    MainCharacterRightHandThumbFill: "#4db6acff",
    MainCharacterLeftHandPalmFill: "#00796Bff",
    MainCharacterLeftHandThumbFill: "#4db6acff",
    MainCharacterHeadBaseFill: "#004d40ff",
    MainCharacterHeadFaceFill: "#d5f0edff",
    MainCharacterNeckFill: "#26a69aff",
    MainCharacterTorsoFill: "#00796Bff",
    MainCharacterLegUpperFill: "#4db6acff",
    MainCharacterFootFill: "#4db6acff",
    MainCharacterLegLowerFill: "#004d40ff",
    RocketExhaustCloudFill: "#f0f9f8ff",
    SidekickCharacterLeftHandThumbFill: "#4db6acff",
    SidekickCharacterLeftHandPalmFill: "#26a69aff",
    SidekickCharacterHeadBaseFill: "#00796Bff",
    SidekickCharacterHeadFaceFill: "#d5f0edff",
    SidekickCharacterRightHandPalmFill: "#26a69aff",
    SidekickCharacterNeckFill: "#26a69aff",
    SidekickCharacterTorsoFill: "#26a69aff",
    SidekickCharacterLegUpperFill: "#00796Bff",
    SidekickCharacterFootFill: "#00796Bff",
    SidekickCharacterLegLowerFill: "#004d40ff",
    RocketWindowLeftFill: "#f0f9f8ff",
    RocketWindowLeftFrameFill: "#26a69aff",
    RocketWindowRightFill: "#f0f9f8ff",
    RocketWindowRightFrameFill: "#26a69aff",
    RocketWindowBottomFill: "#f0f9f8ff",
    RocketWindowBottomFrameFill: "#26a69aff",
    RocketNoseConeFill: "#004d40ff",
    RocketFinBottomFill: "#00695cff",
    RocketFinLeftFill: "#00695cff",
    RocketExhaustOuterFlameFill: "#80cbc4ff",
    RocketExhaustInnerFlameFill: "#00796Bff",
    SparkleTopRightFill: "#d5f0edff",
    SparkleTopRightLateFill: "#d5f0edff",
    SparkleTopCenterFill: "#d5f0edff",
    SparkleFarRightFill: "#00796Bff",
    SparkleFarLeftFill: "#00796Bff",
    SparkleTopLeftFill: "#004d40ff",
    SparkleBottomLeftFill: "#004d40ff",
    SparkleBottomCenterFill: "#004d40ff",
    SparkleBottomRightFill: "#4db6acff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Complete monochrome teal theme with enhanced contrast. Darker teals for structural elements and shadows, mid-range teals for main character elements, lighter teals for highlights and effects, and very light teals for face details, windows, and cloud effects. All elements themed for full monochrome visual cohesion.",
  },
}

export const defaultblueDarkTheme: LottieThemeConfig = {
  themeId: "default-blue-dark",
  name: "Blue Dark",
  description:
    "Default blue dark theme that preserves the original red animation's visual style and patterns. A faithful color replacement maintaining the same brightness relationships, optimized for dark backgrounds.",
  baseColor: "blue",
  mode: "dark",
  colors: {
    MainCharacterRightHandPalmFill: "#2196F3ff",
    MainCharacterRightHandThumbFill: "#64b5f6ff",
    MainCharacterLeftHandPalmFill: "#2196F3ff",
    MainCharacterLeftHandThumbFill: "#64b5f6ff",
    MainCharacterHeadBaseFill: "#1976d2ff",
    MainCharacterHeadFaceFill: "#64b5f6ff",
    MainCharacterNeckFill: "#42a5f5ff",
    MainCharacterTorsoFill: "#2196F3ff",
    MainCharacterLegUpperFill: "#5aaef8ff",
    MainCharacterFootFill: "#5aaef8ff",
    MainCharacterLegLowerFill: "#1565c0ff",
    RocketExhaustCloudFill: "#0d47a1ff",
    SidekickCharacterLeftHandThumbFill: "#64b5f6ff",
    SidekickCharacterLeftHandPalmFill: "#5aaef8ff",
    SidekickCharacterHeadBaseFill: "#2196F3ff",
    SidekickCharacterHeadFaceFill: "#64b5f6ff",
    SidekickCharacterRightHandPalmFill: "#5aaef8ff",
    SidekickCharacterNeckFill: "#42a5f5ff",
    SidekickCharacterTorsoFill: "#5aaef8ff",
    SidekickCharacterLegUpperFill: "#2196F3ff",
    SidekickCharacterFootFill: "#2196F3ff",
    SidekickCharacterLegLowerFill: "#1e88e5ff",
    RocketWindowLeftFill: "#0d47a1ff",
    RocketWindowLeftFrameFill: "#5aaef8ff",
    RocketWindowRightFill: "#0d47a1ff",
    RocketWindowRightFrameFill: "#5aaef8ff",
    RocketWindowBottomFill: "#0d47a1ff",
    RocketWindowBottomFrameFill: "#5aaef8ff",
    RocketNoseConeFill: "#1976d2ff",
    RocketFinBottomFill: "#1e88e5ff",
    RocketFinLeftFill: "#1e88e5ff",
    RocketExhaustOuterFlameFill: "#5aaef8ff",
    RocketExhaustInnerFlameFill: "#1976d2ff",
    SparkleTopRightFill: "#90caf9ff",
    SparkleTopRightLateFill: "#90caf9ff",
    SparkleTopCenterFill: "#90caf9ff",
    SparkleFarRightFill: "#1e88e5ff",
    SparkleFarLeftFill: "#1e88e5ff",
    SparkleTopLeftFill: "#1976d2ff",
    SparkleBottomLeftFill: "#1976d2ff",
    SparkleBottomCenterFill: "#1976d2ff",
    SparkleBottomRightFill: "#5aaef8ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Faithful recreation of the original red animation in blue for dark mode. Preserves the same relative brightness patterns but with richer tones suitable for dark backgrounds.",
  },
}

export const defaultblueLightTheme: LottieThemeConfig = {
  themeId: "default-blue-light",
  name: "Blue Light",
  description:
    "Default blue light theme that preserves the original red animation's visual style and patterns. A faithful color replacement maintaining the same brightness relationships as the original.",
  baseColor: "blue",
  mode: "light",
  colors: {
    MainCharacterRightHandPalmFill: "#5a9cf6ff",
    MainCharacterRightHandThumbFill: "#8fb9f9ff",
    MainCharacterLeftHandPalmFill: "#5a9cf6ff",
    MainCharacterLeftHandThumbFill: "#8fb9f9ff",
    MainCharacterHeadBaseFill: "#2b6fe5ff",
    MainCharacterHeadFaceFill: "#8fb9f9ff",
    MainCharacterNeckFill: "#73abf7ff",
    MainCharacterTorsoFill: "#5a9cf6ff",
    MainCharacterLegUpperFill: "#7fb3f8ff",
    MainCharacterFootFill: "#7fb3f8ff",
    MainCharacterLegLowerFill: "#1565c0ff",
    RocketExhaustCloudFill: "#f5f9feff",
    SidekickCharacterLeftHandThumbFill: "#8fb9f9ff",
    SidekickCharacterLeftHandPalmFill: "#7fb3f8ff",
    SidekickCharacterHeadBaseFill: "#5a9cf6ff",
    SidekickCharacterHeadFaceFill: "#8fb9f9ff",
    SidekickCharacterRightHandPalmFill: "#7fb3f8ff",
    SidekickCharacterNeckFill: "#73abf7ff",
    SidekickCharacterTorsoFill: "#7fb3f8ff",
    SidekickCharacterLegUpperFill: "#5a9cf6ff",
    SidekickCharacterFootFill: "#5a9cf6ff",
    SidekickCharacterLegLowerFill: "#2561d6ff",
    RocketWindowLeftFill: "#e3f2fdff",
    RocketWindowLeftFrameFill: "#7fb3f8ff",
    RocketWindowRightFill: "#e3f2fdff",
    RocketWindowRightFrameFill: "#7fb3f8ff",
    RocketWindowBottomFill: "#e3f2fdff",
    RocketWindowBottomFrameFill: "#7fb3f8ff",
    RocketNoseConeFill: "#1e5dc7ff",
    RocketFinBottomFill: "#3479e8ff",
    RocketFinLeftFill: "#3479e8ff",
    RocketExhaustOuterFlameFill: "#7fb3f8ff",
    RocketExhaustInnerFlameFill: "#2b6fe5ff",
    SparkleTopRightFill: "#aaccfaff",
    SparkleTopRightLateFill: "#aaccfaff",
    SparkleTopCenterFill: "#aaccfaff",
    SparkleFarRightFill: "#2561d6ff",
    SparkleFarLeftFill: "#2561d6ff",
    SparkleTopLeftFill: "#2b6fe5ff",
    SparkleBottomLeftFill: "#2b6fe5ff",
    SparkleBottomCenterFill: "#2b6fe5ff",
    SparkleBottomRightFill: "#7fb3f8ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Faithful recreation of the original red animation in blue. Preserves the same relative lightness and brightness patterns - where the original had dark red, this has dark blue; where it had light red, this has light blue. White elements remain white. The goal is to maintain the exact visual feel of the original, just in a different hue.",
  },
}

export const defaultgreenDarkTheme: LottieThemeConfig = {
  themeId: "default-green-dark",
  name: "Green Dark",
  description:
    "Default green dark theme that preserves the original red animation's visual style and patterns. A faithful color replacement maintaining the same brightness relationships, optimized for dark backgrounds.",
  baseColor: "green",
  mode: "dark",
  colors: {
    MainCharacterRightHandPalmFill: "#66BB6Aff",
    MainCharacterRightHandThumbFill: "#a5d6a7ff",
    MainCharacterLeftHandPalmFill: "#66BB6Aff",
    MainCharacterLeftHandThumbFill: "#a5d6a7ff",
    MainCharacterHeadBaseFill: "#43a047ff",
    MainCharacterHeadFaceFill: "#a5d6a7ff",
    MainCharacterNeckFill: "#81c784ff",
    MainCharacterTorsoFill: "#66BB6Aff",
    MainCharacterLegUpperFill: "#93d396ff",
    MainCharacterFootFill: "#93d396ff",
    MainCharacterLegLowerFill: "#2e7d32ff",
    RocketExhaustCloudFill: "#1b5e20ff",
    SidekickCharacterLeftHandThumbFill: "#a5d6a7ff",
    SidekickCharacterLeftHandPalmFill: "#93d396ff",
    SidekickCharacterHeadBaseFill: "#66BB6Aff",
    SidekickCharacterHeadFaceFill: "#a5d6a7ff",
    SidekickCharacterRightHandPalmFill: "#93d396ff",
    SidekickCharacterNeckFill: "#81c784ff",
    SidekickCharacterTorsoFill: "#93d396ff",
    SidekickCharacterLegUpperFill: "#66BB6Aff",
    SidekickCharacterFootFill: "#66BB6Aff",
    SidekickCharacterLegLowerFill: "#43a047ff",
    RocketWindowLeftFill: "#1b5e20ff",
    RocketWindowLeftFrameFill: "#93d396ff",
    RocketWindowRightFill: "#1b5e20ff",
    RocketWindowRightFrameFill: "#93d396ff",
    RocketWindowBottomFill: "#1b5e20ff",
    RocketWindowBottomFrameFill: "#93d396ff",
    RocketNoseConeFill: "#388e3cff",
    RocketFinBottomFill: "#4caf50ff",
    RocketFinLeftFill: "#4caf50ff",
    RocketExhaustOuterFlameFill: "#93d396ff",
    RocketExhaustInnerFlameFill: "#43a047ff",
    SparkleTopRightFill: "#c8e6c9ff",
    SparkleTopRightLateFill: "#c8e6c9ff",
    SparkleTopCenterFill: "#c8e6c9ff",
    SparkleFarRightFill: "#43a047ff",
    SparkleFarLeftFill: "#43a047ff",
    SparkleTopLeftFill: "#43a047ff",
    SparkleBottomLeftFill: "#43a047ff",
    SparkleBottomCenterFill: "#43a047ff",
    SparkleBottomRightFill: "#93d396ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Faithful recreation of the original red animation in green for dark mode. Preserves the same relative brightness patterns but with richer tones suitable for dark backgrounds.",
  },
}

export const defaultgreenLightTheme: LottieThemeConfig = {
  themeId: "default-green-light",
  name: "Green Light",
  description:
    "Default green light theme that preserves the original red animation's visual style and patterns. A faithful color replacement maintaining the same brightness relationships as the original.",
  baseColor: "green",
  mode: "light",
  colors: {
    MainCharacterRightHandPalmFill: "#5caf5fff",
    MainCharacterRightHandThumbFill: "#8dc891ff",
    MainCharacterLeftHandPalmFill: "#5caf5fff",
    MainCharacterLeftHandThumbFill: "#8dc891ff",
    MainCharacterHeadBaseFill: "#2e8b30ff",
    MainCharacterHeadFaceFill: "#8dc891ff",
    MainCharacterNeckFill: "#73bb75ff",
    MainCharacterTorsoFill: "#5caf5fff",
    MainCharacterLegUpperFill: "#7ec280ff",
    MainCharacterFootFill: "#7ec280ff",
    MainCharacterLegLowerFill: "#1b5e20ff",
    RocketExhaustCloudFill: "#f5faf5ff",
    SidekickCharacterLeftHandThumbFill: "#8dc891ff",
    SidekickCharacterLeftHandPalmFill: "#7ec280ff",
    SidekickCharacterHeadBaseFill: "#5caf5fff",
    SidekickCharacterHeadFaceFill: "#8dc891ff",
    SidekickCharacterRightHandPalmFill: "#7ec280ff",
    SidekickCharacterNeckFill: "#73bb75ff",
    SidekickCharacterTorsoFill: "#7ec280ff",
    SidekickCharacterLegUpperFill: "#5caf5fff",
    SidekickCharacterFootFill: "#5caf5fff",
    SidekickCharacterLegLowerFill: "#2e7d32ff",
    RocketWindowLeftFill: "#e8f5e9ff",
    RocketWindowLeftFrameFill: "#7ec280ff",
    RocketWindowRightFill: "#e8f5e9ff",
    RocketWindowRightFrameFill: "#7ec280ff",
    RocketWindowBottomFill: "#e8f5e9ff",
    RocketWindowBottomFrameFill: "#7ec280ff",
    RocketNoseConeFill: "#27822aff",
    RocketFinBottomFill: "#388e3cff",
    RocketFinLeftFill: "#388e3cff",
    RocketExhaustOuterFlameFill: "#7ec280ff",
    RocketExhaustInnerFlameFill: "#2e8b30ff",
    SparkleTopRightFill: "#aeddb0ff",
    SparkleTopRightLateFill: "#aeddb0ff",
    SparkleTopCenterFill: "#aeddb0ff",
    SparkleFarRightFill: "#2e7d32ff",
    SparkleFarLeftFill: "#2e7d32ff",
    SparkleTopLeftFill: "#2e8b30ff",
    SparkleBottomLeftFill: "#2e8b30ff",
    SparkleBottomCenterFill: "#2e8b30ff",
    SparkleBottomRightFill: "#7ec280ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Faithful recreation of the original red animation in green. Preserves the same relative lightness and brightness patterns - where the original had dark red, this has dark green; where it had light red, this has light green. White elements remain white. The goal is to maintain the exact visual feel of the original, just in a different hue.",
  },
}

export const defaultorangeDarkTheme: LottieThemeConfig = {
  themeId: "default-orange-dark",
  name: "Orange Dark",
  description:
    "Default orange dark theme that preserves the original red animation's visual style and patterns. A faithful color replacement maintaining the same brightness relationships, optimized for dark backgrounds.",
  baseColor: "orange",
  mode: "dark",
  colors: {
    MainCharacterRightHandPalmFill: "#FFA726ff",
    MainCharacterRightHandThumbFill: "#ffcc80ff",
    MainCharacterLeftHandPalmFill: "#FFA726ff",
    MainCharacterLeftHandThumbFill: "#ffcc80ff",
    MainCharacterHeadBaseFill: "#f57c00ff",
    MainCharacterHeadFaceFill: "#ffcc80ff",
    MainCharacterNeckFill: "#ffb74dff",
    MainCharacterTorsoFill: "#FFA726ff",
    MainCharacterLegUpperFill: "#ffc165ff",
    MainCharacterFootFill: "#ffc165ff",
    MainCharacterLegLowerFill: "#e65100ff",
    RocketExhaustCloudFill: "#bf360cff",
    SidekickCharacterLeftHandThumbFill: "#ffcc80ff",
    SidekickCharacterLeftHandPalmFill: "#ffc165ff",
    SidekickCharacterHeadBaseFill: "#FFA726ff",
    SidekickCharacterHeadFaceFill: "#ffcc80ff",
    SidekickCharacterRightHandPalmFill: "#ffc165ff",
    SidekickCharacterNeckFill: "#ffb74dff",
    SidekickCharacterTorsoFill: "#ffc165ff",
    SidekickCharacterLegUpperFill: "#FFA726ff",
    SidekickCharacterFootFill: "#FFA726ff",
    SidekickCharacterLegLowerFill: "#fb8c00ff",
    RocketWindowLeftFill: "#bf360cff",
    RocketWindowLeftFrameFill: "#ffc165ff",
    RocketWindowRightFill: "#bf360cff",
    RocketWindowRightFrameFill: "#ffc165ff",
    RocketWindowBottomFill: "#bf360cff",
    RocketWindowBottomFrameFill: "#ffc165ff",
    RocketNoseConeFill: "#f57c00ff",
    RocketFinBottomFill: "#fb8c00ff",
    RocketFinLeftFill: "#fb8c00ff",
    RocketExhaustOuterFlameFill: "#ffc165ff",
    RocketExhaustInnerFlameFill: "#f57c00ff",
    SparkleTopRightFill: "#ffe0b2ff",
    SparkleTopRightLateFill: "#ffe0b2ff",
    SparkleTopCenterFill: "#ffe0b2ff",
    SparkleFarRightFill: "#fb8c00ff",
    SparkleFarLeftFill: "#fb8c00ff",
    SparkleTopLeftFill: "#f57c00ff",
    SparkleBottomLeftFill: "#f57c00ff",
    SparkleBottomCenterFill: "#f57c00ff",
    SparkleBottomRightFill: "#ffc165ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Faithful recreation of the original red animation in orange for dark mode. Preserves the same relative brightness patterns but with richer tones suitable for dark backgrounds.",
  },
}

export const defaultorangeLightTheme: LottieThemeConfig = {
  themeId: "default-orange-light",
  name: "Orange Light",
  description:
    "Default orange light theme that preserves the original red animation's visual style and patterns. A faithful color replacement maintaining the same brightness relationships as the original.",
  baseColor: "orange",
  mode: "light",
  colors: {
    MainCharacterRightHandPalmFill: "#ff9800ff",
    MainCharacterRightHandThumbFill: "#ffb74dff",
    MainCharacterLeftHandPalmFill: "#ff9800ff",
    MainCharacterLeftHandThumbFill: "#ffb74dff",
    MainCharacterHeadBaseFill: "#ef6c00ff",
    MainCharacterHeadFaceFill: "#ffb74dff",
    MainCharacterNeckFill: "#ffa726ff",
    MainCharacterTorsoFill: "#ff9800ff",
    MainCharacterLegUpperFill: "#ffb04dff",
    MainCharacterFootFill: "#ffb04dff",
    MainCharacterLegLowerFill: "#e65100ff",
    RocketExhaustCloudFill: "#fff8f0ff",
    SidekickCharacterLeftHandThumbFill: "#ffb74dff",
    SidekickCharacterLeftHandPalmFill: "#ffb04dff",
    SidekickCharacterHeadBaseFill: "#ff9800ff",
    SidekickCharacterHeadFaceFill: "#ffb74dff",
    SidekickCharacterRightHandPalmFill: "#ffb04dff",
    SidekickCharacterNeckFill: "#ffa726ff",
    SidekickCharacterTorsoFill: "#ffb04dff",
    SidekickCharacterLegUpperFill: "#ff9800ff",
    SidekickCharacterFootFill: "#ff9800ff",
    SidekickCharacterLegLowerFill: "#f57c00ff",
    RocketWindowLeftFill: "#fff3e0ff",
    RocketWindowLeftFrameFill: "#ffb04dff",
    RocketWindowRightFill: "#fff3e0ff",
    RocketWindowRightFrameFill: "#ffb04dff",
    RocketWindowBottomFill: "#fff3e0ff",
    RocketWindowBottomFrameFill: "#ffb04dff",
    RocketNoseConeFill: "#e86500ff",
    RocketFinBottomFill: "#f57c00ff",
    RocketFinLeftFill: "#f57c00ff",
    RocketExhaustOuterFlameFill: "#ffb04dff",
    RocketExhaustInnerFlameFill: "#ef6c00ff",
    SparkleTopRightFill: "#ffd699ff",
    SparkleTopRightLateFill: "#ffd699ff",
    SparkleTopCenterFill: "#ffd699ff",
    SparkleFarRightFill: "#f57c00ff",
    SparkleFarLeftFill: "#f57c00ff",
    SparkleTopLeftFill: "#ef6c00ff",
    SparkleBottomLeftFill: "#ef6c00ff",
    SparkleBottomCenterFill: "#ef6c00ff",
    SparkleBottomRightFill: "#ffb04dff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Faithful recreation of the original red animation in orange. Preserves the same relative lightness and brightness patterns - where the original had dark red, this has dark orange; where it had light red, this has light orange. White elements remain white. The goal is to maintain the exact visual feel of the original, just in a different hue.",
  },
}

export const defaultpurpleDarkTheme: LottieThemeConfig = {
  themeId: "default-purple-dark",
  name: "Purple Dark",
  description:
    "Default purple dark theme that preserves the original red animation's visual style and patterns. A faithful color replacement maintaining the same brightness relationships, optimized for dark backgrounds.",
  baseColor: "purple",
  mode: "dark",
  colors: {
    MainCharacterRightHandPalmFill: "#9b59b6ff",
    MainCharacterRightHandThumbFill: "#ba68c8ff",
    MainCharacterLeftHandPalmFill: "#9b59b6ff",
    MainCharacterLeftHandThumbFill: "#ba68c8ff",
    MainCharacterHeadBaseFill: "#7b1fa2ff",
    MainCharacterHeadFaceFill: "#ba68c8ff",
    MainCharacterNeckFill: "#ab47bcff",
    MainCharacterTorsoFill: "#9b59b6ff",
    MainCharacterLegUpperFill: "#b388c7ff",
    MainCharacterFootFill: "#b388c7ff",
    MainCharacterLegLowerFill: "#6a1b9aff",
    RocketExhaustCloudFill: "#4a148cff",
    SidekickCharacterLeftHandThumbFill: "#ba68c8ff",
    SidekickCharacterLeftHandPalmFill: "#b388c7ff",
    SidekickCharacterHeadBaseFill: "#9b59b6ff",
    SidekickCharacterHeadFaceFill: "#ba68c8ff",
    SidekickCharacterRightHandPalmFill: "#b388c7ff",
    SidekickCharacterNeckFill: "#ab47bcff",
    SidekickCharacterTorsoFill: "#b388c7ff",
    SidekickCharacterLegUpperFill: "#9b59b6ff",
    SidekickCharacterFootFill: "#9b59b6ff",
    SidekickCharacterLegLowerFill: "#8e24aaff",
    RocketWindowLeftFill: "#4a148cff",
    RocketWindowLeftFrameFill: "#b388c7ff",
    RocketWindowRightFill: "#4a148cff",
    RocketWindowRightFrameFill: "#b388c7ff",
    RocketWindowBottomFill: "#4a148cff",
    RocketWindowBottomFrameFill: "#b388c7ff",
    RocketNoseConeFill: "#7b1fa2ff",
    RocketFinBottomFill: "#8e24aaff",
    RocketFinLeftFill: "#8e24aaff",
    RocketExhaustOuterFlameFill: "#b388c7ff",
    RocketExhaustInnerFlameFill: "#7b1fa2ff",
    SparkleTopRightFill: "#ce93d8ff",
    SparkleTopRightLateFill: "#ce93d8ff",
    SparkleTopCenterFill: "#ce93d8ff",
    SparkleFarRightFill: "#8e24aaff",
    SparkleFarLeftFill: "#8e24aaff",
    SparkleTopLeftFill: "#7b1fa2ff",
    SparkleBottomLeftFill: "#7b1fa2ff",
    SparkleBottomCenterFill: "#7b1fa2ff",
    SparkleBottomRightFill: "#b388c7ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Faithful recreation of the original red animation in purple for dark mode. Preserves the same relative brightness patterns but with richer tones suitable for dark backgrounds.",
  },
}

export const defaultpurpleLightTheme: LottieThemeConfig = {
  themeId: "default-purple-light",
  name: "Purple Light",
  description:
    "Default purple light theme that preserves the original red animation's visual style and patterns. A faithful color replacement maintaining the same brightness relationships as the original.",
  baseColor: "purple",
  mode: "light",
  colors: {
    MainCharacterRightHandPalmFill: "#7b3fb3ff",
    MainCharacterRightHandThumbFill: "#a87cd6ff",
    MainCharacterLeftHandPalmFill: "#7b3fb3ff",
    MainCharacterLeftHandThumbFill: "#a87cd6ff",
    MainCharacterHeadBaseFill: "#531890ff",
    MainCharacterHeadFaceFill: "#a87cd6ff",
    MainCharacterNeckFill: "#8d54c0ff",
    MainCharacterTorsoFill: "#7b3fb3ff",
    MainCharacterLegUpperFill: "#9b69caff",
    MainCharacterFootFill: "#9b69caff",
    MainCharacterLegLowerFill: "#4a148cff",
    RocketExhaustCloudFill: "#f9f5fbff",
    SidekickCharacterLeftHandThumbFill: "#a87cd6ff",
    SidekickCharacterLeftHandPalmFill: "#9b69caff",
    SidekickCharacterHeadBaseFill: "#7b3fb3ff",
    SidekickCharacterHeadFaceFill: "#a87cd6ff",
    SidekickCharacterRightHandPalmFill: "#9b69caff",
    SidekickCharacterNeckFill: "#8d54c0ff",
    SidekickCharacterTorsoFill: "#9b69caff",
    SidekickCharacterLegUpperFill: "#7b3fb3ff",
    SidekickCharacterFootFill: "#7b3fb3ff",
    SidekickCharacterLegLowerFill: "#5e1fa3ff",
    RocketWindowLeftFill: "#f3e5f5ff",
    RocketWindowLeftFrameFill: "#9b69caff",
    RocketWindowRightFill: "#f3e5f5ff",
    RocketWindowRightFrameFill: "#9b69caff",
    RocketWindowBottomFill: "#f3e5f5ff",
    RocketWindowBottomFrameFill: "#9b69caff",
    RocketNoseConeFill: "#4d1787ff",
    RocketFinBottomFill: "#6a1b9aff",
    RocketFinLeftFill: "#6a1b9aff",
    RocketExhaustOuterFlameFill: "#9b69caff",
    RocketExhaustInnerFlameFill: "#531890ff",
    SparkleTopRightFill: "#c89edeff",
    SparkleTopRightLateFill: "#c89edeff",
    SparkleTopCenterFill: "#c89edeff",
    SparkleFarRightFill: "#5e1fa3ff",
    SparkleFarLeftFill: "#5e1fa3ff",
    SparkleTopLeftFill: "#531890ff",
    SparkleBottomLeftFill: "#531890ff",
    SparkleBottomCenterFill: "#531890ff",
    SparkleBottomRightFill: "#9b69caff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "Faithful recreation of the original red animation in purple. Preserves the same relative lightness and brightness patterns - where the original had dark red, this has dark purple; where it had light red, this has light purple. White elements remain white. The goal is to maintain the exact visual feel of the original, just in a different hue.",
  },
}

export const defaultredDarkTheme: LottieThemeConfig = {
  themeId: "default-red-dark",
  name: "Red Dark",
  description:
    "Default red dark theme that preserves the original red animation's visual style and patterns. Optimized for dark backgrounds while maintaining the original color relationships.",
  baseColor: "red",
  mode: "dark",
  colors: {
    MainCharacterRightHandPalmFill: "#ff4242ff",
    MainCharacterRightHandThumbFill: "#ff8585ff",
    MainCharacterLeftHandPalmFill: "#ff4242ff",
    MainCharacterLeftHandThumbFill: "#ff8585ff",
    MainCharacterHeadBaseFill: "#fe0606ff",
    MainCharacterHeadFaceFill: "#ff8585ff",
    MainCharacterNeckFill: "#ff6666ff",
    MainCharacterTorsoFill: "#ff4242ff",
    MainCharacterLegUpperFill: "#ff7575ff",
    MainCharacterFootFill: "#ff7575ff",
    MainCharacterLegLowerFill: "#be3030ff",
    RocketExhaustCloudFill: "#8b2424ff",
    SidekickCharacterLeftHandThumbFill: "#ff8585ff",
    SidekickCharacterLeftHandPalmFill: "#ff7575ff",
    SidekickCharacterHeadBaseFill: "#ff4242ff",
    SidekickCharacterHeadFaceFill: "#ff8585ff",
    SidekickCharacterRightHandPalmFill: "#ff7575ff",
    SidekickCharacterNeckFill: "#ff6666ff",
    SidekickCharacterTorsoFill: "#ff7575ff",
    SidekickCharacterLegUpperFill: "#ff4242ff",
    SidekickCharacterFootFill: "#ff4242ff",
    SidekickCharacterLegLowerFill: "#f32020ff",
    RocketWindowLeftFill: "#8b2424ff",
    RocketWindowLeftFrameFill: "#ff7575ff",
    RocketWindowRightFill: "#8b2424ff",
    RocketWindowRightFrameFill: "#ff7575ff",
    RocketWindowBottomFill: "#8b2424ff",
    RocketWindowBottomFrameFill: "#ff7575ff",
    RocketNoseConeFill: "#f32020ff",
    RocketFinBottomFill: "#dc3333ff",
    RocketFinLeftFill: "#dc3333ff",
    RocketExhaustOuterFlameFill: "#ff7575ff",
    RocketExhaustInnerFlameFill: "#fe0606ff",
    SparkleTopRightFill: "#ff9e9eff",
    SparkleTopRightLateFill: "#ff9e9eff",
    SparkleTopCenterFill: "#ff9e9eff",
    SparkleFarRightFill: "#f32020ff",
    SparkleFarLeftFill: "#f32020ff",
    SparkleTopLeftFill: "#fe0606ff",
    SparkleBottomLeftFill: "#fe0606ff",
    SparkleBottomCenterFill: "#fe0606ff",
    SparkleBottomRightFill: "#ff7575ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "The original red animation adapted for dark mode. Uses same colors but with darker window glass for contrast against dark backgrounds.",
  },
}

export const defaultredLightTheme: LottieThemeConfig = {
  themeId: "default-red-light",
  name: "Red Light",
  description:
    "Default red light theme that preserves the original red animation's visual style and patterns. This is essentially the original animation colors from the source file.",
  baseColor: "red",
  mode: "light",
  colors: {
    MainCharacterRightHandPalmFill: "#ff4242ff",
    MainCharacterRightHandThumbFill: "#ff8585ff",
    MainCharacterLeftHandPalmFill: "#ff4242ff",
    MainCharacterLeftHandThumbFill: "#ff8585ff",
    MainCharacterHeadBaseFill: "#fe0606ff",
    MainCharacterHeadFaceFill: "#ff8585ff",
    MainCharacterNeckFill: "#ff6666ff",
    MainCharacterTorsoFill: "#ff4242ff",
    MainCharacterLegUpperFill: "#ff7575ff",
    MainCharacterFootFill: "#ff7575ff",
    MainCharacterLegLowerFill: "#be3030ff",
    RocketExhaustCloudFill: "#ffececff",
    SidekickCharacterLeftHandThumbFill: "#ff8585ff",
    SidekickCharacterLeftHandPalmFill: "#ff7575ff",
    SidekickCharacterHeadBaseFill: "#ff4242ff",
    SidekickCharacterHeadFaceFill: "#ff8585ff",
    SidekickCharacterRightHandPalmFill: "#ff7575ff",
    SidekickCharacterNeckFill: "#ff6666ff",
    SidekickCharacterTorsoFill: "#ff7575ff",
    SidekickCharacterLegUpperFill: "#ff4242ff",
    SidekickCharacterFootFill: "#ff4242ff",
    SidekickCharacterLegLowerFill: "#f32020ff",
    RocketWindowLeftFill: "#ffebebff",
    RocketWindowLeftFrameFill: "#ff7575ff",
    RocketWindowRightFill: "#ffebebff",
    RocketWindowRightFrameFill: "#ff7575ff",
    RocketWindowBottomFill: "#ffebebff",
    RocketWindowBottomFrameFill: "#ff7575ff",
    RocketNoseConeFill: "#f32020ff",
    RocketFinBottomFill: "#dc3333ff",
    RocketFinLeftFill: "#dc3333ff",
    RocketExhaustOuterFlameFill: "#ff7575ff",
    RocketExhaustInnerFlameFill: "#fe0606ff",
    SparkleTopRightFill: "#ff9e9eff",
    SparkleTopRightLateFill: "#ff9e9eff",
    SparkleTopCenterFill: "#ff9e9eff",
    SparkleFarRightFill: "#f32020ff",
    SparkleFarLeftFill: "#f32020ff",
    SparkleTopLeftFill: "#fe0606ff",
    SparkleBottomLeftFill: "#fe0606ff",
    SparkleBottomCenterFill: "#fe0606ff",
    SparkleBottomRightFill: "#ff7575ff",
  },
  skippedElements: [],
  metadata: {
    created: new Date().toISOString(),
    version: "1.0.0",
    author: "Theme Converter",
    reasoning:
      "This is the original red animation - these are the exact colors from the source Lottie file. Included as the 'default' red theme to show the baseline that all other themes are derived from.",
  },
}

/**
 * All themes for this animation
 */
export const allThemes: LottieThemeConfig[] = [
  improveddualtonecolorblueDarkTheme,
  improveddualtonecolorblueLightTheme,
  improveddualtonecolorgreenDarkTheme,
  improveddualtonecolorgreenLightTheme,
  improveddualtonecolororangeDarkTheme,
  improveddualtonecolororangeLightTheme,
  improveddualtonecolorpurpleDarkTheme,
  improveddualtonecolorpurpleLightTheme,
  improveddualtonecolorredDarkTheme,
  improveddualtonecolorredLightTheme,
  improveddualtonecolortealDarkTheme,
  improveddualtonecolortealLightTheme,
  improvedmonochromecoloringblueDarkTheme,
  improvedmonochromecoloringblueLightTheme,
  improvedmonochromecoloringgreenDarkTheme,
  improvedmonochromecoloringgreenLightTheme,
  improvedmonochromecoloringorangeDarkTheme,
  improvedmonochromecoloringorangeLightTheme,
  improvedmonochromecoloringpurpleDarkTheme,
  improvedmonochromecoloringpurpleLightTheme,
  improvedmonochromecoloringredDarkTheme,
  improvedmonochromecoloringredLightTheme,
  improvedmonochromecoloringtealDarkTheme,
  improvedmonochromecoloringtealLightTheme,
  defaultblueDarkTheme,
  defaultblueLightTheme,
  defaultgreenDarkTheme,
  defaultgreenLightTheme,
  defaultorangeDarkTheme,
  defaultorangeLightTheme,
  defaultpurpleDarkTheme,
  defaultpurpleLightTheme,
  defaultredDarkTheme,
  defaultredLightTheme,
]

/**
 * Theme lookup by ID
 */
export const themesById: Record<string, LottieThemeConfig> = {
  "ImprovedDualToneColor-blue-dark": improveddualtonecolorblueDarkTheme,
  "ImprovedDualToneColor-blue-light": improveddualtonecolorblueLightTheme,
  "ImprovedDualToneColor-green-dark": improveddualtonecolorgreenDarkTheme,
  "ImprovedDualToneColor-green-light": improveddualtonecolorgreenLightTheme,
  "ImprovedDualToneColor-orange-dark": improveddualtonecolororangeDarkTheme,
  "ImprovedDualToneColor-orange-light": improveddualtonecolororangeLightTheme,
  "ImprovedDualToneColor-purple-dark": improveddualtonecolorpurpleDarkTheme,
  "ImprovedDualToneColor-purple-light": improveddualtonecolorpurpleLightTheme,
  "ImprovedDualToneColor-red-dark": improveddualtonecolorredDarkTheme,
  "ImprovedDualToneColor-red-light": improveddualtonecolorredLightTheme,
  "ImprovedDualToneColor-teal-dark": improveddualtonecolortealDarkTheme,
  "ImprovedDualToneColor-teal-light": improveddualtonecolortealLightTheme,
  "ImprovedMonochromeColoring-blue-dark": improvedmonochromecoloringblueDarkTheme,
  "ImprovedMonochromeColoring-blue-light": improvedmonochromecoloringblueLightTheme,
  "ImprovedMonochromeColoring-green-dark": improvedmonochromecoloringgreenDarkTheme,
  "ImprovedMonochromeColoring-green-light": improvedmonochromecoloringgreenLightTheme,
  "ImprovedMonochromeColoring-orange-dark": improvedmonochromecoloringorangeDarkTheme,
  "ImprovedMonochromeColoring-orange-light": improvedmonochromecoloringorangeLightTheme,
  "ImprovedMonochromeColoring-purple-dark": improvedmonochromecoloringpurpleDarkTheme,
  "ImprovedMonochromeColoring-purple-light": improvedmonochromecoloringpurpleLightTheme,
  "ImprovedMonochromeColoring-red-dark": improvedmonochromecoloringredDarkTheme,
  "ImprovedMonochromeColoring-red-light": improvedmonochromecoloringredLightTheme,
  "ImprovedMonochromeColoring-teal-dark": improvedmonochromecoloringtealDarkTheme,
  "ImprovedMonochromeColoring-teal-light": improvedmonochromecoloringtealLightTheme,
  "default-blue-dark": defaultblueDarkTheme,
  "default-blue-light": defaultblueLightTheme,
  "default-green-dark": defaultgreenDarkTheme,
  "default-green-light": defaultgreenLightTheme,
  "default-orange-dark": defaultorangeDarkTheme,
  "default-orange-light": defaultorangeLightTheme,
  "default-purple-dark": defaultpurpleDarkTheme,
  "default-purple-light": defaultpurpleLightTheme,
  "default-red-dark": defaultredDarkTheme,
  "default-red-light": defaultredLightTheme,
}
