import type { ExpanseLottie } from "../../types"

export const RocketLaunchSchema: ExpanseLottie = {
  animationName: "RocketLaunch",

  // Alternative names suggested by AI
  alternativeNames: [
    "RocketLaunch",
    "SpaceRocketAnimation",
    "AstronautLaunchLottie",
    "RocketBlastOff",
    "SpaceExploration",
  ],

  // Animation description
  description:
    "This Lottie animation features a dynamic rocket launch sequence with an astronaut character. The animation shows a rocket blasting off into space with vibrant colors, space elements, and smooth motion. The design conveys exploration, innovation, and achievement with a playful yet professional style.",

  // Metadata tags for categorization
  tags: [
    "rocket",
    "space",
    "launch",
    "astronaut",
    "science",
    "technology",
    "exploration",
    "innovation",
    "achievement",
    "blast-off",
    "mission",
    "startup",
  ],

  // Context-specific purposes for different application domains
  contextSpecificMetadata: {
    education: {
      context: "education",
      primary:
        "To celebrate the start of new learning journeys and major educational achievements.",
      useCaseExamples: [
        "Show after completing a major milestone or graduating from a program.",
        "Celebrate when students unlock advanced learning content.",
        "Display when a student begins a new course or learning path.",
        "Use to introduce STEM-focused lessons or science modules.",
      ],
      recommendations: [
        "Use for significant academic achievements to maximize impact.",
        "Pair with encouraging messages about scientific exploration.",
        "Consider accessibility for diverse learning needs.",
      ],
      tags: [
        "education",
        "learning",
        "achievement",
        "STEM",
        "milestone",
        "graduation",
      ],
    },
    work: {
      context: "work",
      primary:
        "To mark the launch of projects, products, or significant business milestones.",
      useCaseExamples: [
        "Show after successfully launching a new product or feature.",
        "Celebrate company milestones, funding rounds, or expansions.",
        "Display when kicking off a major project or initiative.",
        "Use in presentation decks to emphasize innovation and growth.",
      ],
      recommendations: [
        "Use for significant business events to maintain impact.",
        "Ensure the animation matches the professional context.",
        "Consider cultural sensitivity in global teams.",
      ],
      tags: [
        "work",
        "business",
        "product-launch",
        "milestone",
        "innovation",
        "startup",
      ],
    },
    gamification: {
      context: "gamification",
      primary:
        "To reward players for significant achievements and level progression.",
      useCaseExamples: [
        "Display after unlocking a major achievement or rare reward.",
        "Celebrate reaching the top of leaderboards.",
        "Show when players reach a new rank or tier.",
        "Use as a visual for starting special events or challenges.",
      ],
      recommendations: [
        "Reserve for high-level achievements to maintain excitement.",
        "Pair with reward animations or sound effects.",
        "Consider animation speed for game pacing.",
      ],
      tags: [
        "gamification",
        "achievement",
        "reward",
        "level-up",
        "leaderboard",
        "challenge",
      ],
    },
    life: {
      context: "life",
      primary:
        "To celebrate personal milestones and the start of new life chapters.",
      useCaseExamples: [
        "Display after achieving a major life goal.",
        "Mark significant personal achievements and breakthroughs.",
        "Show when starting a new personal project or habit.",
        "Use in apps to celebrate New Year resolutions or life changes.",
      ],
      recommendations: [
        "Use for genuinely significant personal moments.",
        "Ensure the celebratory tone matches the context.",
        "Consider cultural variations in celebration styles.",
      ],
      tags: [
        "life",
        "personal",
        "milestone",
        "goal",
        "achievement",
        "new-beginning",
      ],
    },
    "web-content": {
      context: "web-content",
      primary:
        "To create engaging hero sections and highlight innovation on websites.",
      useCaseExamples: [
        "Use as a hero animation on startup and tech company landing pages.",
        "Enhance 'About Us' sections that emphasize innovation and vision.",
        "Display after form submissions for product launches or pre-orders.",
        "Integrate into marketing campaigns for new product announcements.",
      ],
      recommendations: [
        "Optimize file size for web performance.",
        "Ensure animation doesn't distract from key messaging.",
        "Consider autoplay policies and user preferences.",
      ],
      tags: [
        "web",
        "marketing",
        "hero",
        "landing-page",
        "innovation",
        "startup",
      ],
    },
  },

  elements: {
    // Main Character Elements
    MainCharacterRightHandPalmFill: {
      name: "Main Character Right Hand Palm",
      description: "The main character's right hand palm",
      path: "layers[0].shapes[0].it[1].c.k",
      originalColor: "#ff4242ff",
      elementType: "fill",
      isSkinTone: true,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["mainCharacter", "hands"],
      tags: ["astronaut", "hand", "skin"],
    },
    MainCharacterRightHandThumbFill: {
      name: "Main Character Right Hand Thumb",
      description: "The main character's right hand thumb",
      path: "layers[0].shapes[1].it[0].it[0].it[1].c.k",
      originalColor: "#ff8585ff",
      elementType: "fill",
      isSkinTone: true,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["mainCharacter", "hands"],
      tags: ["astronaut", "hand", "skin"],
    },
    MainCharacterLeftHandPalmFill: {
      name: "Main Character Left Hand Palm",
      description: "The main character's left hand palm",
      path: "layers[1].shapes[0].it[1].c.k",
      originalColor: "#ff4242ff",
      elementType: "fill",
      isSkinTone: true,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["mainCharacter", "hands"],
      tags: ["astronaut", "hand", "skin"],
    },
    MainCharacterLeftHandThumbFill: {
      name: "Main Character Left Hand Thumb",
      description: "The main character's left hand thumb",
      path: "layers[1].shapes[1].it[0].it[0].it[1].c.k",
      originalColor: "#ff8585ff",
      elementType: "fill",
      isSkinTone: true,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["mainCharacter", "hands"],
      tags: ["astronaut", "hand", "skin"],
    },
    MainCharacterHeadBaseFill: {
      name: "Main Character Head Base",
      description: "The main character's head base/helmet",
      path: "layers[2].shapes[0].it[1].c.k",
      originalColor: "#fe0606ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: true,
      isEffect: false,
      isBackground: false,
      elementGroups: ["mainCharacter", "head"],
      tags: ["astronaut", "helmet", "clothing"],
    },
    MainCharacterHeadFaceFill: {
      name: "Main Character Head Face",
      description: "The main character's face",
      path: "layers[2].shapes[1].it[1].c.k",
      originalColor: "#ff8585ff",
      elementType: "fill",
      isSkinTone: true,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["mainCharacter", "head"],
      tags: ["astronaut", "face", "skin"],
    },
    MainCharacterNeckFill: {
      name: "Main Character Neck",
      description: "The main character's neck",
      path: "layers[3].shapes[0].it[1].c.k",
      originalColor: "#ff6666ff",
      elementType: "fill",
      isSkinTone: true,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["mainCharacter", "body"],
      tags: ["astronaut", "neck", "skin"],
    },
    MainCharacterTorsoFill: {
      name: "Main Character Torso",
      description: "The main character's torso/suit",
      path: "layers[3].shapes[1].it[0].it[1].c.k",
      originalColor: "#ff4242ff",
      elementType: "fill",

      isSkinTone: false,
      isClothing: true,
      isEffect: false,
      isBackground: false,
      elementGroups: ["mainCharacter", "body"],
      tags: ["astronaut", "suit", "clothing"],
    },
    MainCharacterLegUpperFill: {
      name: "Main Character Leg Upper",
      description: "The main character's upper leg",
      path: "layers[4].shapes[0].it[1].c.k",
      originalColor: "#ff7575ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: true,
      isEffect: false,
      isBackground: false,
      elementGroups: ["mainCharacter", "legs"],
      tags: ["astronaut", "leg", "clothing"],
    },
    MainCharacterFootFill: {
      name: "Main Character Foot",
      description: "The main character's foot",
      path: "layers[4].shapes[1].it[0].it[1].c.k",
      originalColor: "#ff7575ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: true,
      isEffect: false,
      isBackground: false,
      elementGroups: ["mainCharacter", "legs"],
      tags: ["astronaut", "foot", "clothing"],
    },
    MainCharacterLegLowerFill: {
      name: "Main Character Leg Lower",
      description: "The main character's lower leg",
      path: "layers[4].shapes[2].it[0].it[1].c.k",
      originalColor: "#be3030ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: true,
      isEffect: false,
      isBackground: false,
      elementGroups: ["mainCharacter", "legs"],
      tags: ["astronaut", "leg", "clothing"],
    },

    // Rocket Elements
    RocketExhaustCloudFill: {
      name: "Rocket Exhaust Cloud",
      description: "The rocket's exhaust cloud",
      path: "layers[5].shapes[0].it[1].c.k",
      originalColor: "#ffffffff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: true,
      isBackground: false,
      elementGroups: ["rocket", "exhaust"],
      tags: ["rocket", "exhaust", "cloud"],
    },
    RocketWindowLeftFill: {
      name: "Rocket Window Left",
      description: "The rocket's left window",
      path: "layers[7].layers[0].shapes[0].it[0].it[0].it[2].c.k",
      originalColor: "#ffffffff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["rocket", "windows"],
      tags: ["rocket", "window", "glass"],
    },
    RocketWindowLeftFrameFill: {
      name: "Rocket Window Left Frame",
      description: "The rocket's left window frame",
      path: "layers[7].layers[0].shapes[0].it[1].it[0].it[1].c.k",
      originalColor: "#ff7575ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["rocket", "windows"],
      tags: ["rocket", "window", "frame"],
    },
    RocketWindowRightFill: {
      name: "Rocket Window Right",
      description: "The rocket's right window",
      path: "layers[7].layers[0].shapes[1].it[0].it[0].it[2].c.k",
      originalColor: "#ffffffff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["rocket", "windows"],
      tags: ["rocket", "window", "glass"],
    },
    RocketWindowRightFrameFill: {
      name: "Rocket Window Right Frame",
      description: "The rocket's right window frame",
      path: "layers[7].layers[0].shapes[1].it[1].it[0].it[1].c.k",
      originalColor: "#ff7575ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["rocket", "windows"],
      tags: ["rocket", "window", "frame"],
    },
    RocketWindowBottomFill: {
      name: "Rocket Window Bottom",
      description: "The rocket's bottom window",
      path: "layers[7].layers[0].shapes[2].it[0].it[0].it[2].c.k",
      originalColor: "#ffffffff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["rocket", "windows"],
      tags: ["rocket", "window", "glass"],
    },
    RocketWindowBottomFrameFill: {
      name: "Rocket Window Bottom Frame",
      description: "The rocket's bottom window frame",
      path: "layers[7].layers[0].shapes[2].it[1].it[0].it[1].c.k",
      originalColor: "#ff7575ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["rocket", "windows"],
      tags: ["rocket", "window", "frame"],
    },
    RocketNoseConeFill: {
      name: "Rocket Nose Cone",
      description: "The rocket's nose cone",
      path: "layers[7].layers[0].shapes[3].it[1].c.k",
      originalColor: "#f32020ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["rocket", "nose"],
      tags: ["rocket", "nose", "cone"],
    },
    RocketFinBottomFill: {
      name: "Rocket Fin Bottom",
      description: "The rocket's bottom fin",
      path: "layers[7].layers[0].shapes[4].it[1].c.k",
      originalColor: "#db3333ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["rocket", "fins"],
      tags: ["rocket", "fin", "stabilizer"],
    },
    RocketFinLeftFill: {
      name: "Rocket Fin Left",
      description: "The rocket's left fin",
      path: "layers[7].layers[0].shapes[5].it[1].c.k",
      originalColor: "#db3333ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["rocket", "fins"],
      tags: ["rocket", "fin", "stabilizer"],
    },
    RocketExhaustOuterFlameFill: {
      name: "Rocket Exhaust Outer Flame",
      description: "The rocket's outer exhaust flame",
      path: "layers[7].layers[1].shapes[0].it[0].it[0].it[1].c.k",
      originalColor: "#ff7575ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: true,
      isBackground: false,
      elementGroups: ["rocket", "exhaust"],
      tags: ["rocket", "exhaust", "flame"],
    },
    RocketExhaustInnerFlameFill: {
      name: "Rocket Exhaust Inner Flame",
      description: "The rocket's inner exhaust flame",
      path: "layers[7].layers[1].shapes[1].it[0].it[0].it[1].c.k",
      originalColor: "#fe0606ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: true,
      isBackground: false,
      elementGroups: ["rocket", "exhaust"],
      tags: ["rocket", "exhaust", "flame"],
    },

    // Sidekick Character Elements
    SidekickCharacterLeftHandThumbFill: {
      name: "Sidekick Character Left Hand Thumb",
      description: "The sidekick character's left hand thumb",
      path: "layers[6].shapes[0].it[0].it[0].it[1].c.k",
      originalColor: "#ff8585ff",
      elementType: "fill",
      isSkinTone: true,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["sidekickCharacter", "hands"],
      tags: ["sidekick", "hand", "skin"],
    },
    SidekickCharacterLeftHandPalmFill: {
      name: "Sidekick Character Left Hand Palm",
      description: "The sidekick character's left hand palm",
      path: "layers[6].shapes[1].it[0].it[0].it[1].c.k",
      originalColor: "#ff7575ff",
      elementType: "fill",

      isSkinTone: true,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["sidekickCharacter", "hands"],
      tags: ["sidekick", "hand", "skin"],
    },
    SidekickCharacterHeadBaseFill: {
      name: "Sidekick Character Head Base",
      description: "The sidekick character's head base/helmet",
      path: "layers[8].shapes[0].it[1].c.k",
      originalColor: "#ff4242ff",
      elementType: "fill",

      isSkinTone: false,
      isClothing: true,
      isEffect: false,
      isBackground: false,
      elementGroups: ["sidekickCharacter", "head"],
      tags: ["sidekick", "helmet", "clothing"],
    },
    SidekickCharacterHeadFaceFill: {
      name: "Sidekick Character Head Face",
      description: "The sidekick character's face",
      path: "layers[8].shapes[1].it[1].c.k",
      originalColor: "#ff8585ff",
      elementType: "fill",
      isSkinTone: true,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["sidekickCharacter", "head"],
      tags: ["sidekick", "face", "skin"],
    },
    SidekickCharacterRightHandPalmFill: {
      name: "Sidekick Character Right Hand Palm",
      description: "The sidekick character's right hand palm",
      path: "layers[9].shapes[0].it[1].c.k",
      originalColor: "#ff7575ff",
      elementType: "fill",

      isSkinTone: true,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["sidekickCharacter", "hands"],
      tags: ["sidekick", "hand", "skin"],
    },
    SidekickCharacterNeckFill: {
      name: "Sidekick Character Neck",
      description: "The sidekick character's neck",
      path: "layers[10].shapes[0].it[1].c.k",
      originalColor: "#ff6666ff",
      elementType: "fill",
      isSkinTone: true,
      isClothing: false,
      isEffect: false,
      isBackground: false,
      elementGroups: ["sidekickCharacter", "body"],
      tags: ["sidekick", "neck", "skin"],
    },
    SidekickCharacterTorsoFill: {
      name: "Sidekick Character Torso",
      description: "The sidekick character's torso/suit",
      path: "layers[10].shapes[1].it[1].c.k",
      originalColor: "#ff7575ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: true,
      isEffect: false,
      isBackground: false,
      elementGroups: ["sidekickCharacter", "body"],
      tags: ["sidekick", "suit", "clothing"],
    },
    SidekickCharacterLegUpperFill: {
      name: "Sidekick Character Leg Upper",
      description: "The sidekick character's upper leg",
      path: "layers[11].shapes[0].it[1].c.k",
      originalColor: "#ff4242ff",
      elementType: "fill",

      isSkinTone: false,
      isClothing: true,
      isEffect: false,
      isBackground: false,
      elementGroups: ["sidekickCharacter", "legs"],
      tags: ["sidekick", "leg", "clothing"],
    },
    SidekickCharacterFootFill: {
      name: "Sidekick Character Foot",
      description: "The sidekick character's foot",
      path: "layers[11].shapes[1].it[1].c.k",
      originalColor: "#ff4242ff",
      elementType: "fill",

      isSkinTone: false,
      isClothing: true,
      isEffect: false,
      isBackground: false,
      elementGroups: ["sidekickCharacter", "legs"],
      tags: ["sidekick", "foot", "clothing"],
    },
    SidekickCharacterLegLowerFill: {
      name: "Sidekick Character Leg Lower",
      description: "The sidekick character's lower leg",
      path: "layers[11].shapes[2].it[1].c.k",
      originalColor: "#f32020ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: true,
      isEffect: false,
      isBackground: false,
      elementGroups: ["sidekickCharacter", "legs"],
      tags: ["sidekick", "leg", "clothing"],
    },

    // Sparkle Elements
    SparkleTopRightFill: {
      name: "Sparkle Top Right",
      description: "Top right sparkle",
      path: "layers[12].layers[0].shapes[0].it[0].it[1].c.k",
      originalColor: "#ff9e9eff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: true,
      isBackground: false,
      elementGroups: ["sparkles", "effects"],
      tags: ["sparkle", "effect", "magic"],
    },
    SparkleTopRightLateFill: {
      name: "Sparkle Top Right Late",
      description: "Top right late sparkle",
      path: "layers[12].layers[1].shapes[0].it[0].it[1].c.k",
      originalColor: "#ff9e9eff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: true,
      isBackground: false,
      elementGroups: ["sparkles", "effects"],
      tags: ["sparkle", "effect", "magic"],
    },
    SparkleTopCenterFill: {
      name: "Sparkle Top Center",
      description: "Top center sparkle",
      path: "layers[12].layers[2].shapes[0].it[0].it[1].c.k",
      originalColor: "#ff9e9eff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: true,
      isBackground: false,
      elementGroups: ["sparkles", "effects"],
      tags: ["sparkle", "effect", "magic"],
    },
    SparkleFarRightFill: {
      name: "Sparkle Far Right",
      description: "Far right sparkle",
      path: "layers[12].layers[3].shapes[0].it[0].it[1].c.k",
      originalColor: "#f32020ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: true,
      isBackground: false,
      elementGroups: ["sparkles", "effects"],
      tags: ["sparkle", "effect", "magic"],
    },
    SparkleFarLeftFill: {
      name: "Sparkle Far Left",
      description: "Far left sparkle",
      path: "layers[12].layers[4].shapes[0].it[0].it[1].c.k",
      originalColor: "#f32020ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: true,
      isBackground: false,
      elementGroups: ["sparkles", "effects"],
      tags: ["sparkle", "effect", "magic"],
    },
    SparkleTopLeftFill: {
      name: "Sparkle Top Left",
      description: "Top left sparkle",
      path: "layers[12].layers[5].shapes[0].it[0].it[1].c.k",
      originalColor: "#fe0606ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: true,
      isBackground: false,
      elementGroups: ["sparkles", "effects"],
      tags: ["sparkle", "effect", "magic"],
    },
    SparkleBottomLeftFill: {
      name: "Sparkle Bottom Left",
      description: "Bottom left sparkle",
      path: "layers[12].layers[6].shapes[0].it[0].it[1].c.k",
      originalColor: "#fe0606ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: true,
      isBackground: false,
      elementGroups: ["sparkles", "effects"],
      tags: ["sparkle", "effect", "magic"],
    },
    SparkleBottomCenterFill: {
      name: "Sparkle Bottom Center",
      description: "Bottom center sparkle",
      path: "layers[12].layers[7].shapes[0].it[0].it[1].c.k",
      originalColor: "#fe0606ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: true,
      isBackground: false,
      elementGroups: ["sparkles", "effects"],
      tags: ["sparkle", "effect", "magic"],
    },
    SparkleBottomRightFill: {
      name: "Sparkle Bottom Right",
      description: "Bottom right sparkle",
      path: "layers[12].layers[8].shapes[0].it[0].it[1].c.k",
      originalColor: "#ff7575ff",
      elementType: "fill",
      isSkinTone: false,
      isClothing: false,
      isEffect: true,
      isBackground: false,
      elementGroups: ["sparkles", "effects"],
      tags: ["sparkle", "effect", "magic"],
    },
  },

  recommendations: {
    recommendedColorPalettes: [
      "blue-light",
      "blue-dark",
      "purple-light",
      "purple-dark",
      "green-light",
      "green-dark",
      "orange-light",
      "orange-dark",
      "red-light",
      "red-dark",
      "teal-light",
      "teal-dark",
    ],

    elementGroups: {
      logicalGrouped: {
        mainCharacter: {
          elements: [
            "MainCharacterRightHandPalmFill",
            "MainCharacterRightHandThumbFill",
            "MainCharacterLeftHandPalmFill",
            "MainCharacterLeftHandThumbFill",
            "MainCharacterHeadBaseFill",
            "MainCharacterHeadFaceFill",
            "MainCharacterNeckFill",
            "MainCharacterTorsoFill",
            "MainCharacterLegUpperFill",
            "MainCharacterFootFill",
            "MainCharacterLegLowerFill",
          ],
          description: "All elements belonging to the main astronaut character",
        },
        rocket: {
          elements: [
            "RocketExhaustCloudFill",
            "RocketWindowLeftFill",
            "RocketWindowLeftFrameFill",
            "RocketWindowRightFill",
            "RocketWindowRightFrameFill",
            "RocketWindowBottomFill",
            "RocketWindowBottomFrameFill",
            "RocketNoseConeFill",
            "RocketFinBottomFill",
            "RocketFinLeftFill",
            "RocketExhaustOuterFlameFill",
            "RocketExhaustInnerFlameFill",
          ],
          description: "All elements belonging to the rocket vehicle",
        },
        sidekickCharacter: {
          elements: [
            "SidekickCharacterLeftHandThumbFill",
            "SidekickCharacterLeftHandPalmFill",
            "SidekickCharacterHeadBaseFill",
            "SidekickCharacterHeadFaceFill",
            "SidekickCharacterRightHandPalmFill",
            "SidekickCharacterNeckFill",
            "SidekickCharacterTorsoFill",
            "SidekickCharacterLegUpperFill",
            "SidekickCharacterFootFill",
            "SidekickCharacterLegLowerFill",
          ],
          description: "All elements belonging to the sidekick character",
        },
        sparkles: {
          elements: [
            "SparkleTopRightFill",
            "SparkleTopRightLateFill",
            "SparkleTopCenterFill",
            "SparkleFarRightFill",
            "SparkleFarLeftFill",
            "SparkleTopLeftFill",
            "SparkleBottomLeftFill",
            "SparkleBottomCenterFill",
            "SparkleBottomRightFill",
          ],
          description: "All sparkle effect elements",
        },
      },

      sharedColor: {
        characterSkin: {
          elements: [
            "MainCharacterRightHandPalmFill",
            "MainCharacterRightHandThumbFill",
            "MainCharacterLeftHandPalmFill",
            "MainCharacterLeftHandThumbFill",
            "MainCharacterHeadFaceFill",
            "MainCharacterNeckFill",
            "SidekickCharacterLeftHandThumbFill",
            "SidekickCharacterLeftHandPalmFill",
            "SidekickCharacterHeadFaceFill",
            "SidekickCharacterRightHandPalmFill",
            "SidekickCharacterNeckFill",
          ],
          description:
            "Character skin elements that should share skin tone colors",
          colorRelationship: "identical",
        },
        characterClothing: {
          elements: [
            "MainCharacterHeadBaseFill",
            "MainCharacterTorsoFill",
            "MainCharacterLegUpperFill",
            "MainCharacterFootFill",
            "MainCharacterLegLowerFill",
            "SidekickCharacterHeadBaseFill",
            "SidekickCharacterTorsoFill",
            "SidekickCharacterLegUpperFill",
            "SidekickCharacterFootFill",
            "SidekickCharacterLegLowerFill",
          ],
          description: "Character clothing that should be themed together",
          colorRelationship: "identical",
        },
        rocketBody: {
          elements: [
            "RocketNoseConeFill",
            "RocketFinBottomFill",
            "RocketFinLeftFill",
            "RocketWindowLeftFrameFill",
            "RocketWindowRightFrameFill",
            "RocketWindowBottomFrameFill",
          ],
          description: "Rocket body elements that should share colors",
          colorRelationship: "gradient",
        },
        rocketWindows: {
          elements: [
            "RocketWindowLeftFill",
            "RocketWindowRightFill",
            "RocketWindowBottomFill",
          ],
          description: "Rocket window elements that should remain clear/white",
          colorRelationship: "identical",
        },
        fireFlames: {
          elements: [
            "RocketExhaustOuterFlameFill",
            "RocketExhaustInnerFlameFill",
          ],
          description: "Fire elements that should share warm colors",
          colorRelationship: "gradient",
        },
        sparkleEffects: {
          elements: [
            "SparkleTopRightFill",
            "SparkleTopRightLateFill",
            "SparkleTopCenterFill",
            "SparkleFarRightFill",
            "SparkleFarLeftFill",
            "SparkleTopLeftFill",
            "SparkleBottomLeftFill",
            "SparkleBottomCenterFill",
            "SparkleBottomRightFill",
          ],
          description: "Sparkle elements that should share magical colors",
          colorRelationship: "gradient",
        },
      },

      themingPriority: {
        high: {
          elements: [
            "MainCharacterHeadBaseFill",
            "MainCharacterTorsoFill",
            "RocketNoseConeFill",
            "RocketFinBottomFill",
            "RocketFinLeftFill",
            "RocketExhaustOuterFlameFill",
            "RocketExhaustInnerFlameFill",
          ],
          description: "Most important elements for theming",
          priority: "high",
        },
        medium: {
          elements: [
            "MainCharacterLegUpperFill",
            "MainCharacterFootFill",
            "MainCharacterLegLowerFill",
            "SidekickCharacterHeadBaseFill",
            "SidekickCharacterTorsoFill",
            "SidekickCharacterLegUpperFill",
            "SidekickCharacterFootFill",
            "SidekickCharacterLegLowerFill",
            "RocketWindowLeftFrameFill",
            "RocketWindowRightFrameFill",
            "RocketWindowBottomFrameFill",
          ],
          description: "Secondary important elements",
          priority: "medium",
        },
        low: {
          elements: [
            "RocketExhaustCloudFill",
            "RocketWindowLeftFill",
            "RocketWindowRightFill",
            "RocketWindowBottomFill",
            "SparkleTopRightFill",
            "SparkleTopRightLateFill",
            "SparkleTopCenterFill",
            "SparkleFarRightFill",
            "SparkleFarLeftFill",
            "SparkleTopLeftFill",
            "SparkleBottomLeftFill",
            "SparkleBottomCenterFill",
            "SparkleBottomRightFill",
          ],
          description:
            "Background and effect elements with low theming priority",
          priority: "low",
        },
      },

      visualHierarchy: {
        primary: {
          elements: [
            "MainCharacterHeadBaseFill",
            "MainCharacterTorsoFill",
            "RocketNoseConeFill",
            "RocketFinBottomFill",
            "RocketFinLeftFill",
          ],
          description: "Primary visual elements",
          hierarchy: "primary",
        },
        secondary: {
          elements: [
            "MainCharacterLegUpperFill",
            "MainCharacterFootFill",
            "MainCharacterLegLowerFill",
            "SidekickCharacterHeadBaseFill",
            "SidekickCharacterTorsoFill",
            "SidekickCharacterLegUpperFill",
            "SidekickCharacterFootFill",
            "SidekickCharacterLegLowerFill",
            "RocketWindowLeftFrameFill",
            "RocketWindowRightFrameFill",
            "RocketWindowBottomFrameFill",
          ],
          description: "Secondary visual elements",
          hierarchy: "secondary",
        },
        accent: {
          elements: [
            "RocketExhaustOuterFlameFill",
            "RocketExhaustInnerFlameFill",
            "SparkleTopRightFill",
            "SparkleTopRightLateFill",
            "SparkleTopCenterFill",
            "SparkleFarRightFill",
            "SparkleFarLeftFill",
            "SparkleTopLeftFill",
            "SparkleBottomLeftFill",
            "SparkleBottomCenterFill",
            "SparkleBottomRightFill",
          ],
          description: "Accent effect elements",
          hierarchy: "accent",
        },
        background: {
          elements: [
            "RocketExhaustCloudFill",
            "RocketWindowLeftFill",
            "RocketWindowRightFill",
            "RocketWindowBottomFill",
          ],
          description: "Background elements",
          hierarchy: "background",
        },
      },
    },

    optionalAiContext: {},

    optionalAiStylePrompts: {
      light:
        "Create a light theme with bright, vibrant colors that maintain good contrast and readability. Use warm, energetic colors for fire effects and cool, professional colors for the astronaut and rocket.",
      dark: "Create a dark theme with deep, rich colors that provide excellent contrast against dark backgrounds. Use bright, glowing colors for fire effects and metallic, space-age colors for the astronaut and rocket.",
      accent:
        "Create an accent theme that uses a single primary color with complementary shades. Focus on creating visual hierarchy through color intensity and saturation.",
    },

    optionalAiVariantPrompts: {
      monochrome:
        "Create a monochrome theme using only shades of a single color. Maintain visual hierarchy through lightness and saturation variations.",
      gradient:
        "Create a gradient theme that uses smooth color transitions between related colors. Apply gradients to large elements like the rocket body and astronaut suit.",
      neon: "Create a neon theme with bright, glowing colors that would work well in dark environments. Use high saturation and brightness for all elements.",
      pastel:
        "Create a pastel theme with soft, muted colors that are easy on the eyes. Use low saturation and high lightness for all elements.",
    },
  },
}
