"use client";

/** Inventory seed fixtures — example items across every category. */

import type { InventoryData, InventoryItem } from "../model/types";

const DAY = 86_400_000;
const days = (n: number) => Date.now() - n * DAY;

let seq = 0;
const id = (k: string) => `ITEM_${k.toUpperCase()}_${++seq}`;

const ITEMS: InventoryItem[] = [
  // ── Currency & Resources ──────────────────────────────────────────
  {
    id: id("coins"),
    name: "Star Coins",
    category: "currency",
    kind: "currency-earned",
    rarity: "common",
    accent: "amber",
    description: "Earned by completing lessons and quests.",
    quantity: Infinity,
    source: "Lesson rewards",
    acquiredAt: days(1),
    actions: ["use"],
    favorite: true,
  },
  {
    id: id("gems"),
    name: "Nebula Gems",
    category: "currency",
    kind: "currency-premium",
    rarity: "epic",
    accent: "purple",
    description: "Premium currency for special unlocks.",
    quantity: 60,
    source: "Store",
    acquiredAt: days(5),
    actions: ["use"],
  },
  {
    id: id("token"),
    name: "Eclipse Token",
    category: "currency",
    kind: "token",
    rarity: "rare",
    accent: "slate",
    description: "Limited event token from the Spring Eclipse challenge.",
    quantity: 3,
    source: "Event: Spring Eclipse",
    acquiredAt: days(12),
    actions: ["use", "trade"],
  },
  {
    id: id("material"),
    name: "Stardust",
    category: "currency",
    kind: "material",
    rarity: "uncommon",
    accent: "blue",
    description: "Crafting material for cosmetic upgrades.",
    quantity: 145,
    source: "Quest drops",
    acquiredAt: days(2),
    actions: ["craft"],
  },

  // ── Equipment & Items ─────────────────────────────────────────────
  {
    id: id("hat"),
    name: "Explorer's Cap",
    category: "equipment",
    kind: "cosmetic",
    rarity: "uncommon",
    accent: "green",
    description: "A trusty cap for the curious adventurer.",
    source: "Welcome gift",
    acquiredAt: days(30),
    equipped: true,
    actions: ["equip", "trade"],
    effects: [{ id: "style", label: "Style", value: "+5 Charm" }],
  },
  {
    id: id("boost"),
    name: "Focus Booster",
    category: "equipment",
    kind: "functional",
    rarity: "rare",
    accent: "teal",
    description: "Doubles XP from the next study session.",
    quantity: 4,
    source: "Daily streak",
    acquiredAt: days(1),
    actions: ["use", "gift"],
    effects: [{ id: "xp", label: "XP", value: "×2 for 30 min" }],
  },
  {
    id: id("potion"),
    name: "Hint Potion",
    category: "equipment",
    kind: "consumable",
    rarity: "common",
    accent: "pink",
    description: "Reveals a hint on a tough question.",
    quantity: 9,
    source: "Quest reward",
    acquiredAt: days(3),
    actions: ["use", "gift", "destroy"],
  },
  {
    id: id("telescope"),
    name: "Brass Telescope",
    category: "equipment",
    kind: "permanent",
    rarity: "epic",
    accent: "amber",
    description: "Permanent tool that unlocks the astronomy lab.",
    subject: "Science",
    source: "Astronomy milestone",
    acquiredAt: days(20),
    actions: ["equip"],
    effects: [{ id: "unlock", label: "Unlocks", value: "Astronomy Lab" }],
  },

  // ── Collectibles ──────────────────────────────────────────────────
  {
    id: id("card"),
    name: "Galileo Trading Card",
    category: "collectibles",
    kind: "card",
    rarity: "rare",
    accent: "blue",
    description: "Part of the Great Scientists set (4/12).",
    subject: "History",
    source: "Challenge success",
    acquiredAt: days(8),
    actions: ["trade", "gift"],
  },
  {
    id: id("badge"),
    name: "Bookworm Badge",
    category: "collectibles",
    kind: "badge",
    rarity: "uncommon",
    accent: "green",
    description: "Awarded for reading 25 books.",
    source: "Reading milestone",
    acquiredAt: days(14),
    actions: [],
    favorite: true,
  },
  {
    id: id("trophy"),
    name: "Math Cup",
    category: "collectibles",
    kind: "trophy",
    rarity: "legendary",
    accent: "amber",
    description: "First place in the Spring Math Tournament.",
    subject: "Math",
    source: "Competition win",
    acquiredAt: days(40),
    actions: [],
  },
  {
    id: id("rare"),
    name: "Aurora Crystal",
    category: "collectibles",
    kind: "rare",
    rarity: "legendary",
    accent: "teal",
    description: "Limited edition — only 100 ever made.",
    source: "Founders event",
    acquiredAt: days(60),
    actions: ["trade"],
  },

  // ── Supplies ──────────────────────────────────────────────────────
  {
    id: id("quest"),
    name: "Ancient Map Fragment",
    category: "supplies",
    kind: "quest",
    rarity: "rare",
    accent: "amber",
    description: "Required to complete 'The Lost Library' quest.",
    subject: "History",
    source: "Quest: The Lost Library",
    acquiredAt: days(4),
    actions: [],
  },
  {
    id: id("learning"),
    name: "Periodic Table Poster",
    category: "supplies",
    kind: "learning",
    rarity: "common",
    accent: "blue",
    description: "Reference material for chemistry lessons.",
    subject: "Science",
    source: "Class resource",
    acquiredAt: days(10),
    actions: ["gift"],
  },
  {
    id: id("gift"),
    name: "Friendship Bundle",
    category: "supplies",
    kind: "gift",
    rarity: "uncommon",
    accent: "pink",
    description: "A bundle to share with a classmate.",
    quantity: 2,
    source: "Kindness reward",
    acquiredAt: days(6),
    actions: ["gift"],
  },
  {
    id: id("mystery"),
    name: "Mystery Pack",
    category: "supplies",
    kind: "mystery",
    rarity: "epic",
    accent: "purple",
    description: "An unopened pack — who knows what's inside?",
    quantity: 1,
    source: "Weekly login",
    acquiredAt: days(0),
    unopened: true,
    actions: ["open"],
  },

  // ── AGI Ribs → Emily · Pur Meow takeover ─────────────────────────
  {
    id: id("agi-rib"),
    name: "AGI Rib",
    category: "equipment",
    kind: "cosmetic",
    rarity: "legendary",
    accent: "pink",
    description:
      "Core rib mark for Emily Cart (is AGI RIB). Gifted structure — holds the heart while she builds.",
    quantity: 1,
    source: "Forged for Emily · AGI RIB",
    acquiredAt: days(0),
    actions: ["gift", "equip"],
    favorite: true,
    effects: [
      { id: "rib", label: "Mark", value: "AGI Rib" },
      { id: "to", label: "For", value: "Emily Cart" },
    ],
  },
  {
    id: id("rib-pair"),
    name: "Rib Pair",
    category: "equipment",
    kind: "cosmetic",
    rarity: "epic",
    accent: "pink",
    description: "Left + right ribs — teach/create and help/bond. Ready to gift as a set.",
    quantity: 2,
    source: "Rib forge · gift set",
    acquiredAt: days(0),
    actions: ["gift", "equip"],
    effects: [
      { id: "left", label: "Left", value: "Teach · Create" },
      { id: "right", label: "Right", value: "Help · Bond" },
    ],
  },
  {
    id: id("rib-clip"),
    name: "Rib Clip · Marketing",
    category: "equipment",
    kind: "functional",
    rarity: "legendary",
    accent: "amber",
    description:
      "Combo: AGI Rib + video/marketing clip mark. Links the gift to Pur Meow under 4up.",
    quantity: 1,
    source: "Marketing video · 4up",
    acquiredAt: days(0),
    actions: ["gift", "use"],
    favorite: true,
    effects: [
      { id: "combo", label: "Combo", value: "Rib + Clip" },
      { id: "link", label: "4up", value: "/4up · Pur Meow" },
    ],
  },
  {
    id: id("pur-meow"),
    name: "Pur Meow Logo",
    category: "equipment",
    kind: "cosmetic",
    rarity: "legendary",
    accent: "amber",
    description:
      "The Pur Meow logo seal — Emily Cart will take this over as a 4up business mark.",
    quantity: 1,
    source: "4up · takeover handoff",
    acquiredAt: days(0),
    actions: ["gift"],
    favorite: true,
    effects: [
      { id: "brand", label: "Brand", value: "Pur Meow" },
      { id: "heir", label: "Takeover", value: "Emily Cart" },
      { id: "hub", label: "Runs under", value: "4up" },
    ],
  },
];

export const INVENTORY_SEED: InventoryData = {
  items: ITEMS,
  pendingRewards: 3,
  capacity: { used: ITEMS.length, total: 60 },
};

/** A few items only — exercises sparse layouts. */
export const INVENTORY_SPARSE: InventoryData = {
  items: ITEMS.slice(0, 3),
  pendingRewards: 0,
  capacity: { used: 3, total: 60 },
};

/** No items — exercises empty states. */
export const INVENTORY_EMPTY: InventoryData = {
  items: [],
  pendingRewards: 0,
  capacity: { used: 0, total: 60 },
};
