/**
 * Schema File Generator
 * Generates .expanse-lottie.ts files from metadata and elements
 *
 * NOTE: This module runs in the browser, so no filesystem access is available.
 * Template is embedded directly in the generateSchemaFileInline function.
 */

import type {
  ExpanseLottieMetadata,
  ExpanseLottieElementDetails,
  ExpanseLottie,
} from "expanse.dynamicAssets"

export interface SchemaExportOptions {
  animationName: string
  metadata: ExpanseLottieMetadata
  elements: Record<string, ExpanseLottieElementDetails>
}

/**
 * Build the complete ExpanseLottie object from metadata and elements
 */
function buildExpanseLottie(options: SchemaExportOptions): ExpanseLottie {
  const { animationName, metadata, elements } = options

  return {
    ...metadata,
    animationName, // Ensure animationName is set correctly
    elements,
  }
}

/**
 * Generate ExpanseLottie TypeScript file content
 * Template is embedded directly for browser compatibility
 */
export function generateSchemaFileInline(options: SchemaExportOptions): string {
  const { animationName } = options

  // Build the complete schema object
  const schema = buildExpanseLottie(options)

  // Serialize to formatted JSON
  const schemaJson = JSON.stringify(schema, null, 2)

  return `/**
 * ${animationName} - ExpanseLottie Schema
 * Generated by AI Naming Tool
 */

import type { ExpanseLottie } from "../../types"

export const ${animationName}Schema: ExpanseLottie = ${schemaJson}
`
}

/**
 * Generate filename for the schema export
 */
export function generateSchemaFilename(animationName: string): string {
  return `${animationName}.expanse-lottie.ts`
}
