# Use official Node.js LTS image
FROM node:24-alpine

ENV NODE_VERSION=24.4.0
# may not need this
RUN apk add --no-cache git openssh

WORKDIR /app-root

# Copy package files and install dependencies
COPY ./@types ./@types
COPY ./apps/expanseEdu ./apps/expanseEdu
COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./tsconfig.json ./tsconfig.json

RUN --mount=type=ssh npm install

WORKDIR /app-root/apps/expanseEdu

# Build the Next.js app
RUN npm run build 

# Copy built output and necessary files
WORKDIR /app-root
RUN rm -rf ./packages
RUN rm -rf ./apps/expanseEdu/src
RUN rm -rf ./apps/expanseEdu/public

EXPOSE 3600

WORKDIR /app-root/apps/expanseEdu
CMD ["npm", "run", "startServer"]