export const GEMINI_TEXT_MODEL = 'GEMINI_TEXT_MODEL';
export const GEMINI_VISION_MODEL = 'GEMINI_VISION_MODEL';
export const GOOGLE_AI_FILE_MANAGER = 'GOOGLE_AI_FILE_MANAGER';
export const GOOGLE_IMAGE_ANNOTATOR = 'GOOGLE_IMAGE_ANNOTATOR';
export const GOOGLE_VERTEX_IMAGE_GEN_AI = 'GOOGLE_VERTEX_IMAGE_GEN_AI';
export const GOOGLE_AI_HELPERS = 'GOOGLE_AI_HELPERS';
