/**
 * SwingingShoppingBag Theme Configurations
 * Generated by Lottie Naming Tool
 *
 * Variant: default
 * Total themes: 10
 */

import type { LottieThemeConfig } from "../../theming/lottieColorMapping"

export const defaultPurpleLightTheme: LottieThemeConfig = {
  themeId: "default-purple-light",
  name: "Purple Light",
  description: "A sophisticated purple theme featuring a dark bag body with lighter handles, creating a clear and elegant look for light UIs.",
  baseColor: "purple",
  mode: "light",
  colors: {
    BagBodyAccentFill: "#a15bca",
    BagBodyMainFill: "#3c1a51",
    BagRimFill: "#e0c9ee",
    HandleLeftFill: "#e0c9ee",
    HandleRightFill: "#e0c9ee",
  },
  skippedElements: [],
}

export const defaultPurpleDarkTheme: LottieThemeConfig = {
  themeId: "default-purple-dark",
  name: "Purple Dark",
  description: "A vibrant purple theme optimized for dark mode. Bright purples and off-white accents ensure the animation is dynamic and clearly visible against dark backgrounds.",
  baseColor: "purple",
  mode: "dark",
  colors: {
    BagBodyAccentFill: "#e1c2f5",
    BagBodyMainFill: "#a15bca",
    BagRimFill: "#F9F5FF",
    HandleLeftFill: "#F9F5FF",
    HandleRightFill: "#F9F5FF",
  },
  skippedElements: [],
}

export const defaultBlueLightTheme: LottieThemeConfig = {
  themeId: "default-blue-light",
  name: "Classic Blue Light",
  description: "A professional and clean theme featuring a primary blue bag with sophisticated gray handles, optimized for light backgrounds.",
  baseColor: "blue",
  mode: "light",
  colors: {
    HandleRightFill: "#707171",
    HandleLeftFill: "#707171",
    BagRimFill: "#707171",
    BagBodyAccentFill: "#1976D2",
    BagBodyMainFill: "#4285F4",
  },
  skippedElements: [],
}

export const defaultBlueDarkTheme: LottieThemeConfig = {
  themeId: "default-blue-dark",
  name: "Luminous Blue Dark",
  description: "A vibrant and luminous theme for dark mode, with a bright blue bag and crisp, light handles that pop against the dark background.",
  baseColor: "blue",
  mode: "dark",
  colors: {
    HandleRightFill: "#E8F5FE",
    HandleLeftFill: "#E8F5FE",
    BagRimFill: "#E8F5FE",
    BagBodyAccentFill: "#2196F3",
    BagBodyMainFill: "#29B6F6",
  },
  skippedElements: [],
}

export const defaultGreenLightTheme: LottieThemeConfig = {
  themeId: "default-green-light",
  name: "Green Light",
  description: "A fresh and vibrant theme with a primary green bag and cheerful teal handles, suitable for light backgrounds.",
  baseColor: "green",
  mode: "light",
  colors: {
    HandleRightFill: "#4DB6AC",
    HandleLeftFill: "#4DB6AC",
    BagRimFill: "#4DB6AC",
    BagBodyAccentFill: "#388E3C",
    BagBodyMainFill: "#4CAF50",
  },
  skippedElements: [],
}

export const defaultGreenDarkTheme: LottieThemeConfig = {
  themeId: "default-green-dark",
  name: "Green Dark",
  description: "A luminous green theme designed for dark interfaces, featuring bright, high-contrast colors for excellent visibility.",
  baseColor: "green",
  mode: "dark",
  colors: {
    HandleRightFill: "#A5D6A7",
    HandleLeftFill: "#A5D6A7",
    BagRimFill: "#A5D6A7",
    BagBodyAccentFill: "#4CAF50",
    BagBodyMainFill: "#66BB6A",
  },
  skippedElements: [],
}

export const defaultOrangeLightTheme: LottieThemeConfig = {
  themeId: "default-orange-light",
  name: "Sunset Citrus",
  description: "A warm and inviting theme featuring bright orange tones, perfect for a sunny, positive user experience in light mode.",
  baseColor: "orange",
  mode: "light",
  colors: {
    HandleRightFill: "#FFF3E0",
    HandleLeftFill: "#FFF3E0",
    BagRimFill: "#FFF3E0",
    BagBodyAccentFill: "#EF6C00",
    BagBodyMainFill: "#FF9800",
  },
  skippedElements: [],
}

export const defaultOrangeDarkTheme: LottieThemeConfig = {
  themeId: "default-orange-dark",
  name: "Ember Glow",
  description: "A striking and vibrant theme designed for dark mode, with a glowing orange that stands out against a deep background.",
  baseColor: "orange",
  mode: "dark",
  colors: {
    HandleRightFill: "#FFF8F0",
    HandleLeftFill: "#FFF8F0",
    BagRimFill: "#FFF8F0",
    BagBodyAccentFill: "#EF6C00",
    BagBodyMainFill: "#FFA726",
  },
  skippedElements: [],
}

export const defaultRedLightTheme: LottieThemeConfig = {
  themeId: "default-red-light",
  name: "Red Light",
  description: "A vibrant and clean theme featuring a bold red bag with classic, light-colored handles. Ideal for light mode UIs.",
  baseColor: "red",
  mode: "light",
  colors: {
    HandleRightFill: "#F5E9E2",
    HandleLeftFill: "#F5E9E2",
    BagRimFill: "#F5E9E2",
    BagBodyAccentFill: "#B71C1C",
    BagBodyMainFill: "#E53935",
  },
  skippedElements: [],
}

export const defaultRedDarkTheme: LottieThemeConfig = {
  themeId: "default-red-dark",
  name: "Red Dark",
  description: "A rich and elegant theme with a luminous red bag and warm golden handles, designed to stand out on dark backgrounds.",
  baseColor: "red",
  mode: "dark",
  colors: {
    HandleRightFill: "#E8D5A5",
    HandleLeftFill: "#E8D5A5",
    BagRimFill: "#E8D5A5",
    BagBodyAccentFill: "#be3030",
    BagBodyMainFill: "#E57373",
  },
  skippedElements: [],
}

/**
 * All themes for this animation
 */
export const allThemes: LottieThemeConfig[] = [
  defaultPurpleLightTheme,
  defaultPurpleDarkTheme,
  defaultBlueLightTheme,
  defaultBlueDarkTheme,
  defaultGreenLightTheme,
  defaultGreenDarkTheme,
  defaultOrangeLightTheme,
  defaultOrangeDarkTheme,
  defaultRedLightTheme,
  defaultRedDarkTheme,
]

/**
 * Theme lookup by ID
 */
export const themesById: Record<string, LottieThemeConfig> = {
  "default-purple-light": defaultPurpleLightTheme,
  "default-purple-dark": defaultPurpleDarkTheme,
  "default-blue-light": defaultBlueLightTheme,
  "default-blue-dark": defaultBlueDarkTheme,
  "default-green-light": defaultGreenLightTheme,
  "default-green-dark": defaultGreenDarkTheme,
  "default-orange-light": defaultOrangeLightTheme,
  "default-orange-dark": defaultOrangeDarkTheme,
  "default-red-light": defaultRedLightTheme,
  "default-red-dark": defaultRedDarkTheme,
}
