/**
 * SwingingShoppingBag - ExpanseLottie Schema
 * Generated by AI Naming Tool
 */

import type { ExpanseLottie } from "../../types"

export const SwingingShoppingBagSchema: ExpanseLottie = {
  "animationName": "SwingingShoppingBag",
  "alternativeNames": [
    "RetailCarryall",
    "FashionTote",
    "ShoppingSpreeIcon",
    "BoutiqueBag"
  ],
  "description": "A stylized shopping bag or handbag with swinging handles. The animation features a smooth scale-in and scale-out effect, with the handles looping in a gentle, rhythmic sway. The bag body and handles are distinct, themeable elements, making it ideal for e-commerce and retail applications.",
  "tags": [
    "bag",
    "shopping",
    "retail",
    "e-commerce",
    "fashion",
    "swaying",
    "loop",
    "icon",
    "purchase",
    "checkout",
    "add-to-cart",
    "item",
    "style"
  ],
  "purpose": {
    "primary": "To visually represent shopping, purchasing, or adding items to a cart in a delightful and engaging way.",
    "categories": {
      "E-Commerce": [
        "Add to Cart confirmation",
        "View Cart icon",
        "Order Successful screen",
        "Empty Cart state"
      ],
      "Retail": [
        "Promotional banners for sales",
        "New arrivals announcement",
        "Loading icon for a product gallery"
      ],
      "Fashion": [
        "Interactive element in a style guide",
        "Icon for a 'Shop the Look' feature",
        "Animated logo for a boutique brand"
      ]
    },
    "contexts": [
      "web-content",
      "life",
      "gamification"
    ],
    "recommendations": [
      "Use as a micro-interaction on 'Add to Cart' buttons to provide immediate feedback.",
      "Place on a checkout or order confirmation page as a success indicator.",
      "Utilize as a loading state when fetching products or processing an order."
    ]
  },
  "contextSpecificMetadata": {
    "education": {
      "context": "education",
      "primary": "Representing school supplies or carrying learning materials.",
      "useCaseExamples": [
        "Icon for a digital book bag or resource folder.",
        "Animation for a school's online bookstore.",
        "Confirmation for submitting a project or assignment.",
        "Visual cue for a 'materials needed' section in a lesson plan."
      ],
      "tags": [
        "book-bag",
        "school-supplies",
        "resources",
        "submission",
        "student-life"
      ]
    },
    "work": {
      "context": "work",
      "primary": "Symbolizing a work briefcase, company assets, or corporate shopping.",
      "useCaseExamples": [
        "Icon for a 'My Documents' or 'Briefcase' folder in a corporate portal.",
        "Animation for a company's internal swag store.",
        "Visual for adding items to a procurement request.",
        "Indicator for a successful file transfer or download."
      ],
      "tags": [
        "briefcase",
        "documents",
        "corporate-store",
        "procurement",
        "assets"
      ]
    },
    "gamification": {
      "context": "gamification",
      "primary": "Representing a player's inventory, a reward, or a loot drop.",
      "useCaseExamples": [
        "Animated icon for the inventory or 'Bag' button.",
        "Visual feedback for collecting an item or reward.",
        "Animation for a 'loot bag' or mystery box opening.",
        "Marketplace or shop icon within a game."
      ],
      "tags": [
        "inventory",
        "loot",
        "reward",
        "item-collected",
        "in-game-shop"
      ]
    },
    "life": {
      "context": "life",
      "primary": "Illustrating personal shopping, errands, or carrying personal items.",
      "useCaseExamples": [
        "Icon for a shopping list app.",
        "Animation in a budgeting app to categorize 'Shopping' expenses.",
        "Decorative element in a blog post about fashion or travel.",
        "Visual cue in a to-do list for 'Run Errands' tasks."
      ],
      "tags": [
        "personal-shopping",
        "errands",
        "lifestyle",
        "wishlist",
        "daily-tasks"
      ]
    },
    "web-content": {
      "context": "web-content",
      "primary": "Enhancing user experience on e-commerce sites and retail platforms.",
      "useCaseExamples": [
        "Primary 'Shopping Cart' or 'Bag' icon in a website header.",
        "Micro-interaction on an 'Add to Bag' button.",
        "Success animation on an order confirmation page.",
        "Engaging loading animation for a product page."
      ],
      "recommendations": [
        "Integrate with cart functionality; could change color or show an item count when items are added.",
        "Use the looping sway on hover to indicate interactivity."
      ],
      "tags": [
        "e-commerce",
        "add-to-cart",
        "checkout",
        "online-store",
        "user-interface"
      ]
    }
  },
  "recommendations": {
    "recommendedColorPalettes": [
      "Pastel Pop",
      "Luxury Noir",
      "Eco-Friendly Earth Tones",
      "Bold & Modern",
      "Corporate Blue & Gray"
    ],
    "elementGroups": {
      "logicalGrouped": {
        "bagBody": {
          "elements": [
            "B 5.G.P",
            "B 4.G.P"
          ],
          "description": "The main body and front flap of the shopping bag."
        },
        "bagStraps": {
          "elements": [
            "B.G.P",
            "B 2.G.P",
            "B 3.G.P"
          ],
          "description": "The two swinging straps and the central strap holder."
        }
      },
      "sharedColor": {
        "bagBodyColor": {
          "elements": [
            "B 5.G.F",
            "B 4.G.F"
          ],
          "description": "The main body and front flap of the bag, which share a dark purple color scheme.",
          "colorRelationship": "shades"
        },
        "strapColor": {
          "elements": [
            "B.G.F",
            "B 2.G.F",
            "B 3.G.F"
          ],
          "description": "The straps and strap holder, which all share an identical light peach color.",
          "colorRelationship": "identical"
        }
      },
      "themingPriority": {
        "primaryBagColor": {
          "elements": [
            "B 5.G.F",
            "B 4.G.F"
          ],
          "description": "The bag body is the largest visual component and defines the primary color.",
          "priority": "high"
        },
        "strapAccentColor": {
          "elements": [
            "B.G.F",
            "B 2.G.F",
            "B 3.G.F"
          ],
          "description": "The straps provide a contrasting accent color and are the focus of the motion.",
          "priority": "medium"
        }
      },
      "visualHierarchy": {
        "primaryElement": {
          "elements": [
            "B 5.G.P",
            "B 4.G.P",
            "B 3.G.P",
            "B 2.G.P",
            "B.G.P"
          ],
          "description": "The entire bag assembly, which forms the main subject of the animation.",
          "hierarchy": "primary"
        },
        "motionAccent": {
          "elements": [
            "B 2.G.P",
            "B.G.P"
          ],
          "description": "The swinging straps are the key animated elements that draw the user's eye.",
          "hierarchy": "accent"
        }
      }
    },
    "optionalAiContext": {
      "mood": "Playful, light, positive, satisfying",
      "style": "Minimalist, flat design, modern, clean",
      "theme": "Shopping, retail, fashion, consumerism"
    },
    "optionalAiStylePrompts": {
      "base": "Flat design illustration, minimalist icon animation, clean vector art, 2D cartoon style with smooth motion",
      "decorative": "Whimsical and charming animation, pastel color palette, soft shadows",
      "corporate": "Professional and clean animation, muted corporate colors, subtle motion"
    },
    "optionalAiVariantPrompts": {
      "objectSwap": "Animate a paper grocery bag with the same swinging motion",
      "styleSwap": "Re-imagine this animation in a detailed, textured style, like a leather handbag",
      "contextual": "Create a version where a small item flies into the bag as it swings",
      "alternative": "Animate a backpack with a slight bounce and jingling zippers"
    }
  },
  "elements": {
    "HandleRightFill": {
      "name": "HandleRightFill",
      "alternativeNames": [
        "HandleFrontFill"
      ],
      "description": "The fill color for the right swinging handle of the shopping bag.",
      "path": "layers[0].shapes[0].it[1].c.k",
      "originalColor": "#efcfc2ff",
      "elementType": "fill",
      "roleFunction": "primary_subject",
      "visualLevel": "primary",
      "semanticRole": "illustrative_object",
      "isThemeable": true,
      "isClothing": false,
      "isEffect": false,
      "isBackground": false,
      "elementGroups": [
        "bag",
        "handle",
        "themeable",
        "primary"
      ],
      "tags": [
        "handle",
        "swinging",
        "animated"
      ]
    },
    "HandleLeftFill": {
      "name": "HandleLeftFill",
      "alternativeNames": [
        "HandleBackFill"
      ],
      "description": "The fill color for the left swinging handle of the shopping bag.",
      "path": "layers[1].shapes[0].it[1].c.k",
      "originalColor": "#efcfc2ff",
      "elementType": "fill",
      "roleFunction": "primary_subject",
      "visualLevel": "primary",
      "semanticRole": "illustrative_object",
      "isThemeable": true,
      "isClothing": false,
      "isEffect": false,
      "isBackground": false,
      "elementGroups": [
        "bag",
        "handle",
        "themeable",
        "primary"
      ],
      "tags": [
        "handle",
        "swinging",
        "animated"
      ]
    },
    "BagRimFill": {
      "name": "BagRimFill",
      "alternativeNames": [
        "BagOpeningFill"
      ],
      "description": "The fill color for the top rim or opening of the shopping bag.",
      "path": "layers[2].shapes[0].it[1].c.k",
      "originalColor": "#efcfc2ff",
      "elementType": "fill",
      "roleFunction": "primary_subject",
      "visualLevel": "secondary",
      "semanticRole": "illustrative_object",
      "isThemeable": true,
      "isClothing": false,
      "isEffect": false,
      "isBackground": false,
      "elementGroups": [
        "bag",
        "body",
        "themeable",
        "primary"
      ],
      "tags": [
        "rim",
        "detail",
        "accent"
      ]
    },
    "BagBodyAccentFill": {
      "name": "BagBodyAccentFill",
      "alternativeNames": [
        "BagBodyHighlightFill"
      ],
      "description": "The fill color for the accent or highlight panel on the front of the shopping bag body.",
      "path": "layers[3].shapes[0].it[1].c.k",
      "originalColor": "#3e2e82ff",
      "elementType": "fill",
      "roleFunction": "primary_subject",
      "visualLevel": "secondary",
      "semanticRole": "illustrative_object",
      "isThemeable": true,
      "isClothing": false,
      "isEffect": false,
      "isBackground": false,
      "elementGroups": [
        "bag",
        "body",
        "themeable",
        "primary"
      ],
      "tags": [
        "accent",
        "highlight",
        "detail"
      ]
    },
    "BagBodyMainFill": {
      "name": "BagBodyMainFill",
      "alternativeNames": [
        "BagMainFill"
      ],
      "description": "The main fill color for the body of the shopping bag.",
      "path": "layers[4].shapes[0].it[1].c.k",
      "originalColor": "#46308bff",
      "elementType": "fill",
      "roleFunction": "primary_subject",
      "visualLevel": "primary",
      "semanticRole": "illustrative_object",
      "isThemeable": true,
      "isClothing": false,
      "isEffect": false,
      "isBackground": false,
      "elementGroups": [
        "bag",
        "body",
        "themeable",
        "primary"
      ],
      "tags": [
        "main-body",
        "primary-color",
        "brand"
      ]
    }
  }
}
