/**
 * Theme File Generator
 *
 * Generates TypeScript theme files in LottieThemeConfig format
 */

import type { GeneratedTheme, ThemeGenerationResult } from "./types"

/**
 * Generate TypeScript file content for a single theme
 */
export function generateThemeFileContent(
  animationName: string,
  theme: GeneratedTheme,
): string {
  const { themeId, name, description, palette, colors, skippedElements } = theme

  // Format colors object with proper indentation
  const colorsEntries = Object.entries(colors)
    .map(([key, value]) => `    ${key}: "${value}",`)
    .join("\n")

  // Format skipped elements array
  const skippedStr =
    skippedElements.length > 0
      ? `[\n    "${skippedElements.join('",\n    "')}",\n  ]`
      : "[]"

  return `import type { LottieThemeConfig } from "../../../../theming/lottieColorMapping"

export const ${camelCase(themeId.replace(/-/g, "_"))}Theme: LottieThemeConfig = {
  themeId: "${themeId}",
  name: "${name}",
  description: "${description}",
  baseColor: "${palette.baseColor}",
  mode: "${palette.mode}",
  colors: {
${colorsEntries}
  },
  skippedElements: ${skippedStr},
}
`
}

/**
 * Generate a single consolidated themes file with all themes as named exports
 * This is the preferred export format - one file with all themes
 */
export function generateConsolidatedThemesFile(
  animationName: string,
  result: ThemeGenerationResult,
): string {
  const themes = result.themes

  // Generate theme objects for all themes
  const themeExports = themes.map((theme) => {
    const { themeId, name, description, palette, colors, skippedElements } =
      theme
    const constName = `${camelCase(themeId.replace(/-/g, "_"))}Theme`

    // Format colors object with proper indentation
    const colorsEntries = Object.entries(colors)
      .map(([key, value]) => `    ${key}: "${value}",`)
      .join("\n")

    // Format skipped elements array
    const skippedStr =
      skippedElements.length > 0
        ? `[\n    "${skippedElements.join('",\n    "')}",\n  ]`
        : "[]"

    return `export const ${constName}: LottieThemeConfig = {
  themeId: "${themeId}",
  name: "${name}",
  description: "${escapeString(description)}",
  baseColor: "${palette.baseColor}",
  mode: "${palette.mode}",
  colors: {
${colorsEntries}
  },
  skippedElements: ${skippedStr},
}`
  })

  // Generate list of theme constant names for the allThemes array
  const themeNames = themes.map(
    (theme) => `${camelCase(theme.themeId.replace(/-/g, "_"))}Theme`,
  )

  return `/**
 * ${animationName} Theme Configurations
 * Generated by Lottie Naming Tool
 *
 * Variant: ${result.variant}
 * Total themes: ${themes.length}
 */

import type { LottieThemeConfig } from "../../theming/lottieColorMapping"

${themeExports.join("\n\n")}

/**
 * All themes for this animation
 */
export const allThemes: LottieThemeConfig[] = [
  ${themeNames.join(",\n  ")},
]

/**
 * Theme lookup by ID
 */
export const themesById: Record<string, LottieThemeConfig> = {
  ${themeNames.map((name) => `"${themes[themeNames.indexOf(name)].themeId}": ${name}`).join(",\n  ")},
}
`
}

/**
 * Escape string for use in template literals
 */
function escapeString(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"')
}

/**
 * Generate filename for a theme file
 */
export function generateThemeFilename(palette: { id: string }): string {
  return `${palette.id}.ts`
}

/**
 * Generate all theme files for an animation
 */
export function generateAllThemeFiles(
  result: ThemeGenerationResult,
): Array<{ filename: string; content: string; subdirectory: string }> {
  const files: Array<{
    filename: string
    content: string
    subdirectory: string
  }> = []

  for (const theme of result.themes) {
    const filename = generateThemeFilename(theme.palette)
    const content = generateThemeFileContent(result.animationName, theme)
    // Include animation name in path for organization
    const subdirectory = `themes/${result.animationName}/${result.variant}`

    files.push({ filename, content, subdirectory })
  }

  return files
}

/**
 * Generate React component file using createLottieComponent factory
 */
export function generateComponentFileContent(animationName: string): string {
  return `"use client"
/**
 * ${animationName} Animation Component
 *
 * **Theming:**
 * - \`theme\`: Color theme name (e.g., "purple-light", "blue-dark")
 * - \`variant\`: Theme variant ("default" or custom variants)
 *
 * @example
 * \`\`\`tsx
 * <${animationName} width="400px" theme="purple-light" />
 * <${animationName} width="400px" theme="blue-dark" variant="minimal" />
 * \`\`\`
 */

import { createLottieComponent } from "../../theming/createLottieComponent"
import BaseAnimationData from "./${animationName}_ExpanseLottie.json"
import { ${animationName}Schema } from "./${animationName}.expanse-lottie"

export const ${animationName} = createLottieComponent({
  animationName: "${animationName}",
  baseAnimationData: BaseAnimationData,
  schema: ${animationName}Schema,
})

// Re-export types for consumers
export type { LottieComponentProps, LottieComponentRef } from "../../theming/createLottieComponent"
`
}

/**
 * Generate registry entry code snippet for lottieThemeRegistry.ts
 * @deprecated Use generateAnimationThemesFile instead for auto-registration
 */
export function generateRegistryEntrySnippet(
  animationName: string,
  variants: string[],
  themesPerVariant: Record<string, string[]>,
): string {
  const variantEntries = variants
    .map((variant) => {
      const themes = themesPerVariant[variant] || []
      const themesList =
        themes.length > 0 ? `["${themes.join('", "')}"]` : "UNIVERSAL_THEMES"
      return `    { variant: "${variant}", themes: ${themesList} },`
    })
    .join("\n")

  return `// Add this to ANIMATION_THEME_SUPPORT array in lottieThemeRegistry.ts:
createAnimationSupport("${animationName}", [
${variantEntries}
]),`
}

/**
 * Convert string to camelCase
 */
function camelCase(str: string): string {
  return str
    .split(/[_-]/)
    .map((word, index) =>
      index === 0
        ? word.toLowerCase()
        : word.charAt(0).toUpperCase() + word.slice(1).toLowerCase(),
    )
    .join("")
}

/**
 * Generate index file for themes directory
 */
export function generateThemeIndexContent(themes: GeneratedTheme[]): string {
  const imports = themes
    .map((t) => {
      const varName = camelCase(t.themeId.replace(/-/g, "_"))
      const filename = t.palette.id
      return `export { default as ${varName}Theme } from "./${filename}"`
    })
    .join("\n")

  return `/**
 * Theme exports for this animation
 * Auto-generated by Lottie Naming Tool
 */

${imports}
`
}

/**
 * Generate a .themes.ts file for auto-registration in theming/animations/
 *
 * This file is automatically discovered by lottieThemeRegistry.ts
 */
export function generateAnimationThemesFileContent(
  animationName: string,
  variants: string[],
  themesPerVariant: Record<string, string[]>,
): string {
  // Collect all unique theme IDs across variants
  const allThemes = new Set<string>()
  for (const themes of Object.values(themesPerVariant)) {
    themes.forEach((t) => allThemes.add(t))
  }

  // Check if using universal themes (all standard themes)
  const universalThemes = [
    "purple-light",
    "purple-dark",
    "blue-light",
    "blue-dark",
    "green-light",
    "green-dark",
    "orange-light",
    "orange-dark",
    "red-light",
    "red-dark",
    "teal-light",
    "teal-dark",
  ]
  const isUsingUniversal = universalThemes.every((t) => allThemes.has(t))

  // Build variant entries
  const variantEntries = variants
    .map((variant) => {
      const themes = themesPerVariant[variant] || []
      if (isUsingUniversal && themes.length === universalThemes.length) {
        return `  { variant: "${variant}", themes: UNIVERSAL_THEMES },`
      }
      return `  { variant: "${variant}", themes: ["${themes.join('", "')}"] },`
    })
    .join("\n")

  return `/**
 * ${animationName} Theme Support
 * Auto-registered via animations/index.ts
 * Generated by Lottie Naming Tool
 */

import type { VariantThemeSupport } from "../lottieThemeRegistry"

${
  isUsingUniversal
    ? `// Universal themes - matches THEME_REGISTRY universal themes
const UNIVERSAL_THEMES = [
  "purple-light",
  "purple-dark",
  "blue-light",
  "blue-dark",
  "green-light",
  "green-dark",
  "orange-light",
  "orange-dark",
  "red-light",
  "red-dark",
  "teal-light",
  "teal-dark",
]

`
    : ""
}export const animationName = "${animationName}"

export const variantThemes: VariantThemeSupport[] = [
${variantEntries}
]
`
}

/**
 * Get the filename for an animation's .themes.ts file
 */
export function getAnimationThemesFilename(animationName: string): string {
  return `${animationName}.themes.ts`
}
