/**
 * BusinessGrowth Theme Support
 * Auto-registered via animations/index.ts
 * Generated by Lottie Naming Tool
 */

import type { VariantThemeSupport } from "../lottieThemeRegistry"

export const animationName = "BusinessGrowth"

export const variantThemes: VariantThemeSupport[] = [
  { variant: "default", themes: ["purple-light", "purple-dark", "blue-light", "blue-dark", "green-light", "green-dark", "orange-light", "orange-dark", "red-light", "red-dark"] },
]
