// 1 	2 	3 	5 	9 	18 	  81
// 1	4	  8	  16	40  95	  ∞
export enum TICKET_POINT_VALUES {
  ONE_POINT = 1, // Estimated complexity level 1
  TWO_POINTS = 4, // Estimated complexity level 3
  THREE_POINTS = 8, // Estimated complexity level 9
  FIVE_POINTS = 16,
  NINE_POINTS = 45,
  EIGHTEEN_POINTS = 95,
  EIGHTY_ONE_POINTS = Infinity,
}

export enum TICKET_POINT_OPTIONS {
  ONE_POINT = 1,
  TWO_POINTS = 2,
  THREE_POINTS = 3,
  FIVE_POINTS = 5,
  NINE_POINTS = 9,
  EIGHTEEN_POINTS = 18,
  EIGHTY_ONE_POINTS = 81,
}

export const TICKET_POINT_OPTIONS_LIST = [
  TICKET_POINT_OPTIONS.ONE_POINT,
  TICKET_POINT_OPTIONS.TWO_POINTS,
  TICKET_POINT_OPTIONS.THREE_POINTS,
  TICKET_POINT_OPTIONS.FIVE_POINTS,
  TICKET_POINT_OPTIONS.NINE_POINTS,
  TICKET_POINT_OPTIONS.EIGHTEEN_POINTS,
  TICKET_POINT_OPTIONS.EIGHTY_ONE_POINTS,
]
