import type {
  AnimationTemplate,
  Audience,
  Location,
  PipelineTemplate,
  SceneTemplate,
  SequenceTemplate,
  StoryTemplate,
  Target,
} from "@4eye/types";

export const DEFAULT_TARGETS: Target[] = [
  {
    id: "target-self",
    name: "Self",
    targetType: "people",
    symbol: "Person",
    symbolColor: "blue",
    identifiers: ["me", "self"],
    labels: ["primary"],
    createdAt: 0,
  },
  {
    id: "target-mentor",
    name: "Mentor",
    targetType: "teachers",
    symbol: "Star",
    symbolColor: "amber",
    identifiers: ["mentor", "guide"],
    labels: [],
    createdAt: 0,
  },
  // Person profiles (explicit profile records that map to identity entries)
  {
    id: "target-matthew",
    name: "Matthew McKeller",
    targetType: "people",
    symbol: "Person",
    symbolColor: "blue",
    identifiers: ["matthew", "mckeller", "expanse_eye"],
    labels: ["profile"],
    description: "Profile: Matthew McKeller",
    createdAt: 0,
  },
  {
    id: "target-janna",
    name: "Janna",
    targetType: "people",
    symbol: "Person",
    symbolColor: "pink",
    identifiers: ["janna"],
    labels: ["profile"],
    createdAt: 0,
  },
  // Crew-role-style targets (people on the crew, added as simple person targets)
  {
    id: "target-crew-designer",
    name: "Crew — Designer",
    targetType: "people",
    symbol: "Person",
    symbolColor: "teal",
    identifiers: ["designer", "crew-designer"],
    labels: ["definition"],
    description: "A member of the crew: Designer (generic)",
    createdAt: 0,
  },
  {
    id: "target-crew-engineer",
    name: "Crew — Engineer",
    targetType: "people",
    symbol: "Person",
    symbolColor: "slate",
    identifiers: ["engineer", "crew-engineer"],
    labels: ["definition"],
    description: "A member of the crew: Engineer (generic)",
    createdAt: 0,
  },
  // Simple / geopolitical / public figure profiles (labelled as simple profiles)
  {
    id: "target-america",
    name: "America",
    targetType: "groups",
    symbol: "Group",
    symbolColor: "purple",
    identifiers: ["america", "usa", "united states"],
    labels: ["simple"],
    description: "Simple profile: country / large public group",
    createdAt: 0,
  },
  {
    id: "target-japan",
    name: "Japan",
    targetType: "groups",
    symbol: "Group",
    symbolColor: "green",
    identifiers: ["japan"],
    labels: ["simple"],
    createdAt: 0,
  },
  {
    id: "target-trump",
    name: "Donald Trump",
    targetType: "people",
    symbol: "Person",
    symbolColor: "red",
    identifiers: ["trump", "donald trump"],
    labels: ["simple"],
    description: "Public figure — simple profile entry",
    createdAt: 0,
  },
  {
    id: "target-fortune-500-ceos",
    name: "Fortune 500 CEOs",
    targetType: "groups",
    symbol: "Group",
    symbolColor: "amber",
    identifiers: ["fortune 500", "fortune500", "ceos"],
    labels: ["simple", "definition"],
    description: "Broad group label for senior corporate leaders",
    createdAt: 0,
  },
  // Common audience-like targets usable as quick aims
  {
    id: "target-students",
    name: "Students",
    targetType: "classmates",
    symbol: "Group",
    symbolColor: "teal",
    identifiers: ["students"],
    labels: ["definition"],
    createdAt: 0,
  },
  {
    id: "target-teachers",
    name: "Teachers",
    targetType: "teachers",
    symbol: "Group",
    symbolColor: "green",
    identifiers: ["teachers"],
    labels: ["definition"],
    createdAt: 0,
  },
];

export const DEFAULT_AUDIENCES: Audience[] = [
  {
    id: "audience-team",
    name: "Team",
    description: "Immediate working group",
    symbol: "Group",
    symbolColor: "green",
    identifiers: ["team", "group"],
    createdAt: 0,
  },
  {
    id: "audience-public",
    name: "Public",
    description: "General audience",
    symbol: "Group",
    symbolColor: "purple",
    identifiers: ["public", "everyone"],
    createdAt: 0,
  },
  {
    id: "audience-gamers",
    name: "Gamers",
    description: "Players and game communities",
    symbol: "Group",
    symbolColor: "teal",
    identifiers: ["gamers", "gaming", "players"],
    createdAt: 0,
  },
  {
    id: "audience-tech-enthusiast",
    name: "Technology Enthusiast",
    description: "People who follow and explore tech",
    symbol: "Group",
    symbolColor: "blue",
    identifiers: ["tech", "technology", "enthusiast"],
    createdAt: 0,
  },
  {
    id: "audience-truth-seekers",
    name: "People Seeking Truth",
    description: "People oriented toward clarity and truth-seeking",
    symbol: "Group",
    symbolColor: "amber",
    identifiers: ["truth", "seekers", "clarity"],
    createdAt: 0,
  },
];

export const DEFAULT_LOCATIONS: Location[] = [
  {
    id: "location-home",
    name: "Home",
    shortTag: "Home",
    locationType: "home",
    category: "profile",
    symbol: "Place",
    symbolColor: "red",
    identifiers: ["home", "house"],
    createdAt: 0,
  },
  {
    id: "location-work",
    name: "Workspace",
    shortTag: "Work",
    locationType: "work",
    category: "profile",
    symbol: "Place",
    symbolColor: "blue",
    identifiers: ["work", "office"],
    createdAt: 0,
  },
  {
    id: "location-global",
    name: "Global",
    shortTag: "Global",
    locationType: "custom",
    category: "actual",
    symbol: "Place",
    symbolColor: "teal",
    region: "world",
    identifiers: ["global", "worldwide", "world"],
    createdAt: 0,
  },
  {
    id: "location-united-states",
    name: "United States",
    shortTag: "US",
    locationType: "custom",
    category: "actual",
    symbol: "Place",
    symbolColor: "blue",
    region: "north-america",
    identifiers: ["united states", "usa", "us", "america"],
    createdAt: 0,
  },
  {
    id: "location-missouri",
    name: "Missouri",
    shortTag: "MO",
    locationType: "custom",
    category: "actual",
    symbol: "Place",
    symbolColor: "amber",
    region: "united-states",
    identifiers: ["missouri", "mo"],
    createdAt: 0,
  },
  {
    id: "location-california",
    name: "California",
    shortTag: "CA",
    locationType: "custom",
    category: "actual",
    symbol: "Place",
    symbolColor: "green",
    region: "united-states",
    identifiers: ["california", "ca"],
    createdAt: 0,
  },
  {
    id: "location-china",
    name: "China",
    shortTag: "China",
    locationType: "custom",
    category: "actual",
    symbol: "Place",
    symbolColor: "red",
    region: "asia",
    identifiers: ["china", "prc"],
    createdAt: 0,
  },
  {
    id: "location-russia",
    name: "Russia",
    shortTag: "Russia",
    locationType: "custom",
    category: "actual",
    symbol: "Place",
    symbolColor: "purple",
    region: "eurasia",
    identifiers: ["russia", "russian federation"],
    createdAt: 0,
  },
  {
    id: "location-japan",
    name: "Japan",
    shortTag: "Japan",
    locationType: "custom",
    category: "actual",
    symbol: "Place",
    symbolColor: "pink",
    region: "asia",
    identifiers: ["japan", "jp"],
    createdAt: 0,
  },
  {
    id: "location-ukraine",
    name: "Ukraine",
    shortTag: "Ukraine",
    locationType: "custom",
    category: "actual",
    symbol: "Place",
    symbolColor: "blue",
    region: "europe",
    identifiers: ["ukraine", "ua"],
    createdAt: 0,
  },
  {
    id: "location-england",
    name: "England",
    shortTag: "England",
    locationType: "custom",
    category: "actual",
    symbol: "Place",
    symbolColor: "slate",
    region: "europe",
    identifiers: ["england", "uk", "britain"],
    createdAt: 0,
  },
  {
    id: "location-north-korea",
    name: "North Korea",
    shortTag: "NK",
    locationType: "custom",
    category: "actual",
    symbol: "Place",
    symbolColor: "red",
    region: "asia",
    identifiers: ["north korea", "dprk", "nk"],
    createdAt: 0,
  },
];

export const DEFAULT_STORIES: StoryTemplate[] = [
  {
    id: "story-intro",
    name: "Introduction",
    symbol: "AutoStories",
    symbolColor: "amber",
    content: "A short opening that establishes context.",
    identifiers: ["intro", "opening"],
    createdAt: 0,
  },
];

export const DEFAULT_ANIMATIONS: AnimationTemplate[] = [
  {
    id: "animation-pulse",
    name: "Pulse",
    symbol: "Movie",
    symbolColor: "purple",
    keyframes: ["scale-in", "scale-out"],
    identifiers: ["pulse"],
    createdAt: 0,
  },
];

export const DEFAULT_SCENES: SceneTemplate[] = [
  {
    id: "scene-blank",
    name: "Blank",
    symbol: "Image",
    symbolColor: "pink",
    elements: [],
    identifiers: ["blank", "empty"],
    createdAt: 0,
  },
];

export const DEFAULT_SEQUENCES: SequenceTemplate[] = [
  {
    id: "sequence-intro-loop",
    name: "Intro Loop",
    symbol: "Wave",
    symbolColor: "teal",
    steps: ["Blank scene", "Pulse animation"],
    identifiers: ["intro", "loop"],
    createdAt: 0,
  },
  {
    id: "sequence-reveal",
    name: "Reveal",
    symbol: "Wave",
    symbolColor: "amber",
    steps: ["Fade in", "Hero scene", "Title card"],
    identifiers: ["reveal", "hero", "title"],
    createdAt: 0,
  },
  {
    id: "sequence-explainer",
    name: "Explainer",
    symbol: "Wave",
    symbolColor: "blue",
    steps: ["Hook scene", "Concept animation", "Recap scene"],
    identifiers: ["explainer", "teach", "concept"],
    createdAt: 0,
  },
  {
    id: "sequence-outro",
    name: "Outro",
    symbol: "Wave",
    symbolColor: "purple",
    steps: ["Summary scene", "Call to action", "Fade out"],
    identifiers: ["outro", "cta", "closing"],
    createdAt: 0,
  },
];

export const DEFAULT_PIPELINES: PipelineTemplate[] = [
  {
    id: "pipeline-concise",
    name: "Make it Concise",
    symbol: "Pipeline",
    symbolColor: "blue",
    summary: "Compress wording while preserving meaning and tone",
    stages: [
      { name: "Identify filler", description: "Tag low-information words and phrases" },
      { name: "Rewrite", description: "Tighten phrasing without losing key signal" },
    ],
    identifiers: ["concise", "brevity", "tighten"],
    createdAt: 0,
  },
  {
    id: "pipeline-data-stacking",
    name: "Data Stacking",
    symbol: "Pipeline",
    symbolColor: "teal",
    summary: "Embed structured data and supporting facts into the response",
    stages: [
      { name: "Lookup", description: "Resolve relevant data points from context" },
      { name: "Stack", description: "Layer figures, citations, and patterns into the output" },
    ],
    identifiers: ["data", "stacking", "facts"],
    createdAt: 0,
  },
  {
    id: "pipeline-engagement",
    name: "Engagement",
    symbol: "Pipeline",
    symbolColor: "amber",
    summary: "Increase hooks, momentum, and reader pull-through",
    stages: [
      { name: "Hook", description: "Open with a high-signal hook" },
      { name: "Pacing", description: "Tune cadence to sustain attention" },
    ],
    identifiers: ["engagement", "hook", "attention"],
    createdAt: 0,
  },
  {
    id: "pipeline-healing",
    name: "Healing",
    symbol: "Pipeline",
    symbolColor: "green",
    summary: "Reframe with positivity, optimism, and supportive tone",
    stages: [
      { name: "Detect tension", description: "Identify negative or shame-laden framings" },
      { name: "Reframe", description: "Rewrite in a hopeful, growth-oriented voice" },
    ],
    identifiers: ["healing", "positive", "optimism"],
    createdAt: 0,
  },
  {
    id: "pipeline-love",
    name: "Love",
    symbol: "Pipeline",
    symbolColor: "red",
    summary: "Infuse warmth, compassion, and care into the response",
    stages: [
      { name: "Soften", description: "Adjust tone toward warmth and patience" },
      { name: "Affirm", description: "Weave in compassion and affirmation" },
    ],
    identifiers: ["love", "warmth", "compassion"],
    createdAt: 0,
  },
];

export const DEFAULT_CONTEXT_DATA = {
  targets: DEFAULT_TARGETS,
  audiences: DEFAULT_AUDIENCES,
  locations: DEFAULT_LOCATIONS,
  stories: DEFAULT_STORIES,
  animations: DEFAULT_ANIMATIONS,
  scenes: DEFAULT_SCENES,
  sequences: DEFAULT_SEQUENCES,
  pipelines: DEFAULT_PIPELINES,
};
