import { Box, Paper, Typography, Chip, Stack } from '@mui/material';
import { Hub as HubIcon } from '@mui/icons-material';
import { connections, getPersonById, getLocationById, getOrganizationById, getEventById, getItemById } from '../utils/dataService';

export default function Connections() {
  const getEntityName = (type: string, id: string): string => {
    switch (type) {
      case 'person':
        return getPersonById(id)?.name || id;
      case 'location':
        return getLocationById(id)?.name || id;
      case 'organization':
        return getOrganizationById(id)?.name || id;
      case 'event':
        return getEventById(id)?.title || id;
      case 'item':
        return getItemById(id)?.name || id;
      default:
        return id;
    }
  };

  const getStrengthColor = (strength?: string) => {
    switch (strength) {
      case 'strong': return 'success';
      case 'moderate': return 'warning';
      case 'weak': return 'error';
      default: return 'default';
    }
  };

  return (
    <Box>
      <Typography variant="h4" gutterBottom>
        Connections ({connections.length})
      </Typography>

      <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
        Relationships between entities in the data (auto-generated by AI)
      </Typography>

      <Stack spacing={2}>
        {connections.map((conn) => (
          <Paper key={conn.id} sx={{ p: 2 }}>
            <Stack direction="row" spacing={2} alignItems="center">
              <HubIcon color="primary" />
              
              <Box sx={{ flex: 1 }}>
                <Stack direction="row" alignItems="center" spacing={2} flexWrap="wrap" gap={1}>
                  {/* From entity */}
                  <Box sx={{ textAlign: 'center' }}>
                    <Chip 
                      size="small" 
                      label={conn.fromEntityType} 
                      sx={{ mb: 0.5 }}
                    />
                    <Typography variant="subtitle1" sx={{ fontWeight: 'bold' }}>
                      {getEntityName(conn.fromEntityType, conn.fromEntityId)}
                    </Typography>
                  </Box>

                  {/* Connection arrow and type */}
                  <Box sx={{ 
                    display: 'flex', 
                    flexDirection: 'column', 
                    alignItems: 'center',
                    px: 2,
                  }}>
                    <Typography variant="caption" color="text.secondary">
                      {conn.relationshipType || conn.type}
                    </Typography>
                    <Box sx={{ 
                      display: 'flex', 
                      alignItems: 'center',
                      color: 'primary.main',
                    }}>
                      <Box sx={{ width: 40, height: 2, backgroundColor: 'primary.main' }} />
                      →
                    </Box>
                    {conn.strength && (
                      <Chip 
                        size="small" 
                        label={conn.strength} 
                        color={getStrengthColor(conn.strength) as 'success' | 'warning' | 'error' | 'default'}
                        sx={{ mt: 0.5 }}
                      />
                    )}
                  </Box>

                  {/* To entity */}
                  <Box sx={{ textAlign: 'center' }}>
                    <Chip 
                      size="small" 
                      label={conn.toEntityType} 
                      sx={{ mb: 0.5 }}
                    />
                    <Typography variant="subtitle1" sx={{ fontWeight: 'bold' }}>
                      {getEntityName(conn.toEntityType, conn.toEntityId)}
                    </Typography>
                  </Box>
                </Stack>

                {conn.relationshipDescription && (
                  <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
                    {conn.relationshipDescription}
                  </Typography>
                )}

                {conn.perspective && (
                  <Chip 
                    size="small" 
                    label={`Perspective: ${conn.perspective}`} 
                    variant="outlined" 
                    sx={{ mt: 1 }}
                  />
                )}

                {conn.supportingEvidence && conn.supportingEvidence.length > 0 && (
                  <Box sx={{ mt: 1 }}>
                    <Typography variant="caption" color="text.secondary">
                      Supporting evidence: {conn.supportingEvidence.join(', ')}
                    </Typography>
                  </Box>
                )}

                {conn.notes && (
                  <Box sx={{ mt: 1, pt: 1, borderTop: '1px solid', borderColor: 'divider' }}>
                    <Typography variant="caption" color="text.secondary">
                      Notes: {conn.notes}
                    </Typography>
                  </Box>
                )}
              </Box>
            </Stack>
          </Paper>
        ))}
      </Stack>
    </Box>
  );
}
